-- =============================================================================
-- V122__communications_device_token.sql  —  Push device-token registry (communications, EI-5).
--
-- Responsibility: create the `device_token` table behind the JPA entity
-- com.taarifu.communications.domain.model.DeviceToken (the binding "this profile is
-- reachable on this push device"). It gives the push path a real fan-out target: the
-- PushSender/FcmHttpPushSender resolves a recipient's live tokens and delivers to each
-- device, pruning tokens FCM reports invalid. MUST match the entity so
-- ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §13, US-5.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * profile_id is a bare UUID, NOT a foreign key — the owner is an `identity` profile,
--     owned by another module (ARCHITECTURE §3.2, parallel-build isolation).
--   * `token` is a SENSITIVE routing credential (its holder can push to the device).
--     It is treated as a secret: NEVER logged by the service/adapter (they log the owning
--     profile UUID + a token count only), and it never enters an event payload or a
--     cross-user DTO (PRD §18, CLAUDE.md §12). It is not field-encrypted (it is not citizen
--     PII and rotates frequently) — the no-log discipline is the control.
--   * ONE registration per `token` AMONG LIVE ROWS: registering a known token is an
--     idempotent re-bind/refresh (never a duplicate row), so a push never double-delivers
--     to one device. Unregister (logout) and invalid-token pruning are soft-deletes
--     (history stays auditable, PRD §9), so uniqueness must be scoped to deleted = false —
--     JPA cannot express partial uniqueness, so the DB owns a PARTIAL UNIQUE INDEX here.
--     The table-level UNIQUE on the entity documents the intent; this partial index is the
--     authoritative guarantee (and correctly allows a re-register after an unregister).
--
-- NOTE on the entity's @UniqueConstraint: Hibernate ddl-auto=validate does NOT verify
--   table-level UNIQUE constraints/indexes (it validates columns, types, nullability), so
--   declaring the live-scoped partial unique index here — instead of a full UNIQUE matching
--   the annotation — keeps validate green while giving the stronger, soft-delete-aware rule.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE device_token (
    -- BaseEntity (ARCHITECTURE §4.2).
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    version       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE,
    created_by    UUID,
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    UUID,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    UUID,

    -- Domain columns (DeviceToken.java).
    profile_id    UUID         NOT NULL,                 -- bare ref to identity profile; never a FK
    token         VARCHAR(512) NOT NULL,                 -- opaque FCM/APNs/WebPush token; SECRET — never logged
    platform      VARCHAR(16)  NOT NULL,                 -- DevicePlatform
    last_seen_at  TIMESTAMP WITH TIME ZONE NOT NULL,     -- last (re-)registration / reachable confirmation

    CONSTRAINT uq_device_token_public_id UNIQUE (public_id),
    CONSTRAINT ck_device_token_platform CHECK (platform IN ('ANDROID','IOS','WEB'))
);

-- Entity-declared lookup indexes.
-- Push fan-out's hot read: all live tokens for a recipient profile.
CREATE INDEX ix_device_token_profile ON device_token (profile_id);
-- Unregister / prune by raw token value.
CREATE INDEX ix_device_token_value   ON device_token (token);

-- INVARIANT (DB-owned): at most ONE LIVE registration per `token`.
-- Scoped to live rows so a soft-deleted (unregistered/pruned) token never blocks a fresh re-register.
CREATE UNIQUE INDEX ux_device_token_token_live
    ON device_token (token)
    WHERE deleted = FALSE;

COMMENT ON TABLE  device_token              IS 'Push device-token registry: a profile is reachable on a device; the push path fans out to live tokens (PRD §13, EI-5, US-5.1).';
COMMENT ON COLUMN device_token.profile_id   IS 'Owning profile publicId (identity); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN device_token.token        IS 'Opaque FCM/APNs/WebPush registration token; SECRET routing credential — never logged, never returned to other users (PRD §18).';
COMMENT ON COLUMN device_token.platform     IS 'DevicePlatform discriminator: ANDROID, IOS, WEB (descriptive; FCM delivers all in this MVP).';
COMMENT ON COLUMN device_token.last_seen_at IS 'Last (re-)registration / reachable confirmation instant (UTC); refreshed on idempotent re-register.';
