-- =============================================================================
-- V130__payments_top_up.sql  —  Phase-2 Wave-1: mobile-money token TOP-UP
--                               (payments module, ADR-0015, PRD §23.4/§23.5/§23.6,
--                                §25.10, D18). Flyway block V130–V139 reserved for
--                                the payments module.
--
-- Responsibility: create top_up — the money-movement lifecycle of one wallet
-- top-up via TZ mobile money (M-Pesa/Tigo Pesa/Airtel Money/HaloPesa). Tokens
-- are credited to the buyer's wallet (a PURCHASE credit via tokens.api) ONLY on
-- a provider-VERIFIED settlement (status SUCCEEDED), exactly once and reconciled
-- — never on the unverified callback alone (PRD §23.5 anti-fraud). top_up is a
-- BaseEntity subclass and MUST match the JPA entity for ddl-auto=validate
-- (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * 🔒 FENCE (D18): a top-up credits the CONVENIENCE wallet only. It never buys
--     democratic weight (no signature/rating/poll outcome/routing/SLA/role/
--     verification). Buyer & wallet owner are referenced by opaque UUID — there is
--     NO cross-module FK into identity or tokens (ADR-0013); the wallet lives in
--     the tokens module and is credited through its published api port.
--   * Money is stored in MINOR UNITS as BIGINT, never floating-point — rounding
--     corruption is unacceptable on money (paranoid-on-money; standard fintech).
--   * idempotency_key is UNIQUE: a replayed initiation (client retry, duplicate
--     request) is a no-op — one purchase attempt = one row (PRD §23.5).
--   * (provider, provider_ref) is PARTIAL-UNIQUE (where provider_ref IS NOT NULL):
--     one provider settlement = one row, so a duplicate/out-of-order webhook is a
--     no-op — this is the reconciliation anchor.
--   * credit_event_id keys the wallet credit so a redelivered SUCCEEDED callback
--     credits exactly once (the ledger's idempotency discipline, PRD §23.5).
--   * failure_reason is REDACTED — no PII, no provider body (PRD §18).
--   * This SUPERSEDES the legacy MVP stub seam tokens.payment (V33) for the FLOW;
--     that table stays as history (ADR-0015 consequences).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- top_up — lifecycle of one mobile-money token top-up attempt (Phase-2 Wave-1).
-- -----------------------------------------------------------------------------
CREATE TABLE top_up (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    buyer_id          UUID         NOT NULL,                 -- buyer account public id (opaque; NO FK)
    wallet_owner_type VARCHAR(16)  NOT NULL,                 -- WalletOwnerKind: USER/ORGANIZATION
    provider          VARCHAR(16)  NOT NULL,                 -- MobileMoneyProvider: MPESA/TIGOPESA/AIRTELMONEY/HALOPESA
    provider_ref      VARCHAR(128),                          -- provider settlement reference (set on initiation/callback)
    amount_minor      BIGINT       NOT NULL,                 -- amount collected, in minor currency units
    token_amount      BIGINT       NOT NULL,                 -- tokens credited on SUCCEEDED; > 0
    currency          VARCHAR(3)   NOT NULL DEFAULT 'TZS',   -- ISO-4217
    status            VARCHAR(16)  NOT NULL DEFAULT 'INITIATED', -- TopUpStatus: INITIATED/PENDING/SUCCEEDED/FAILED
    idempotency_key   VARCHAR(200) NOT NULL,                 -- UNIQUE; dedups initiation/retries (PRD §23.5)
    credit_event_id   UUID,                                  -- wallet-credit idempotency key (set once, on credit)
    failure_reason    VARCHAR(256),                          -- REDACTED machine reason on FAILED (no PII)

    CONSTRAINT uq_top_up_public_id   UNIQUE (public_id),
    CONSTRAINT uq_top_up_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_top_up_owner_type  CHECK (wallet_owner_type IN ('USER','ORGANIZATION')),
    CONSTRAINT ck_top_up_provider    CHECK (provider IN ('MPESA','TIGOPESA','AIRTELMONEY','HALOPESA')),
    CONSTRAINT ck_top_up_status      CHECK (status   IN ('INITIATED','PENDING','SUCCEEDED','FAILED')),
    CONSTRAINT ck_top_up_amount_nonneg CHECK (amount_minor >= 0),
    CONSTRAINT ck_top_up_tokens_pos    CHECK (token_amount > 0)
);

-- One provider settlement = one row (reconciliation anchor). PARTIAL so multiple
-- not-yet-referenced rows (provider_ref NULL before the rail accepts) coexist.
CREATE UNIQUE INDEX uq_top_up_provider_ref
    ON top_up (provider, provider_ref)
    WHERE provider_ref IS NOT NULL;

CREATE INDEX ix_top_up_buyer  ON top_up (buyer_id);
CREATE INDEX ix_top_up_status ON top_up (status);

COMMENT ON TABLE  top_up                  IS 'Mobile-money token top-up lifecycle (ADR-0015, PRD §23.6). Convenience-wallet credit ONLY — never democratic weight (D18). Credited on provider-verified SUCCEEDED, idempotently — never trust-the-callback (PRD §23.5).';
COMMENT ON COLUMN top_up.buyer_id         IS 'Buyer account public id (opaque UUID; NO cross-module FK into identity — ADR-0013).';
COMMENT ON COLUMN top_up.amount_minor     IS 'Amount in the currency minor units (BIGINT) — never floating-point money (rounding safety).';
COMMENT ON COLUMN top_up.idempotency_key  IS 'UNIQUE; one purchase attempt = one row, so a duplicate initiation/retry is a no-op (anti-fraud, PRD §23.5).';
COMMENT ON COLUMN top_up.provider_ref     IS 'Provider settlement reference; (provider, provider_ref) is partial-unique so a duplicate/out-of-order webhook reconciles to exactly one row — never the raw callback body.';
COMMENT ON COLUMN top_up.credit_event_id  IS 'Idempotency key under which the wallet credit was posted; makes a redelivered SUCCEEDED callback credit exactly once (PRD §23.5).';
COMMENT ON COLUMN top_up.failure_reason   IS 'Redacted machine reason on FAILED — no PII, no provider body (PRD §18).';
