-- =============================================================================
-- V140__privacy_consent.sql  —  PDPA consent ledger (privacy module, ADR-0016 §2).
--
-- Responsibility: create the `consent` table behind the JPA entity
-- com.taarifu.privacy.domain.model.Consent — the VERSIONED, APPEND-ON-CHANGE record
-- of every consent decision a citizen makes for a processing purpose (PRD §18 PDPA
-- 2022/2023, UC-A16, US-0.7). MUST match the entity exactly so Hibernate
-- ddl-auto=validate passes (ARCHITECTURE §4.1).
--
-- WHY the V140 range: ADR-0016 reserves V140–V145 as a NEW per-feature range for the
-- privacy module (the next free block after the cross-cutting tail …V96/V97 and the
-- wave-3 seeds V100–V122). Forward-only; never edit once applied (CLAUDE.md §12).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * APPEND-ON-CHANGE, not mutate-in-place: a grant or a withdrawal for a
--     (subject, purpose) is a NEW row; the prior current row is flagged `superseded`.
--     The CURRENT consent for a (subject, purpose) is the single row with
--     superseded=false. WHY: consent HISTORY is itself the evidence PDPA requires
--     (when granted, when withdrawn, under which policy version) and must be
--     reconstructable — mutating a row would destroy that trail (the same philosophy
--     as the immutable audit log, §25.1).
--   * 🔒 NO PII (PRD §18): the only person-reference is `subject_public_id` — the
--     subject's OWN account public id (a bare cross-module UUID to identity,
--     intentionally NOT a foreign key — ADR-0013 §3.2). No name, phone, email, ID, or
--     free text ever enters this table.
--   * IS a BaseEntity (ARCHITECTURE §4.2): id + public_id + audit + soft-delete +
--     version. Consent rows are never user-deletable (a withdrawal is a new WITHDRAWN
--     row, not a delete); the soft-delete columns come with BaseEntity and are reserved
--     for retention/erasure tooling.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id              -> bigint identity PK
--   UUID public_id       -> uuid not null unique
--   UUID subject_public_id-> uuid not null
--   String purpose (enum)-> varchar(48) not null  (@Enumerated(STRING))
--   String state (enum)  -> varchar(16) not null  (@Enumerated(STRING))
--   String policy_version-> varchar(32) not null
--   String source        -> varchar(16) (nullable)
--   Instant granted_at   -> timestamptz (nullable)
--   Instant withdrawn_at -> timestamptz (nullable)
--   boolean superseded   -> boolean not null
--   BaseEntity audit/soft-delete/version columns as elsewhere.
-- =============================================================================

CREATE TABLE consent (
    -- BaseEntity (ARCHITECTURE §4.2).
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    -- Domain columns (Consent.java).
    subject_public_id UUID         NOT NULL,                 -- the consenting account (bare UUID, never a FK)
    purpose           VARCHAR(48)  NOT NULL,                 -- ConsentPurpose (@Enumerated STRING)
    state             VARCHAR(16)  NOT NULL,                 -- ConsentState GRANTED|WITHDRAWN
    policy_version    VARCHAR(32)  NOT NULL,                 -- informed-consent: policy/text version decided under
    source            VARCHAR(16),                           -- coarse channel WEB/APP/USSD (diagnostics, never PII)
    granted_at        TIMESTAMP WITH TIME ZONE,              -- set for a GRANTED row
    withdrawn_at      TIMESTAMP WITH TIME ZONE,              -- set for a WITHDRAWN row
    superseded        BOOLEAN      NOT NULL DEFAULT FALSE,   -- true once a later decision replaced this row

    CONSTRAINT uq_consent_public_id UNIQUE (public_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs for the @Enumerated(STRING) columns.
    CONSTRAINT ck_consent_purpose CHECK (purpose IN
        ('DATA_SHARING_PRIVATE_RESPONDER','BEHAVIOURAL_ANALYTICS','MARKETING_NOTIFICATIONS','PROFILING')),
    CONSTRAINT ck_consent_state CHECK (state IN ('GRANTED','WITHDRAWN'))
);

-- The hot read: "the current consent for this subject + purpose" — subject + purpose, not-superseded.
CREATE INDEX ix_consent_subject_purpose ON consent (subject_public_id, purpose, superseded);
-- The privacy-center read + export section: all of a subject's current decisions.
CREATE INDEX ix_consent_subject ON consent (subject_public_id);

COMMENT ON TABLE  consent                   IS 'PDPA consent ledger: versioned, append-on-change consent decisions per (subject, purpose). The current decision for a pair is the single superseded=false row (ADR-0016 §2). 🔒 No PII beyond the subject''s own account public id.';
COMMENT ON COLUMN consent.subject_public_id IS 'The consenting account''s public id (self-asserted). Bare cross-module reference to identity — never an FK (ADR-0013 §3.2).';
COMMENT ON COLUMN consent.purpose           IS 'ConsentPurpose (governed enum, append-only). The processing purpose the decision is about (e.g. DATA_SHARING_PRIVATE_RESPONDER gates §24 private-responder sharing).';
COMMENT ON COLUMN consent.state             IS 'ConsentState: GRANTED (active lawful basis) | WITHDRAWN (PDPA right to withdraw).';
COMMENT ON COLUMN consent.policy_version    IS 'The privacy-policy / consent-text version the decision was made against (informed consent — a policy change can re-prompt).';
COMMENT ON COLUMN consent.superseded        IS 'true once a later decision for the same (subject, purpose) replaced this row; the latest decision is always superseded=false. Makes "current consent" a single-row lookup (append-on-change history is preserved).';
