-- =============================================================================
-- V141__privacy_data_subject_request.sql  —  PDPA data-subject requests
--                                            (privacy module, ADR-0016 §3).
--
-- Responsibility: create the `data_subject_request` table behind the JPA entity
-- com.taarifu.privacy.domain.model.DataSubjectRequest — the tracked ACCESS (export) /
-- ERASURE (right-to-be-forgotten) requests with the §25.1 SLA and legal-hold state
-- (PRD §18 PDPA, §25.1, UC-A17/UC-S09). MUST match the entity exactly so Hibernate
-- ddl-auto=validate passes (ARCHITECTURE §4.1).
--
-- WHY V141 (privacy range V140–V145, ADR-0016). Forward-only; never edit once applied.
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * WHY a persisted request (not fire-and-forget): PDPA obligates the controller to
--     DEMONSTRATE it honoured the right within SLA (acknowledge ≤72h, complete ≤30 days
--     — §25.1). The row is the auditable proof; erasure is asynchronous (it fans out
--     across modules via the ERASURE_REQUESTED outbox event) so the request tracks
--     completion. `due_at` = requested_at + 30 days drives the operator dashboard.
--   * LEGAL HOLD (§25.1): `legal_hold=true` parks an erasure at status ON_HOLD — an item
--     under investigation is exempt from erasure until released. The erasure handlers
--     honour it (no severing while held).
--   * 🔒 NO PII (PRD §18): the subject is identified by their AUTHENTICATED account
--     public id (`subject_public_id` — a bare cross-module UUID to identity, NOT an FK,
--     ADR-0013 §3.2), never a re-submitted name/phone/ID. `reason_code` is a machine
--     token (e.g. UNDER_INVESTIGATION / SUBJECT_UNVERIFIABLE), never free text or PII.
--   * IS a BaseEntity (ARCHITECTURE §4.2).
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id               -> bigint identity PK
--   UUID public_id        -> uuid not null unique
--   UUID subject_public_id-> uuid not null
--   String type (enum)    -> varchar(16) not null  (@Enumerated STRING)
--   String status (enum)  -> varchar(16) not null  (@Enumerated STRING)
--   Instant requested_at  -> timestamptz not null
--   Instant acknowledged_at-> timestamptz (nullable)
--   Instant completed_at  -> timestamptz (nullable)
--   Instant due_at        -> timestamptz not null
--   boolean legal_hold    -> boolean not null
--   String reason_code    -> varchar(64) (nullable)
--   BaseEntity audit/soft-delete/version columns as elsewhere.
-- =============================================================================

CREATE TABLE data_subject_request (
    -- BaseEntity (ARCHITECTURE §4.2).
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    -- Domain columns (DataSubjectRequest.java).
    subject_public_id UUID         NOT NULL,                 -- requesting account (bare UUID, never a FK)
    type              VARCHAR(16)  NOT NULL,                 -- DsrType ACCESS|ERASURE
    status            VARCHAR(16)  NOT NULL DEFAULT 'RECEIVED', -- DsrStatus lifecycle
    requested_at      TIMESTAMP WITH TIME ZONE NOT NULL,     -- SLA clock origin
    acknowledged_at   TIMESTAMP WITH TIME ZONE,              -- ≤72h obligation met (§25.1)
    completed_at      TIMESTAMP WITH TIME ZONE,              -- terminal close instant
    due_at            TIMESTAMP WITH TIME ZONE NOT NULL,     -- requested_at + 30 days (§25.1)
    legal_hold        BOOLEAN      NOT NULL DEFAULT FALSE,   -- suspends erasure (under investigation, §25.1)
    reason_code       VARCHAR(64),                           -- machine reason (hold/rejection); never PII

    CONSTRAINT uq_dsr_public_id UNIQUE (public_id),
    CONSTRAINT ck_dsr_type   CHECK (type   IN ('ACCESS','ERASURE')),
    CONSTRAINT ck_dsr_status CHECK (status IN
        ('RECEIVED','ACKNOWLEDGED','IN_PROGRESS','COMPLETED','REJECTED','ON_HOLD'))
);

-- The subject's own request lookup + the idempotency probe (open request of a type).
CREATE INDEX ix_dsr_subject ON data_subject_request (subject_public_id);
-- The ADMIN/ROOT operator queue: open requests, oldest-due first.
CREATE INDEX ix_dsr_status_due ON data_subject_request (status, due_at);

COMMENT ON TABLE  data_subject_request                   IS 'PDPA data-subject requests (ACCESS export / ERASURE right-to-be-forgotten) with the §25.1 SLA + legal hold. The auditable proof the right was honoured within SLA; erasure fan-out is async via the ERASURE_REQUESTED outbox event (ADR-0016 §3/§5). 🔒 No PII beyond the subject''s own account public id.';
COMMENT ON COLUMN data_subject_request.subject_public_id IS 'The requesting account''s public id (self-asserted, never a body id). Bare cross-module reference to identity — never an FK (ADR-0013 §3.2).';
COMMENT ON COLUMN data_subject_request.type              IS 'DsrType: ACCESS (export, right of access) | ERASURE (right to be forgotten, fulfilled as de-identification + tombstoning, not row deletion — §25.1).';
COMMENT ON COLUMN data_subject_request.status            IS 'DsrStatus lifecycle: RECEIVED -> ACKNOWLEDGED (≤72h) -> IN_PROGRESS -> COMPLETED | REJECTED | ON_HOLD (legal hold suspends erasure, §25.1).';
COMMENT ON COLUMN data_subject_request.due_at            IS 'Completion SLA deadline = requested_at + 30 days (PRD §25.1); surfaced to the operator dashboard so an at-risk request is visible.';
COMMENT ON COLUMN data_subject_request.legal_hold        IS 'true while a legal hold suspends fulfilment — an item under investigation is exempt from erasure until released (§25.1). The erasure handlers must honour it.';
COMMENT ON COLUMN data_subject_request.reason_code       IS 'Machine reason code (e.g. UNDER_INVESTIGATION on hold, SUBJECT_UNVERIFIABLE on rejection); never free text or PII (PRD §18, L-1).';
