-- =============================================================================
-- V146__search_document.sql  —  Cross-entity discovery index (search, ADR-0017).
--
-- Responsibility: create the `search_document` table behind the JPA entity
-- com.taarifu.search.domain.model.SearchDocument — ONE denormalised, full-text
-- read-projection per searchable thing (representative / organisation / announcement /
-- issue-category / public report). It is the Postgres-FTS search index: GET /search
-- matches keywords against a tsvector (GIN-indexed) and filters by area/category in a
-- single indexed query, then returns the source aggregate's public id for the client to
-- re-read the full record from its owning module (the index never returns the aggregate —
-- ADR-0013). MUST match the entity so Hibernate ddl-auto=validate passes (ARCHITECTURE §4.1).
--
-- WHY V146 (search's reserved block V146–V149): the search module's parallel-build Flyway
-- range, after the existing tail (…V122). Forward-only; never edit once applied — add a new
-- migration (CLAUDE.md §12).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * This is a READ-PROJECTION, not a source of truth. The authoritative data stays in the
--     owning module; the owner PUSHES this projection via search.api.SearchIndexApi
--     (owner→search direction — no cross-module reach-in, no cycle — ADR-0017 §1, ADR-0013 §1).
--   * 🔒 PUBLIC-DISPLAY DATA + OPAQUE IDS ONLY — NEVER PII (PRD §18, ADR-0017 §1): title,
--     public localised snippets, free keywords, and opaque entity/area/category/author UUIDs.
--     No phone, national/voter ID, free GPS, or private body text ever enters this table.
--   * entity_public_id / area_id / category_id / authored_by_account_id are BARE PUBLIC UUIDs
--     of other modules' aggregates — intentionally NOT foreign keys (cross-module references
--     are opaque UUIDs — ADR-0013 §3.2). search is a leaf: nothing FK-references it.
--   * visibility is the SERVER-SIDE GATE (PUBLIC any reader | STAFF staff-only). The query
--     service ADDS the STAFF tier to the predicate only for staff callers; a guest/citizen
--     sees PUBLIC rows only, so private/sensitive rows are FILTERED OUT (never 403'd per-row —
--     anti-enumeration, PRD §18, ADR-0017 §4).
--   * authored_by_account_id is used ONLY for visibility maintenance (a suspended author's
--     rows are hidden by the MODERATION_SANCTION_APPLIED outbox handler — ADR-0017 §3); it is
--     never returned to a reader.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id                       -> bigint identity PK
--   UUID public_id                -> uuid not null unique
--   String entity_type (enum)     -> varchar(32)  not null  (@Enumerated(STRING))
--   UUID entity_public_id         -> uuid         not null
--   String title                  -> varchar(512) not null
--   String snippet_sw             -> varchar(1024) (nullable)
--   String snippet_en             -> varchar(1024) (nullable)
--   String keywords               -> varchar(1024) (nullable)
--   UUID area_id                  -> uuid         (nullable)
--   UUID category_id              -> uuid         (nullable)
--   String visibility (enum)      -> varchar(16)  not null  (@Enumerated(STRING))
--   UUID authored_by_account_id   -> uuid         (nullable)
--   (search_vector is DB-owned, UNMAPPED on the entity — see below)
-- =============================================================================

CREATE TABLE search_document (
    -- BaseEntity (ARCHITECTURE §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID          NOT NULL,
    version                 BIGINT        NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE,
    created_by              UUID,
    updated_at              TIMESTAMP WITH TIME ZONE,
    updated_by              UUID,
    deleted                 BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP WITH TIME ZONE,
    deleted_by              UUID,

    -- Domain columns (SearchDocument.java).
    entity_type             VARCHAR(32)   NOT NULL,           -- SearchEntityType discriminator
    entity_public_id        UUID          NOT NULL,           -- source aggregate public id; bare UUID, never a FK
    title                   VARCHAR(512)  NOT NULL,           -- display label; weighted A in the tsvector
    snippet_sw              VARCHAR(1024),                     -- localised SW public preview
    snippet_en              VARCHAR(1024),                     -- localised EN public preview
    keywords                VARCHAR(1024),                     -- owner-supplied synonyms/codes; weighted B
    area_id                 UUID,                              -- Ward-or-coarser area; bare UUID, never a FK
    category_id             UUID,                              -- issue-category; bare UUID, never a FK
    visibility              VARCHAR(16)   NOT NULL,            -- SearchVisibility gate (PUBLIC | STAFF)
    authored_by_account_id  UUID,                              -- opaque author account; visibility maintenance only

    -- DB-OWNED, UNMAPPED full-text column (ADR-0017 §2). GENERATED ALWAYS … STORED so it can
    -- never drift from / be overwritten by JPA. The 'simple' configuration case-folds + tokenises
    -- WITHOUT English stemming — the safe choice for a Swahili-first corpus (English stemming would
    -- mangle Swahili tokens; a Swahili dictionary/unaccent + synonyms is a documented follow-up).
    -- Weights: title=A (most relevant), keywords=B, snippets=C; coalesce so NULLs don't break it.
    search_vector           TSVECTOR
        GENERATED ALWAYS AS (
            setweight(to_tsvector('simple', coalesce(title, '')),      'A') ||
            setweight(to_tsvector('simple', coalesce(keywords, '')),   'B') ||
            setweight(to_tsvector('simple', coalesce(snippet_sw, '')), 'C') ||
            setweight(to_tsvector('simple', coalesce(snippet_en, '')), 'C')
        ) STORED,

    CONSTRAINT uq_search_document_public_id UNIQUE (public_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs for the @Enumerated(STRING) columns.
    CONSTRAINT ck_search_document_entity_type CHECK (entity_type IN
        ('REPRESENTATIVE','ORGANISATION','ANNOUNCEMENT','ISSUE_CATEGORY','PUBLIC_REPORT')),
    CONSTRAINT ck_search_document_visibility CHECK (visibility IN ('PUBLIC','STAFF'))
);

-- The FTS query path: search_vector @@ websearch_to_tsquery('simple', :q), ranked by ts_rank.
CREATE INDEX ix_search_document_vector ON search_document USING GIN (search_vector);

-- Filter b-tree indexes (entity-declared as @Index; created here authoritatively).
CREATE INDEX ix_search_document_type     ON search_document (entity_type);
CREATE INDEX ix_search_document_area     ON search_document (area_id);
CREATE INDEX ix_search_document_category ON search_document (category_id);
-- Author index supports the visibility-maintenance handler's "hide all rows by this account" update.
CREATE INDEX ix_search_document_author   ON search_document (authored_by_account_id);

-- INVARIANT (DB-owned): at most ONE LIVE projection per source aggregate. Scoped to live rows so a
-- soft-deleted (removed) projection never blocks a fresh re-index of the same source. This makes the
-- owner's push an idempotent UPSERT (re-push updates the one row, never duplicates — ADR-0017 §1/§3).
-- Partial uniqueness JPA cannot express, so the DB owns it here (validate ignores indexes anyway).
CREATE UNIQUE INDEX ux_search_document_source_live
    ON search_document (entity_type, entity_public_id)
    WHERE deleted = FALSE;

COMMENT ON TABLE  search_document                        IS 'Cross-entity discovery read-projection (Postgres FTS). One denormalised, GIN-indexed row per searchable entity, PUSHED by its owning module via search.api.SearchIndexApi (owner→search; no reach-in). Public display data + opaque ids ONLY — never PII (ADR-0017, PRD §18).';
COMMENT ON COLUMN search_document.entity_type            IS 'SearchEntityType: REPRESENTATIVE | ORGANISATION | ANNOUNCEMENT | ISSUE_CATEGORY | PUBLIC_REPORT.';
COMMENT ON COLUMN search_document.entity_public_id       IS 'Source aggregate PUBLIC id (UUID). Bare cross-module reference — never an internal id, never a FK (ADR-0013 §3.2). The client re-reads the full record from the owning module by this id.';
COMMENT ON COLUMN search_document.title                  IS 'Primary display label (rep name+seat / org name / announcement·category·report title); weighted A in search_vector.';
COMMENT ON COLUMN search_document.snippet_sw             IS 'Short localised Swahili PUBLIC preview (lean payload, PRD §15). Never PII.';
COMMENT ON COLUMN search_document.snippet_en             IS 'Short localised English PUBLIC preview. Never PII.';
COMMENT ON COLUMN search_document.keywords               IS 'Owner-supplied extra search terms (Swahili synonyms, codes); weighted B in search_vector.';
COMMENT ON COLUMN search_document.area_id                IS 'Ward-or-coarser area PUBLIC id for the area filter (PRD §9.0); bare UUID, never a FK.';
COMMENT ON COLUMN search_document.category_id            IS 'Issue-category PUBLIC id for the category filter; bare UUID, never a FK.';
COMMENT ON COLUMN search_document.visibility             IS 'SearchVisibility server-side gate: PUBLIC (any reader) | STAFF (authorised staff only). Private rows are FILTERED OUT for guests/citizens — never 403''d per row (anti-enumeration, PRD §18).';
COMMENT ON COLUMN search_document.authored_by_account_id IS 'Opaque author ACCOUNT public id — used ONLY for visibility maintenance (hide a suspended author''s rows, ADR-0017 §3). Never returned to a reader.';
COMMENT ON COLUMN search_document.search_vector          IS 'DB-OWNED, UNMAPPED tsvector (GENERATED ALWAYS … STORED, ''simple'' config — no English stemming, Swahili-safe). Weights title=A, keywords=B, snippets=C. The FTS match/rank target; GIN-indexed.';
