-- =============================================================================
-- V180__accountability_promise_status_entry.sql
--   Append-only promise STATUS TIMELINE (accountability, M6, US-6.3).
--
-- Responsibility: create promise_status_entry behind
-- com.taarifu.accountability.domain.model.PromiseStatusEntry — one immutable, citizen-visible
-- row per promise status transition (and the originating MADE state). It is the dated provenance
-- behind promise.status (the denormalised "latest"), so a citizen sees not just where a promise
-- is but how it got there. MUST match the entity so ddl-auto=validate passes.
--
-- APPEND-ONLY accountability record (PRD §10, election-period neutrality): each curated move
-- (D-Q4) APPENDS a new entry; history is never rewritten — rewriting it would let a status
-- judgement be silently changed. The service appends a row on promise create and on each genuine
-- transition; there is no update/delete path.
--
-- SAME-MODULE FK (NOT a cross-module reference): promise lives in THIS module, so promise_id is a
-- real, enforced FK to promise(id) — the "reference by id, never an FK" rule applies only ACROSS
-- module boundaries (ARCHITECTURE §4.3). evidence_ref is an OBJECT-STORE KEY, never bytes (PRD §18).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- promise_status_entry — one dated entry in a promise's status timeline.
-- -----------------------------------------------------------------------------
CREATE TABLE promise_status_entry (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID          NOT NULL,
    version      BIGINT        NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE,
    created_by   UUID,
    updated_at   TIMESTAMP WITH TIME ZONE,
    updated_by   UUID,
    deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMP WITH TIME ZONE,
    deleted_by   UUID,

    promise_id   BIGINT        NOT NULL,                  -- same-module FK to promise(id)
    status       VARCHAR(16)   NOT NULL,                  -- PromiseStatus the promise moved TO at this entry
    evidence_ref VARCHAR(512),                            -- object-store key; never bytes
    note         VARCHAR(1000),                           -- optional curator note explaining the transition

    CONSTRAINT uq_promise_status_entry_public_id UNIQUE (public_id),
    CONSTRAINT fk_promise_status_entry_promise
        FOREIGN KEY (promise_id) REFERENCES promise (id),
    -- Enum domain guard (mirror Hibernate's generated CHECK for PromiseStatus — entity↔DDL parity).
    CONSTRAINT ck_promise_status_entry_status
        CHECK (status IN ('MADE','IN_PROGRESS','KEPT','BROKEN'))
);

-- Entity @Index set — the timeline read is "all entries for one promise" (FK lookup).
CREATE INDEX ix_promise_status_entry_promise ON promise_status_entry (promise_id);

COMMENT ON TABLE  promise_status_entry             IS 'Append-only citizen-visible timeline of a promise''s status moves (M6, US-6.3). Curated by ROLE_ADMIN (D-Q4); history never rewritten (neutrality, PRD §10).';
COMMENT ON COLUMN promise_status_entry.promise_id  IS 'Same-module FK to promise(id) — a real, enforced FK (the "reference by id, never an FK" rule is cross-module only; ARCHITECTURE §4.3).';
COMMENT ON COLUMN promise_status_entry.status      IS 'PromiseStatus the promise moved TO at this point in the timeline.';
COMMENT ON COLUMN promise_status_entry.evidence_ref IS 'Object-store key for the evidence backing this transition; never inline content (PRD §18).';
