-- =============================================================================
-- V181__accountability_rating_reply.sql
--   Representative RIGHT-OF-REPLY to a rating (accountability, M6, US-6.2).
--
-- Responsibility: create rating_reply behind com.taarifu.accountability.domain.model.RatingReply —
-- the rated representative's single reply to a citizen rating (the D-rated-fairness rule), shown WITH
-- the rating so the public aggregate is never one-sided. MUST match the entity so ddl-auto=validate
-- passes.
--
-- THE FAIRNESS CAP — invariant the DB enforces here (US-6.2):
--   * ONE REPLY PER RATING: ux_rating_reply_one_per_rating UNIQUE (rating_id) — a representative gets
--     a reply, not a thread (a fair, bounded counterweight, never a megaphone). A second reply is a
--     hard 409; editing the existing one is the author's follow-up.
--   * NO TOKEN COLUMN: there is deliberately NO token/balance/cost column. A right-of-reply is the
--     fairness counterweight to a fenced binding action — never token-gated (§23 fence).
--
-- The OWNERSHIP / conflict-of-interest fence (a rep replies only to a rating about THEMSELVES, never a
-- rival) is enforced in the application layer (RatingReplyService via RepresentativeOwnershipPort,
-- deny-by-default until the real institutions-backed adapter is wired); the curated on-behalf path is
-- ROLE_ADMIN-gated. The subject-must-be-REPRESENTATIVE rule is enforced in the service too.
--
-- SAME-MODULE FK: rating_id is a real, enforced FK to rating(id) — rating lives in THIS module, so a
-- foreign key is correct (the "reference by id, never an FK" rule is cross-module only, ARCHITECTURE
-- §4.3). representative_id (institutions) and author_account_id (identity) are PUBLIC UUIDs referenced
-- by id only, NOT foreign keys (module isolation).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- rating_reply — the representative's single reply to a rating.
-- -----------------------------------------------------------------------------
CREATE TABLE rating_reply (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID          NOT NULL,
    version           BIGINT        NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    rating_id         BIGINT        NOT NULL,             -- same-module FK to rating(id)
    representative_id UUID          NOT NULL,             -- public id (institutions); NOT an FK by design
    author_account_id UUID          NOT NULL,             -- public id (identity); from the security context, never the body
    on_behalf         BOOLEAN       NOT NULL,             -- true = curator posted on the representative's behalf (D-Q4)
    body              VARCHAR(2000) NOT NULL,             -- the reply text (moderated downstream)

    CONSTRAINT uq_rating_reply_public_id UNIQUE (public_id),
    -- ONE reply per rating — the fairness cap (a reply, not a thread; US-6.2). Matches the entity
    -- @OneToOne unique JoinColumn + @UniqueConstraint(rating_id).
    CONSTRAINT ux_rating_reply_one_per_rating UNIQUE (rating_id),
    CONSTRAINT fk_rating_reply_rating FOREIGN KEY (rating_id) REFERENCES rating (id)
);

-- Entity @Index set (author lookup for audit/admin).
CREATE INDEX ix_rating_reply_author ON rating_reply (author_account_id);

COMMENT ON TABLE  rating_reply                   IS 'Representative right-of-reply to a rating (M6, US-6.2; D-rated-fairness). One reply per rating; shown with the rating. Ownership/CoI fence + subject-is-REPRESENTATIVE enforced in app; NO token column (§23).';
COMMENT ON COLUMN rating_reply.rating_id          IS 'Same-module FK to rating(id) — a real, enforced FK (the "reference by id, never an FK" rule is cross-module only; ARCHITECTURE §4.3).';
COMMENT ON COLUMN rating_reply.representative_id   IS 'PUBLIC UUID of the rated representative (institutions module); referenced by id, never an FK (module isolation). Equals the answered rating''s subject_id.';
COMMENT ON COLUMN rating_reply.author_account_id   IS 'PUBLIC UUID of the replying account (identity module); taken from the security context, never the request body. The representative''s linked account (self) or an ADMIN/ROOT curator (on-behalf).';
COMMENT ON COLUMN rating_reply.on_behalf           IS 'TRUE when a curator posted the reply on the representative''s behalf (D-Q4 curated authorship); shown attributably.';
