-- =============================================================================
-- V20__institutions_parties_parliaments.sql
--   Institutions module (M2) — reference directories: political parties, parliament
--   terms, and the parliament-role catalogue (PRD §9.1, §22.6).
--
-- Responsibility: create the three reference tables that a Representative (V21) links
-- to. They MUST match the JPA entities exactly so Hibernate ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1; entities PoliticalParty/Parliament/ParliamentRole).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * One party row referenced by FK from representative — NOT a free-text party name
--     duplicated per representative (the legacy drift). Single source of truth (DRY).
--   * status (PartyStatus) models civic deregistration distinctly from the soft-delete
--     tombstone so a dissolved party still anchors a FORMER rep's historical affiliation.
--   * parliament.is_current is an administrative flag; "at most one current term per
--     legislature" is a DB-owned invariant (partial unique index) JPA cannot express.
--   * legislature separates the Union Parliament from the Zanzibar House of
--     Representatives (D17) so the current-term invariant never collides across them.
--
-- Type mapping contract (entity -> column), so validate is exact (matches V2 geography):
--   Long id            -> bigint identity PK
--   UUID public_id     -> uuid not null unique
--   Long version       -> bigint not null
--   Instant created_at -> timestamp with time zone (Hibernate 6 maps Instant to TIMESTAMP_UTC)
--   UUID *_by          -> uuid
--   boolean deleted    -> boolean not null
--   LocalDate dates    -> date
--   @Enumerated(STRING)-> varchar(<declared length>)
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- political_party — registered party (Chama cha Siasa) reference directory.
-- -----------------------------------------------------------------------------
CREATE TABLE political_party (
    -- BaseEntity (ARCHITECTURE.md §4.2).
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    version       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE,
    created_by    UUID,
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    UUID,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    UUID,

    -- Domain columns (PoliticalParty.java).
    code          VARCHAR(32)  NOT NULL,                 -- official code; idempotent seed/import match key
    name          VARCHAR(200) NOT NULL,
    abbreviation  VARCHAR(32),
    ideology      VARCHAR(160),
    founded_year  INTEGER,
    logo_ref      VARCHAR(512),                          -- object-store reference, NOT bytes (ARCHITECTURE.md §7)
    status        VARCHAR(16)  NOT NULL,                 -- PartyStatus: ACTIVE/INACTIVE
    contacts      VARCHAR(512),

    CONSTRAINT uq_political_party_public_id UNIQUE (public_id),
    CONSTRAINT uq_political_party_code      UNIQUE (code),
    -- Enum domain guard mirrors Hibernate's generated CHECK for @Enumerated(STRING) (defense in depth).
    CONSTRAINT ck_political_party_status    CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX ix_political_party_status ON political_party (status);
-- uq_political_party_code already provides the unique index the entity declares as ix_political_party_code(unique).

COMMENT ON TABLE  political_party            IS 'Registered political party (Chama) reference directory; referenced by FK from representative (PRD §9.1).';
COMMENT ON COLUMN political_party.code       IS 'Official party code; unique; idempotent seed/import match key.';
COMMENT ON COLUMN political_party.status     IS 'PartyStatus ACTIVE/INACTIVE: civic deregistration, distinct from the soft-delete tombstone (retains historical affiliation).';
COMMENT ON COLUMN political_party.logo_ref   IS 'Object-store key/URL for the logo asset; binary lives in object storage behind a port, never in the row.';


-- -----------------------------------------------------------------------------
-- parliament — a parliamentary term/session of a legislature (Bunge term).
-- -----------------------------------------------------------------------------
CREATE TABLE parliament (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    version       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE,
    created_by    UUID,
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    UUID,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    UUID,

    -- Domain columns (Parliament.java).
    term_number   INTEGER      NOT NULL,                 -- e.g. 12 for the 12th Parliament
    name          VARCHAR(160) NOT NULL,
    legislature   VARCHAR(24)  NOT NULL,                 -- Legislature: UNION_PARLIAMENT/ZANZIBAR_HOR
    start_date    DATE         NOT NULL,                 -- inclusive
    end_date      DATE,                                  -- exclusive; NULL = ongoing
    is_current    BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_parliament_public_id UNIQUE (public_id),
    CONSTRAINT ck_parliament_legislature CHECK (legislature IN ('UNION_PARLIAMENT','ZANZIBAR_HOR')),
    -- Range sanity: end (if set) must be strictly after start.
    CONSTRAINT ck_parliament_range CHECK (end_date IS NULL OR end_date > start_date)
);

CREATE INDEX ix_parliament_legislature ON parliament (legislature);
CREATE INDEX ix_parliament_current     ON parliament (is_current);

-- INVARIANT (DB-owned): at most ONE current term per legislature. JPA cannot express this; the DB is
-- the only place it can be guaranteed. Scoped to live rows so a soft-deleted historical term never
-- blocks flagging a new current one.
CREATE UNIQUE INDEX ux_parliament_current_per_legislature
    ON parliament (legislature)
    WHERE is_current = TRUE AND deleted = FALSE;

COMMENT ON TABLE  parliament             IS 'A parliamentary term/session of a legislature; representatives FK their seat to a term (PRD §9.1).';
COMMENT ON COLUMN parliament.is_current  IS 'Administrative "currently-sitting term" flag; ux_parliament_current_per_legislature guarantees one current term per legislature.';
COMMENT ON COLUMN parliament.legislature IS 'Legislature UNION_PARLIAMENT/ZANZIBAR_HOR (D17); separates Union Bunge from Zanzibar HoR.';


-- -----------------------------------------------------------------------------
-- parliament_role — catalogue of assignable offices (Speaker, Minister, ...).
-- -----------------------------------------------------------------------------
CREATE TABLE parliament_role (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    version       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE,
    created_by    UUID,
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    UUID,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    UUID,

    -- Domain columns (ParliamentRole.java).
    code          VARCHAR(48)  NOT NULL,                 -- stable role code; idempotent seed/import key
    name          VARCHAR(160) NOT NULL,
    description   VARCHAR(512),

    CONSTRAINT uq_parliament_role_public_id UNIQUE (public_id),
    CONSTRAINT uq_parliament_role_code      UNIQUE (code)
);
-- uq_parliament_role_code already provides the unique index the entity declares as ix_parliament_role_code(unique).

COMMENT ON TABLE  parliament_role      IS 'Catalogue of assignable parliamentary offices (Speaker/Minister/Committee chair); a representative optionally FKs one (PRD §9.1).';
COMMENT ON COLUMN parliament_role.code IS 'Stable role code; unique; idempotent seed/import match key.';
