-- =============================================================================
-- V21__institutions_representative.sql
--   Institutions module (M2) — the representative (Mbunge/Diwani/ward-exec) table:
--   the heart of "find my representatives" and the representative directory
--   (PRD §9.1, §22.6; entity Representative.java).
--
-- Responsibility: create the `representative` table with REAL foreign keys to the
-- geography seat (constituency / ward) and to this module's party/parliament/role
-- tables, plus the cross-field integrity constraints. MUST match the JPA entity so
-- ddl-auto=validate passes (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * profile_id is a bare UUID (the identity Profile's PUBLIC id), NOT a FK into the
--     identity schema — institutions must not reach into identity's tables
--     (module boundary, ARCHITECTURE.md §3.2). The actual account/role association is
--     owned by identity/admin and wired at integration time.
--   * constituency_id / ward_id are real FKs to geography.constituency / geography.location
--     (fixes the legacy loose-Long `Mp.constituencyId`). They are NULLABLE because
--     special-seats (Viti Maalum) and nominated MPs have NO geographic seat (PRD §22.6).
--   * mandate ⇄ geography coherence is enforced by ck_representative_mandate_geo so an
--     impossible combination (e.g. a CONSTITUENCY mandate with no constituency, or a
--     special-seats MP carrying a ward) can never be stored — defense in depth behind the
--     service-level validation (PRD §9.1).
--   * The load-bearing electoral invariant — ONE SITTING constituency-MP per constituency
--     — is a DB partial-unique index (ux_representative_sitting_constituency); JPA cannot
--     express it. PENDING_VERIFICATION/FORMER rows do not consume the slot, so a successor
--     can be staged before the incumbent is retired (UC-C08). FORMER reps are retained.
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================

CREATE TABLE representative (
    -- BaseEntity (ARCHITECTURE.md §4.2).
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID        NOT NULL,
    version             BIGINT      NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    -- Domain columns (Representative.java).
    profile_id          UUID,                            -- identity Profile PUBLIC id (cross-module by id only)
    type                VARCHAR(16) NOT NULL,            -- RepresentativeType: MP/COUNCILLOR/WARD_EXEC
    mandate             VARCHAR(24) NOT NULL,            -- Mandate: CONSTITUENCY/SPECIAL_SEATS/NOMINATED/COUNCILLOR_WARD
    constituency_id     BIGINT,                          -- FK geography.constituency.id (NULL unless CONSTITUENCY mandate)
    ward_id             BIGINT,                          -- FK geography.location.id WARD (NULL unless COUNCILLOR_WARD mandate)
    party_id            BIGINT,                          -- FK political_party.id (NULL for independents)
    legislature         VARCHAR(24) NOT NULL,            -- Legislature: UNION_PARLIAMENT/ZANZIBAR_HOR
    parliament_id       BIGINT,                          -- FK parliament.id (NULL for councillors/ward-execs)
    parliament_role_id  BIGINT,                          -- FK parliament_role.id (NULL unless an office is held)
    status              VARCHAR(24) NOT NULL,            -- RepresentativeStatus: PENDING_VERIFICATION/SITTING/FORMER
    elected_at          DATE,                            -- election/seating date
    bio                 VARCHAR(4000),                   -- moderated public biography

    CONSTRAINT uq_representative_public_id UNIQUE (public_id),

    -- Real foreign keys (ON DELETE not cascaded — civic rows are soft-deleted, never physically removed).
    CONSTRAINT fk_representative_constituency    FOREIGN KEY (constituency_id)    REFERENCES constituency (id),
    CONSTRAINT fk_representative_ward             FOREIGN KEY (ward_id)            REFERENCES location (id),
    CONSTRAINT fk_representative_party            FOREIGN KEY (party_id)           REFERENCES political_party (id),
    CONSTRAINT fk_representative_parliament       FOREIGN KEY (parliament_id)      REFERENCES parliament (id),
    CONSTRAINT fk_representative_parliament_role  FOREIGN KEY (parliament_role_id) REFERENCES parliament_role (id),

    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns.
    CONSTRAINT ck_representative_type        CHECK (type IN ('MP','COUNCILLOR','WARD_EXEC')),
    CONSTRAINT ck_representative_mandate     CHECK (mandate IN ('CONSTITUENCY','SPECIAL_SEATS','NOMINATED','COUNCILLOR_WARD')),
    CONSTRAINT ck_representative_legislature CHECK (legislature IN ('UNION_PARLIAMENT','ZANZIBAR_HOR')),
    CONSTRAINT ck_representative_status      CHECK (status IN ('PENDING_VERIFICATION','SITTING','FORMER')),

    -- INVARIANT (DB-owned): mandate ⇄ geography coherence. A CONSTITUENCY mandate must carry a
    -- constituency and no ward; a COUNCILLOR_WARD must carry a ward and no constituency; SPECIAL_SEATS
    -- and NOMINATED must carry NEITHER. This makes "no constituency" an intentional, valid state for a
    -- Viti Maalum / nominated MP — never a data error (PRD §22.6).
    CONSTRAINT ck_representative_mandate_geo CHECK (
        (mandate = 'CONSTITUENCY'     AND constituency_id IS NOT NULL AND ward_id IS NULL)
     OR (mandate = 'COUNCILLOR_WARD'  AND ward_id IS NOT NULL         AND constituency_id IS NULL)
     OR (mandate IN ('SPECIAL_SEATS','NOMINATED') AND constituency_id IS NULL AND ward_id IS NULL)
    )
);

-- Entity-declared lookup indexes (names kept identical to the @Index set to avoid drift).
CREATE INDEX ix_representative_profile      ON representative (profile_id);
CREATE INDEX ix_representative_constituency ON representative (constituency_id);
CREATE INDEX ix_representative_ward         ON representative (ward_id);
CREATE INDEX ix_representative_party        ON representative (party_id);
CREATE INDEX ix_representative_parliament   ON representative (parliament_id);
CREATE INDEX ix_representative_type         ON representative (type);
CREATE INDEX ix_representative_status       ON representative (status);

-- INVARIANT (DB-owned): ONE SITTING constituency-MP per constituency. Partial unique index — JPA cannot
-- express "unique constituency WHERE status = SITTING". Scoped to live rows so a soft-deleted row never
-- blocks a successor. PENDING_VERIFICATION/FORMER rows are outside the predicate, so staging a successor
-- before retiring the incumbent does not trip it (UC-C08).
CREATE UNIQUE INDEX ux_representative_sitting_constituency
    ON representative (constituency_id)
    WHERE status = 'SITTING' AND constituency_id IS NOT NULL AND deleted = FALSE;

COMMENT ON TABLE  representative                 IS 'Elected/appointed representative (MP/Councillor/ward-exec); heart of find-my-rep + directory (PRD §9.1, §22.6).';
COMMENT ON COLUMN representative.profile_id      IS 'Identity Profile PUBLIC id (1:1, same account §6.4); a cross-module reference by id only, never a FK into identity.';
COMMENT ON COLUMN representative.mandate         IS 'Mandate basis; ck_representative_mandate_geo ties it to which geographic FK is populated (Viti Maalum/nominated carry neither).';
COMMENT ON COLUMN representative.constituency_id IS 'FK geography.constituency.id; populated only for a CONSTITUENCY-mandate MP.';
COMMENT ON COLUMN representative.ward_id         IS 'FK geography.location.id (WARD); populated only for a COUNCILLOR_WARD-mandate councillor/exec.';
COMMENT ON COLUMN representative.status          IS 'Lifecycle PENDING_VERIFICATION/SITTING/FORMER; ux_representative_sitting_constituency enforces one SITTING MP per constituency; FORMER retained.';
