-- =============================================================================
-- V23__reporting_issue_category.sql  —  Hierarchical issue taxonomy (reporting).
--
-- Responsibility: create the issue_category table behind the IssueCategory entity
-- and the report_code_seq sequence that the application's CodeGenerator draws on to
-- mint TAR-YYYY-NNNNNN ticket codes (race-safe, gap-tolerant — never max(id)+1).
-- MUST match the entities so ddl-auto=validate passes (ARCHITECTURE.md §4; PRD §9.1,
-- Appendix D; M3).
--
-- The taxonomy is hierarchical (self-FK parent_id) and carries the DEFAULTS that drive
-- routing/SLA/privacy/anonymity for reports filed under it (Appendix D.2/D.4):
--   * default_routing_level  — routing TOKEN (not an agency), Appendix D.1
--   * default_sla_ttfr/ttr   — SLA in MINUTES (integer; computable into Report.dueAt)
--   * sensitive              — anonymity-eligible (T1 sufficient), D-Q1
--   * force_private          — GBV/Corruption forced PRIVATE regardless of choice, D.4
--   * default_visibility     — applied when not forced/chosen
--
-- Type mapping contract (entity -> column) — same rules as V2/V3:
--   Long->bigint identity, UUID->uuid, Long version->bigint not null,
--   Instant->timestamp with time zone, boolean->boolean not null,
--   @Enumerated(STRING)->varchar(<declared length>), int->integer.
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- report_code_seq — drives the human ticket code TAR-YYYY-NNNNNN (BaseCodedEntity).
-- WHY a sequence (not max(id)+1): gap-tolerant + race-safe under concurrency; a
-- rolled-back report still burns its number, which is correct (numbers are
-- non-reused identifiers, never a count) — ADR-0006, CodeGenerator.
-- -----------------------------------------------------------------------------
CREATE SEQUENCE report_code_seq START WITH 1 INCREMENT BY 1;

COMMENT ON SEQUENCE report_code_seq IS 'Source of the numeric tail of Report.code (TAR-YYYY-NNNNNN); drawn by common.CodeGenerator in its own REQUIRES_NEW tx (ADR-0006).';


-- -----------------------------------------------------------------------------
-- issue_category — hierarchical reportable-issue taxonomy (Appendix D).
-- -----------------------------------------------------------------------------
CREATE TABLE issue_category (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL,
    version                  BIGINT       NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE,
    created_by               UUID,
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               UUID,
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    deleted_by               UUID,

    -- Domain columns (IssueCategory.java).
    code                     VARCHAR(64)  NOT NULL,                 -- stable machine code; import/match key
    name                     VARCHAR(160) NOT NULL,                 -- Swahili-first display name
    parent_id                BIGINT,                                -- self-FK; NULL for a top-level category
    default_routing_level    VARCHAR(24)  NOT NULL,                 -- RoutingLevel token (Appendix D.1)
    default_sla_ttfr_minutes INTEGER      NOT NULL,                 -- TTFR in minutes
    default_sla_ttr_minutes  INTEGER      NOT NULL,                 -- TTR in minutes (drives Report.dueAt)
    sensitive                BOOLEAN      NOT NULL DEFAULT FALSE,    -- anonymity-eligible (D-Q1)
    force_private            BOOLEAN      NOT NULL DEFAULT FALSE,    -- forced PRIVATE (GBV/Corruption, D.4)
    default_visibility       VARCHAR(16)  NOT NULL,                 -- ReportVisibility: PUBLIC/PRIVATE
    icon                     VARCHAR(64),                           -- optional UI icon token
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,     -- shown in the picker

    CONSTRAINT uq_issue_category_public_id UNIQUE (public_id),
    CONSTRAINT uq_issue_category_code      UNIQUE (code),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns.
    CONSTRAINT ck_issue_category_routing CHECK (default_routing_level IN
        ('WARD','MTAA_VILLAGE','COUNCIL','DISTRICT','REGION','SECTOR_UTILITY','OVERSIGHT')),
    CONSTRAINT ck_issue_category_visibility CHECK (default_visibility IN ('PUBLIC','PRIVATE')),
    -- Non-negative SLA windows (defense in depth alongside Bean Validation @Min(1)).
    CONSTRAINT ck_issue_category_ttfr CHECK (default_sla_ttfr_minutes >= 0),
    CONSTRAINT ck_issue_category_ttr  CHECK (default_sla_ttr_minutes  >= 0),
    -- Self-referential parent; never cascaded — categories are soft-deleted, never physically removed.
    CONSTRAINT fk_issue_category_parent FOREIGN KEY (parent_id) REFERENCES issue_category (id)
);

-- Indexes mirror the entity @Index set (names kept identical to avoid drift).
-- uq_issue_category_code already provides the unique index the entity declares as ix_issue_category_code(unique).
CREATE INDEX ix_issue_category_parent ON issue_category (parent_id);
CREATE INDEX ix_issue_category_active ON issue_category (active);

COMMENT ON TABLE  issue_category                          IS 'Hierarchical citizen-reportable issue taxonomy with routing/SLA/privacy defaults (PRD §9.1, Appendix D).';
COMMENT ON COLUMN issue_category.public_id                IS 'Public, non-enumerable UUID exposed in URLs/DTOs (PRD §17); internal id never leaves the backend.';
COMMENT ON COLUMN issue_category.code                     IS 'Stable machine code (e.g. WATER_SANITATION); unique; immutable; import/match key.';
COMMENT ON COLUMN issue_category.parent_id                IS 'Immediate parent category (self-FK); NULL for a top-level node.';
COMMENT ON COLUMN issue_category.default_routing_level    IS 'RoutingLevel TOKEN reports route to by default (Appendix D.1); an abstraction, not a hardcoded agency.';
COMMENT ON COLUMN issue_category.default_sla_ttfr_minutes IS 'Default time-to-first-response in minutes (TTFR); shown as expected first response at file time.';
COMMENT ON COLUMN issue_category.default_sla_ttr_minutes  IS 'Default time-to-resolution in minutes (TTR); Report.dueAt = filedAt + this (UC-D04).';
COMMENT ON COLUMN issue_category.sensitive                IS 'Anonymity-eligible (T1 sufficient, no reporter linkage) per D-Q1 (GBV/Corruption always; some sub-cases).';
COMMENT ON COLUMN issue_category.force_private            IS 'Forces visibility PRIVATE regardless of citizen choice (GBV/Corruption — Appendix D.4 "never PUBLIC").';
COMMENT ON COLUMN issue_category.default_visibility       IS 'ReportVisibility applied when not forced/chosen: PUBLIC/PRIVATE.';
COMMENT ON COLUMN issue_category.active                  IS 'Civic on/off: a retired category is hidden from the picker but kept for historical reports.';
