-- =============================================================================
-- V24__reporting_report.sql  —  Citizen issue report / case aggregate (reporting).
--
-- Responsibility: create the report table behind the Report entity (BaseCodedEntity:
-- it carries the human ticket code TAR-YYYY-NNNNNN in addition to the BaseEntity
-- shape). MUST match the entity so ddl-auto=validate passes (ARCHITECTURE.md §4;
-- PRD §10 M3, §12.1, §25.3, Appendix D).
--
-- Integrity/privacy invariants reflected here (PRD §19/§25.3/§23.5, CLAUDE.md §12):
--   * ANONYMOUS SENSITIVE FILING (D-Q1): reporter_profile_id is NULLABLE — a sensitive
--     report stores NO reporter linkage at all (strongest protection; tracked by code).
--   * CROSS-MODULE REFERENCE BY ID, not FK: reporter_profile_id, reporter_ward_id,
--     constituency_id, assigned_responder_id, duplicate_of_id are UUID publicIds of
--     OTHER modules' entities — intentionally NOT FKs, to keep the module boundary
--     clean and make anonymity a simple NULL (ARCHITECTURE.md §4.3).
--   * ROUTING DEFERRED: assigned_responder_id is a STUB — reports are created NEW and
--     never auto-assigned in this increment (see // TODO(wiring)).
--   * INTEGRITY FENCE (D18/§23.5): upvotes/followers are discovery-reach counters ONLY;
--     they must never influence routing/SLA/priority/resolution. They live here as
--     denormalised counts; nothing reads them for official routing.
--
-- Type mapping contract (entity -> column): as V2/V3/V23, plus
--   Point -> geometry(Point,4326); Boolean (nullable) -> boolean (nullable);
--   long -> bigint not null.
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- report — the central case aggregate (PRD §10 M3, §12.1).
-- -----------------------------------------------------------------------------
CREATE TABLE report (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID         NOT NULL,
    version              BIGINT       NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE,
    created_by           UUID,
    updated_at           TIMESTAMP WITH TIME ZONE,
    updated_by           UUID,
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMP WITH TIME ZONE,
    deleted_by           UUID,

    -- BaseCodedEntity (ADR-0006): human ticket code TAR-YYYY-NNNNNN; immutable; unique.
    code                 VARCHAR(255),                              -- mapped by BaseCodedEntity (no length declared)

    -- Domain columns (Report.java).
    reporter_profile_id  UUID,                                      -- identity.Profile publicId; NULL = anonymous (D-Q1)
    category_id          BIGINT       NOT NULL,                     -- FK issue_category.id (required)
    title                VARCHAR(200) NOT NULL,
    description          VARCHAR(4000) NOT NULL,
    geo_point            geometry(Point, 4326),                     -- optional incident point (WGS84)
    reporter_ward_id     UUID         NOT NULL,                     -- geography ward publicId (min pin granularity)
    constituency_id      UUID,                                      -- constituency publicId in effect (snapshot), or NULL
    attachment_refs      VARCHAR(2000),                             -- delimited object-store refs (virus-scanned)
    visibility           VARCHAR(16)  NOT NULL,                     -- ReportVisibility: PUBLIC/PRIVATE
    status               VARCHAR(16)  NOT NULL,                     -- ReportStatus (§12.1)
    priority             VARCHAR(16)  NOT NULL,                     -- ReportPriority
    assigned_responder_id UUID,                                     -- STUB; routing DEFERRED (// TODO(wiring))
    due_at               TIMESTAMP WITH TIME ZONE,                  -- SLA due = filedAt + category TTR
    resolution           VARCHAR(4000),                             -- resolution note (required when RESOLVED)
    confirmation         BOOLEAN,                                   -- NULL pending / true confirm / false dispute
    duplicate_of_id      UUID,                                      -- canonical report publicId if DUPLICATE
    upvotes              BIGINT       NOT NULL DEFAULT 0,           -- discovery-reach counter (integrity-fenced)
    followers            BIGINT       NOT NULL DEFAULT 0,           -- discovery-reach counter (integrity-fenced)

    CONSTRAINT uq_report_public_id UNIQUE (public_id),
    CONSTRAINT uq_report_code      UNIQUE (code),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns.
    CONSTRAINT ck_report_visibility CHECK (visibility IN ('PUBLIC','PRIVATE')),
    CONSTRAINT ck_report_status     CHECK (status IN
        ('NEW','ASSIGNED','IN_PROGRESS','AWAITING_INFO','RESOLVED','CLOSED','REOPENED','REJECTED','DUPLICATE','ESCALATED')),
    CONSTRAINT ck_report_priority   CHECK (priority IN ('NORMAL','HIGH','EMERGENCY')),
    -- Real FK to the (same-module) category; never cascaded — rows are soft-deleted.
    CONSTRAINT fk_report_category   FOREIGN KEY (category_id) REFERENCES issue_category (id)
);

-- Indexes mirror the entity @Index set (names kept identical to avoid drift).
-- uq_report_code already provides the unique index the entity declares as ix_report_code(unique).
CREATE INDEX ix_report_reporter ON report (reporter_profile_id);
CREATE INDEX ix_report_category ON report (category_id);
CREATE INDEX ix_report_status   ON report (status);
CREATE INDEX ix_report_ward     ON report (reporter_ward_id);
-- Composite index for the public near-me list/map: PUBLIC rows by ward, newest first.
CREATE INDEX ix_report_public_ward ON report (visibility, reporter_ward_id, created_at);
-- GiST spatial index on the incident point (sparse — only GPS-located reports carry it).
CREATE INDEX ix_report_geo_point_gist ON report USING gist (geo_point) WHERE geo_point IS NOT NULL;

COMMENT ON TABLE  report                      IS 'Citizen-filed issue report / case aggregate; human ticket TAR-YYYY-NNNNNN (PRD §10 M3, §12.1).';
COMMENT ON COLUMN report.code                 IS 'Human ticket code TAR-YYYY-NNNNNN (BaseCodedEntity); unique; also the anonymous tracking handle (D-Q1).';
COMMENT ON COLUMN report.reporter_profile_id  IS 'identity.Profile publicId of the reporter; NULL for an anonymous sensitive filing (D-Q1, §25.3). NOT a FK (cross-module + anonymity).';
COMMENT ON COLUMN report.category_id          IS 'FK issue_category.id; required; drives default routing/SLA/privacy.';
COMMENT ON COLUMN report.geo_point            IS 'Optional incident point (PostGIS, SRID 4326); coarsened/redacted in shared views for sensitive reports (Appendix D.4).';
COMMENT ON COLUMN report.reporter_ward_id     IS 'geography.Location (type WARD) publicId — minimum pin granularity (PRD §9.0). Reference-by-id, not a FK.';
COMMENT ON COLUMN report.constituency_id      IS 'Constituency (Jimbo) publicId in effect for the ward at file time (snapshot for stable electoral attribution, §25.4).';
COMMENT ON COLUMN report.visibility           IS 'ReportVisibility PUBLIC/PRIVATE; FORCED PRIVATE for GBV/Corruption regardless of citizen choice (D-Q1, D.4).';
COMMENT ON COLUMN report.status               IS 'ReportStatus lifecycle (§12.1); transitions are guarded server-side and recorded as case_event STATUS_CHANGE rows.';
COMMENT ON COLUMN report.assigned_responder_id IS 'STUB — responder OWNER publicId once routing is wired (D21); routing DEFERRED, reports stay NEW for now.';
COMMENT ON COLUMN report.due_at               IS 'SLA due instant = filedAt + category default TTR (UC-D04); drives breach detection (DEFERRED engine).';
COMMENT ON COLUMN report.confirmation         IS 'Citizen confirm/dispute on RESOLVED: NULL pending, TRUE confirmed (->CLOSED), FALSE disputed (->REOPENED) (US-3.5).';
COMMENT ON COLUMN report.duplicate_of_id      IS 'Canonical report publicId when this report is merged as DUPLICATE (US-3.8).';
COMMENT ON COLUMN report.upvotes              IS 'Discovery-reach upvote counter (US-3.7); INTEGRITY-FENCED — never affects routing/SLA/priority (D18, §23.5).';
COMMENT ON COLUMN report.followers            IS 'Discovery-reach follower counter (US-3.7); INTEGRITY-FENCED — never affects routing/SLA/priority (D18, §23.5).';
