-- =============================================================================
-- V25__reporting_case_event.sql  —  Append-only case timeline (reporting).
--
-- Responsibility: create the case_event table behind the CaseEvent entity — one row
-- per thing that happened to a report (status change, assignment, comment, attachment,
-- escalation). MUST match the entity so ddl-auto=validate passes (ARCHITECTURE.md §4;
-- PRD §10 US-3.2/US-3.4, §12.1).
--
-- Privacy invariant (PRD §25.3, US-3.4): public_event gates citizen/public visibility —
-- internal responder notes (public_event = FALSE) are NEVER surfaced to the reporter/
-- public. Read services filter on this flag; the column is the single source of the gate.
--
-- This is the module's DOMAIN timeline (it may quote a citizen's comment text shown back
-- to them) — distinct from the PII-free, hash-chained security audit_event store (V5),
-- which catalogues authn/authz/identity decisions only.
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- case_event — one append-only entry on a report's timeline.
-- -----------------------------------------------------------------------------
CREATE TABLE case_event (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    -- Domain columns (CaseEvent.java).
    report_id         BIGINT       NOT NULL,                     -- FK report.id (required)
    event_type        VARCHAR(24)  NOT NULL,                     -- CaseEventType
    public_event      BOOLEAN      NOT NULL,                     -- visibility gate (US-3.4)
    actor_profile_id  UUID,                                      -- acting identity.Profile publicId; NULL system/anon
    message           VARCHAR(4000),                             -- comment / change description

    CONSTRAINT uq_case_event_public_id UNIQUE (public_id),
    -- Enum domain guard mirrors Hibernate's generated CHECK for @Enumerated(STRING).
    CONSTRAINT ck_case_event_type CHECK (event_type IN
        ('STATUS_CHANGE','ASSIGNMENT','COMMENT','ATTACHMENT','ESCALATION')),
    -- Real FK to the report; never cascaded — rows are soft-deleted, history is preserved.
    CONSTRAINT fk_case_event_report FOREIGN KEY (report_id) REFERENCES report (id)
);

-- Indexes mirror the entity @Index set (names kept identical to avoid drift).
CREATE INDEX ix_case_event_report ON case_event (report_id);
CREATE INDEX ix_case_event_type   ON case_event (event_type);
-- Composite index for the citizen-facing public timeline read: this report's public events, chronological.
CREATE INDEX ix_case_event_report_public ON case_event (report_id, public_event, created_at);

COMMENT ON TABLE  case_event                  IS 'Append-only case timeline (status/comment/assignment/attachment/escalation) for a report (PRD §10 US-3.2/US-3.4, §12.1).';
COMMENT ON COLUMN case_event.public_id        IS 'Public, non-enumerable UUID exposed in URLs/DTOs (PRD §17); internal id never leaves the backend.';
COMMENT ON COLUMN case_event.report_id        IS 'FK report.id — the report this event belongs to (required).';
COMMENT ON COLUMN case_event.event_type       IS 'CaseEventType: STATUS_CHANGE, ASSIGNMENT, COMMENT, ATTACHMENT, ESCALATION.';
COMMENT ON COLUMN case_event.public_event     IS 'Visibility gate (US-3.4): TRUE = reporter/public-visible; FALSE = internal responder-only note (never leaked).';
COMMENT ON COLUMN case_event.actor_profile_id IS 'identity.Profile publicId of the actor; NULL for a system event or an anonymous reporter action on a sensitive case (D-Q1).';
COMMENT ON COLUMN case_event.message          IS 'Event body: comment text, resolution-note copy, or a human description of the change.';
