-- =============================================================================
-- V27__communications_announcement.sql  —  Announcements (communications module, M4).
--
-- Responsibility: create the `announcement` table and its three child collection
-- tables (audience areas, channels, attachments) behind the JPA entity
-- com.taarifu.communications.domain.model.Announcement. These MUST match the
-- entities exactly so Hibernate ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §13).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * Cross-module references (author_profile_id, category_id, audience_area area_id)
--     are bare UUIDs, NOT foreign keys. The author profile (identity), the category
--     (reporting), and the audience areas (geography) are owned by OTHER modules; the
--     modular-monolith boundary forbids FK-joining their tables (ARCHITECTURE §3.2).
--     The owning module validates the id at write time.
--   * Bilingual body (body_sw required, body_en optional): Swahili is the default
--     locale (ADR-0010); a recipient is served their locale, Swahili otherwise.
--   * moderation_held is a SEPARATE axis from status: a new/untrusted author's
--     announcement is DRAFT + moderation_held=true and cannot publish until cleared
--     (US-4.1). The publish lifecycle (DRAFT→SCHEDULED→PUBLISHED→EXPIRED) is the status
--     enum; the hold is a boolean — never conflate them.
--   * @ElementCollection child tables (audience_area, channel, attachment) carry NO
--     BaseEntity columns (they are value collections, not aggregates) — they have only
--     the owning FK + the element column, matching Hibernate's generated DDL.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id            -> bigint identity PK
--   UUID public_id     -> uuid not null unique
--   Long version       -> bigint not null
--   Instant created_at/publish_at/expire_at -> timestamp with time zone
--   UUID *_id / *_by   -> uuid
--   boolean            -> boolean not null
--   @Enumerated(STRING)-> varchar(<declared length>)
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- announcement — an authored, geo-targeted civic announcement.
-- -----------------------------------------------------------------------------
CREATE TABLE announcement (
    -- BaseEntity (ARCHITECTURE §4.2).
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL,
    version            BIGINT       NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE,
    created_by         UUID,
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         UUID,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMP WITH TIME ZONE,
    deleted_by         UUID,

    -- Domain columns (Announcement.java).
    author_profile_id  UUID         NOT NULL,                 -- bare ref to identity Profile/User; never a FK
    title              VARCHAR(200) NOT NULL,
    body_sw            VARCHAR(4000) NOT NULL,                -- Swahili body (default locale, ADR-0010)
    body_en            VARCHAR(4000),                         -- optional English body
    category_id        UUID,                                  -- bare ref to reporting IssueCategory; never a FK
    audience_role      VARCHAR(32),                           -- optional role-name narrowing
    status             VARCHAR(16)  NOT NULL,                 -- AnnouncementStatus
    moderation_held    BOOLEAN      NOT NULL DEFAULT FALSE,   -- new-author hold gate (US-4.1)
    publish_at         TIMESTAMP WITH TIME ZONE,              -- NULL = publish immediately
    expire_at          TIMESTAMP WITH TIME ZONE,              -- NULL = never expire

    CONSTRAINT uq_announcement_public_id UNIQUE (public_id),
    -- Enum domain guard mirrors Hibernate's generated CHECK for the @Enumerated(STRING) column.
    CONSTRAINT ck_announcement_status CHECK (status IN ('DRAFT','SCHEDULED','PUBLISHED','EXPIRED'))
);

-- Indexes mirror the entity @Index set (names identical to avoid drift).
CREATE INDEX ix_announcement_author         ON announcement (author_profile_id);
CREATE INDEX ix_announcement_status         ON announcement (status);
-- The hot feed query: live, non-expired announcements ordered by publish time.
CREATE INDEX ix_announcement_status_publish ON announcement (status, publish_at);

COMMENT ON TABLE  announcement                  IS 'Authored, geo-targeted civic announcement; fans out to followers'' feeds + notifications (PRD §13, M4).';
COMMENT ON COLUMN announcement.author_profile_id IS 'Authoring profile publicId (identity); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN announcement.body_sw          IS 'Swahili body — the default locale (ADR-0010); always present.';
COMMENT ON COLUMN announcement.category_id      IS 'Tagged IssueCategory publicId (reporting); bare UUID ref, never a FK.';
COMMENT ON COLUMN announcement.status           IS 'AnnouncementStatus lifecycle: DRAFT,SCHEDULED,PUBLISHED,EXPIRED (PRD §12).';
COMMENT ON COLUMN announcement.moderation_held  IS 'New/untrusted-author hold; blocks ->PUBLISHED until a moderator clears it (US-4.1). Separate axis from status.';
COMMENT ON COLUMN announcement.publish_at       IS 'When to go live (UTC); NULL = immediately. Drives SCHEDULED vs PUBLISHED on publish.';
COMMENT ON COLUMN announcement.expire_at        IS 'When to stop showing (UTC); NULL = never.';


-- -----------------------------------------------------------------------------
-- announcement_audience_area — the targeted geo area refs (value collection).
-- Bare area UUIDs (geography Location ids); no BaseEntity columns, no FK to geography.
-- -----------------------------------------------------------------------------
CREATE TABLE announcement_audience_area (
    announcement_id BIGINT NOT NULL,                          -- FK announcement.id (owning aggregate)
    area_id         UUID   NOT NULL,                          -- bare geography area publicId; never a FK

    CONSTRAINT fk_announcement_audience_area_owner
        FOREIGN KEY (announcement_id) REFERENCES announcement (id) ON DELETE CASCADE
);
CREATE INDEX ix_announcement_audience_area_owner ON announcement_audience_area (announcement_id);
-- Index on area_id supports the feed query's "announcements targeting my followed areas" match.
CREATE INDEX ix_announcement_audience_area_area  ON announcement_audience_area (area_id);

COMMENT ON TABLE announcement_audience_area IS 'Audience-scope geo areas for an announcement (value collection); area_id is a bare geography publicId, never a FK (ARCHITECTURE §3.2).';


-- -----------------------------------------------------------------------------
-- announcement_channel — the selected delivery channels (enum value collection).
-- -----------------------------------------------------------------------------
CREATE TABLE announcement_channel (
    announcement_id BIGINT      NOT NULL,                     -- FK announcement.id
    channel         VARCHAR(16) NOT NULL,                     -- Channel enum name

    CONSTRAINT fk_announcement_channel_owner
        FOREIGN KEY (announcement_id) REFERENCES announcement (id) ON DELETE CASCADE,
    CONSTRAINT ck_announcement_channel CHECK (channel IN ('FEED','PUSH','SMS','EMAIL'))
);
CREATE INDEX ix_announcement_channel_owner ON announcement_channel (announcement_id);

COMMENT ON TABLE announcement_channel IS 'Delivery channels selected for an announcement (PRD §9.1 channels[]).';


-- -----------------------------------------------------------------------------
-- announcement_attachment — object-store keys for attachments (value collection).
-- -----------------------------------------------------------------------------
CREATE TABLE announcement_attachment (
    announcement_id BIGINT       NOT NULL,                    -- FK announcement.id
    attachment_ref  VARCHAR(512) NOT NULL,                    -- object-store key (signed-URL fetched, EI-8)

    CONSTRAINT fk_announcement_attachment_owner
        FOREIGN KEY (announcement_id) REFERENCES announcement (id) ON DELETE CASCADE
);
CREATE INDEX ix_announcement_attachment_owner ON announcement_attachment (announcement_id);

COMMENT ON TABLE announcement_attachment IS 'Object-store keys for announcement attachments (virus-scanned on upload, EI-8); never inline blobs.';
