-- =============================================================================
-- V28__communications_subscription.sql  —  Follows/subscriptions (communications, M4).
--
-- Responsibility: create the `subscription` table behind the JPA entity
-- com.taarifu.communications.domain.model.Subscription (a follow edge:
-- profile -> {AREA|REPRESENTATIVE|CATEGORY}). MUST match the entity so
-- ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §9.1, UC-G05).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * follower_profile_id and target_id are bare UUIDs, NOT foreign keys — the
--     follower (identity) and the target (geography/institutions/reporting) are owned
--     by other modules (ARCHITECTURE §3.2).
--   * ONE follow per (follower, target_type, target_id) AMONG LIVE ROWS: unfollow is a
--     soft-delete (history stays auditable, PRD §9), so the uniqueness must be scoped
--     to deleted = false — JPA cannot express partial uniqueness, so the DB owns a
--     PARTIAL UNIQUE INDEX here. The table-level UNIQUE constraint on the entity covers
--     the common case but would wrongly block a re-follow after an unfollow; the partial
--     index is the correct, authoritative guarantee.
--
-- NOTE on the entity's @UniqueConstraint: Hibernate ddl-auto=validate does NOT verify
--   table-level UNIQUE constraints/indexes (it validates columns, types, and nullability,
--   not arbitrary constraints), so declaring the live-scoped partial unique index here —
--   instead of a full UNIQUE matching the annotation — keeps validate green while giving
--   the stronger, soft-delete-aware guarantee.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE subscription (
    -- BaseEntity (ARCHITECTURE §4.2).
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID        NOT NULL,
    version             BIGINT      NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    -- Domain columns (Subscription.java).
    follower_profile_id UUID        NOT NULL,                 -- bare ref to identity profile; never a FK
    target_type         VARCHAR(16) NOT NULL,                 -- SubscriptionTargetType
    target_id           UUID        NOT NULL,                 -- bare ref to the followed entity; never a FK

    CONSTRAINT uq_subscription_public_id UNIQUE (public_id),
    CONSTRAINT ck_subscription_target_type CHECK (target_type IN ('AREA','REPRESENTATIVE','CATEGORY'))
);

-- Entity-declared lookup indexes.
CREATE INDEX ix_subscription_follower ON subscription (follower_profile_id);
CREATE INDEX ix_subscription_target   ON subscription (target_type, target_id);

-- INVARIANT (DB-owned): at most ONE LIVE follow per (follower, target_type, target_id).
-- Scoped to live rows so a soft-deleted (unfollowed) edge never blocks a fresh re-follow.
CREATE UNIQUE INDEX ux_subscription_follow_live
    ON subscription (follower_profile_id, target_type, target_id)
    WHERE deleted = FALSE;

COMMENT ON TABLE  subscription                     IS 'Follow edge: a profile follows an area/representative/category; drives the personalised feed (PRD §9.1, UC-G05).';
COMMENT ON COLUMN subscription.follower_profile_id IS 'Following profile publicId (identity); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN subscription.target_id           IS 'Followed target publicId (geography area / institutions representative / reporting category); bare UUID ref, never a FK.';
COMMENT ON COLUMN subscription.target_type         IS 'SubscriptionTargetType discriminator: AREA, REPRESENTATIVE, CATEGORY.';
