-- =============================================================================
-- V29__communications_notification.sql  —  Notifications (communications, M5).
--
-- Responsibility: create the `notification` table behind the JPA entity
-- com.taarifu.communications.domain.model.Notification (one delivery of one event to
-- one recipient over one channel). MUST match the entity so ddl-auto=validate passes
-- (ARCHITECTURE §4.1, PRD §13).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * recipient_profile_id is a bare UUID, NOT a FK (identity owns profiles;
--     ARCHITECTURE §3.2).
--   * payload_ref is a REFERENCE (announcement publicId / object-store key), never the
--     content itself — keeps the row PII-free and small (PRD §18).
--   * idempotency_key is UNIQUE: SMS/push webhooks and outbox relays deliver
--     at-least-once and replay (EI-3); a stable key + unique index guarantees no
--     double-send and lets a retry find the existing row (DI4). This is the load-bearing
--     idempotency invariant of the dispatch path — the DB owns it.
--   * Status lifecycle QUEUED->SENT->DELIVERED->READ / ->FAILED; SENT and DELIVERED are
--     distinct (gateway-accepted vs carrier/device-confirmed via DLR webhook, EI-3).
--
-- Type mapping contract (entity -> column):
--   Long->bigint identity, UUID->uuid, Instant->timestamp with time zone,
--   @Enumerated(STRING)->varchar(<declared length>), String->varchar(<length>).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE notification (
    -- BaseEntity (ARCHITECTURE §4.2).
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID         NOT NULL,
    version              BIGINT       NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE,
    created_by           UUID,
    updated_at           TIMESTAMP WITH TIME ZONE,
    updated_by           UUID,
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMP WITH TIME ZONE,
    deleted_by           UUID,

    -- Domain columns (Notification.java).
    recipient_profile_id UUID         NOT NULL,               -- bare ref to identity profile; never a FK
    type                 VARCHAR(32)  NOT NULL,               -- NotificationType
    payload_ref          VARCHAR(512),                        -- source ref/deep-link; never inline content (PRD §18)
    channel              VARCHAR(16)  NOT NULL,               -- Channel
    status               VARCHAR(16)  NOT NULL,               -- NotificationStatus
    idempotency_key      VARCHAR(200) NOT NULL,               -- stable de-dup key (DI4)
    sent_at              TIMESTAMP WITH TIME ZONE,
    delivered_at         TIMESTAMP WITH TIME ZONE,
    read_at              TIMESTAMP WITH TIME ZONE,
    failure_reason       VARCHAR(128),                        -- non-PII reason on FAILED

    CONSTRAINT uq_notification_public_id UNIQUE (public_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs.
    CONSTRAINT ck_notification_type    CHECK (type    IN ('NEW_ANNOUNCEMENT','REPORT_STATUS','MODERATION_OUTCOME','SYSTEM')),
    CONSTRAINT ck_notification_channel CHECK (channel IN ('FEED','PUSH','SMS','EMAIL')),
    CONSTRAINT ck_notification_status  CHECK (status  IN ('QUEUED','SENT','DELIVERED','READ','FAILED'))
);

-- Entity-declared indexes (names identical to avoid drift).
CREATE INDEX        ix_notification_recipient   ON notification (recipient_profile_id, created_at);
CREATE INDEX        ix_notification_status      ON notification (status);
-- INVARIANT (DB-owned): the idempotency key is globally unique — no double-send (DI4).
-- The entity declares this index as unique; a plain UNIQUE INDEX matches it exactly.
CREATE UNIQUE INDEX ix_notification_idempotency ON notification (idempotency_key);

COMMENT ON TABLE  notification                      IS 'One delivery of one event to one recipient over one channel; tracks delivery status (PRD §13, M5).';
COMMENT ON COLUMN notification.recipient_profile_id IS 'Recipient profile publicId (identity); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN notification.payload_ref          IS 'Source reference (announcement publicId / object-store key); never inline content/PII (PRD §18).';
COMMENT ON COLUMN notification.idempotency_key      IS 'Stable de-dup key; UNIQUE — guarantees no double-send under at-least-once delivery (DI4, EI-3).';
COMMENT ON COLUMN notification.status               IS 'NotificationStatus: QUEUED->SENT->DELIVERED->READ / ->FAILED. SENT=gateway-accepted, DELIVERED=carrier/device-confirmed (DLR, EI-3).';
