-- =============================================================================
-- V2__geography.sql  —  Administrative + electoral geography (geography module).
--
-- Responsibility: create the tables behind the geography domain model — the single
-- discriminated `location` hierarchy (Mkoa..Kitongoji), its closure table, the
-- electoral `constituency`, and the effective-dated `ward_constituency` bridge.
-- These MUST match the JPA entities exactly so Hibernate ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1/§4.3, PRD §9.0).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * One discriminated `location` table + a closure table — NOT a table per level
--     (the legacy `Area` duplication mistake). Closure gives O(1) indexed
--     "all descendants of a district" / "full ancestor chain of a ward" reads at
--     national scale (PRD §15, §9.0).
--   * Two overlapping geographies: the admin chain drives services/officials/routing;
--     `constituency` (Jimbo) drives representation. A citizen pins a place; both
--     chains are derived (PRD §9.0). Constituency is its own entity, not an admin level.
--   * `ward_constituency` is EFFECTIVE-DATED so re-delimitation never corrupts history
--     (EI-14): a boundary change closes the old row (sets effective_to) and inserts a
--     new one; historical reports/ratings still resolve to the constituency in effect
--     at action time. The DB owns two invariants JPA cannot express:
--       - at most ONE current (effective_to IS NULL) mapping per ward (partial unique);
--       - NO overlapping date ranges per ward (EXCLUDE with gist).
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id            -> bigint identity PK
--   UUID public_id     -> uuid not null unique
--   Long version       -> bigint not null
--   Instant created_at -> timestamp with time zone   (Hibernate 6 maps Instant to TIMESTAMP_UTC)
--   UUID *_by          -> uuid
--   boolean deleted    -> boolean not null
--   LocalDate eff_*    -> date
--   @Enumerated(STRING)-> varchar(<declared length>)
--   geometry columns   -> exactly the entity columnDefinition (PostGIS, SRID 4326)
--
-- Forward-only; idempotent table creation is NOT used here (these are net-new tables
-- owned solely by this migration). Never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- location — one node of Tanzania's administrative hierarchy, discriminated by type.
-- -----------------------------------------------------------------------------
CREATE TABLE location (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    -- Domain columns (Location.java).
    code            VARCHAR(32)  NOT NULL,                 -- official admin code; idempotent seed match key (EI-14)
    name            VARCHAR(160) NOT NULL,                 -- display name in local civic vocabulary
    type            VARCHAR(16)  NOT NULL,                 -- LocationType: REGION..HAMLET
    parent_id       BIGINT,                                -- self-FK; NULL only for REGION rows
    status          VARCHAR(16)  NOT NULL,                 -- LocationStatus: ACTIVE/INACTIVE (civic retirement)
    population      BIGINT,                                -- optional reference attribute
    boundary        geometry(MultiPolygon, 4326),          -- optional ward polygon for GPS->ward (EI-7)
    centroid        geometry(Point, 4326),                 -- optional display point

    CONSTRAINT uq_location_public_id UNIQUE (public_id),
    CONSTRAINT uq_location_code      UNIQUE (code),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns
    -- (defense in depth: the DB rejects any value outside the LocationType/LocationStatus enums).
    CONSTRAINT ck_location_type   CHECK (type   IN ('REGION','DISTRICT','COUNCIL','DIVISION','WARD','VILLAGE','MTAA','HAMLET')),
    CONSTRAINT ck_location_status CHECK (status IN ('ACTIVE','INACTIVE')),
    -- Self-referential admin parent; ON DELETE not cascaded — civic rows are soft-deleted, never physically removed.
    CONSTRAINT fk_location_parent    FOREIGN KEY (parent_id) REFERENCES location (id)
);

-- Indexes mirror the entity @Index set (names kept identical to avoid drift).
CREATE INDEX        ix_location_parent ON location (parent_id);
CREATE INDEX        ix_location_type   ON location (type);
-- uq_location_code already provides the unique index the entity declares as ix_location_code(unique).
-- GiST spatial index on the ward boundary: required for fast ST_Contains / ST_DWithin point-in-polygon (EI-7).
-- Partial (WHERE boundary IS NOT NULL) because geometry is sparse — typically only WARD rows carry it.
CREATE INDEX ix_location_boundary_gist ON location USING gist (boundary) WHERE boundary IS NOT NULL;

COMMENT ON TABLE  location            IS 'Single discriminated node of TZ admin hierarchy (Mkoa..Kitongoji); closure table holds transitive ancestry (PRD §9.0).';
COMMENT ON COLUMN location.public_id  IS 'Public, non-enumerable UUID exposed in URLs/DTOs (PRD §17); internal id never leaves the backend.';
COMMENT ON COLUMN location.code       IS 'Official administrative code; unique; idempotent match key for seed/bulk import (EI-14).';
COMMENT ON COLUMN location.type       IS 'LocationType discriminator: REGION,DISTRICT,COUNCIL,DIVISION,WARD,VILLAGE,MTAA,HAMLET (D14).';
COMMENT ON COLUMN location.parent_id  IS 'Immediate admin parent (self-FK); NULL only for REGION rows.';
COMMENT ON COLUMN location.status     IS 'LocationStatus ACTIVE/INACTIVE: civic retirement (re-delimitation), distinct from soft-delete.';
COMMENT ON COLUMN location.boundary   IS 'Optional ward polygon (PostGIS, SRID 4326) for GPS->ward point-in-polygon (EI-7); absence degrades to manual drill-down.';
COMMENT ON COLUMN location.centroid   IS 'Optional representative point (PostGIS, SRID 4326) for map display.';


-- -----------------------------------------------------------------------------
-- location_closure — (ancestor, descendant, depth) rows for indexed hierarchy reads.
-- -----------------------------------------------------------------------------
CREATE TABLE location_closure (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID    NOT NULL,
    version         BIGINT  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    ancestor_id     BIGINT  NOT NULL,                      -- FK location.id
    descendant_id   BIGINT  NOT NULL,                      -- FK location.id
    depth           INTEGER NOT NULL,                      -- 0 = self, 1 = direct child, n = n levels deep

    CONSTRAINT uq_location_closure_public_id UNIQUE (public_id),
    CONSTRAINT uq_closure_pair               UNIQUE (ancestor_id, descendant_id),  -- matches entity @UniqueConstraint
    CONSTRAINT fk_closure_ancestor           FOREIGN KEY (ancestor_id)   REFERENCES location (id),
    CONSTRAINT fk_closure_descendant         FOREIGN KEY (descendant_id) REFERENCES location (id)
);

CREATE INDEX ix_closure_ancestor   ON location_closure (ancestor_id);
CREATE INDEX ix_closure_descendant ON location_closure (descendant_id);

COMMENT ON TABLE  location_closure        IS 'Closure table: one row per (ancestor,descendant) incl. self-pair (depth 0); enables single-query subtree/ancestry reads (ARCHITECTURE.md §4.3).';
COMMENT ON COLUMN location_closure.depth  IS 'Edge distance: 0 self, 1 direct child, n n-levels-deep — supports "children only" (=1) vs "all descendants" (>=1).';


-- -----------------------------------------------------------------------------
-- constituency — electoral unit (Jimbo) homed in a DISTRICT; member wards via bridge.
-- -----------------------------------------------------------------------------
CREATE TABLE constituency (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    code            VARCHAR(32)  NOT NULL,                 -- official electoral code; idempotent seed match key
    name            VARCHAR(160) NOT NULL,
    district_id     BIGINT,                                -- FK location.id (DISTRICT); nullable only to tolerate seed ordering

    CONSTRAINT uq_constituency_public_id UNIQUE (public_id),
    CONSTRAINT uq_constituency_code      UNIQUE (code),
    CONSTRAINT fk_constituency_district  FOREIGN KEY (district_id) REFERENCES location (id)
);

CREATE INDEX ix_constituency_district ON constituency (district_id);
-- uq_constituency_code already provides the unique index the entity declares as ix_constituency_code(unique).

COMMENT ON TABLE  constituency             IS 'Electoral constituency (Jimbo) an MP (Mbunge) is elected to; overlays the admin chain (PRD §9.0).';
COMMENT ON COLUMN constituency.district_id IS 'Administrative home district (FK location.id, type DISTRICT); member wards mapped via effective-dated ward_constituency, never a direct ward FK.';


-- -----------------------------------------------------------------------------
-- ward_constituency — EFFECTIVE-DATED ward(Kata)->constituency(Jimbo) bridge.
-- The single most important temporal-correctness table in the schema (EI-14).
-- -----------------------------------------------------------------------------
CREATE TABLE ward_constituency (
    id               BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID    NOT NULL,
    version          BIGINT  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE,
    created_by       UUID,
    updated_at       TIMESTAMP WITH TIME ZONE,
    updated_by       UUID,
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP WITH TIME ZONE,
    deleted_by       UUID,

    ward_id          BIGINT  NOT NULL,                     -- FK location.id (WARD)
    constituency_id  BIGINT  NOT NULL,                     -- FK constituency.id
    effective_from   DATE    NOT NULL,                     -- inclusive start
    effective_to     DATE,                                 -- exclusive end; NULL = currently in effect

    CONSTRAINT uq_ward_constituency_public_id UNIQUE (public_id),
    CONSTRAINT fk_ward_constituency_ward         FOREIGN KEY (ward_id)         REFERENCES location (id),
    CONSTRAINT fk_ward_constituency_constituency FOREIGN KEY (constituency_id) REFERENCES constituency (id),
    -- Range sanity: end (if set) must be strictly after start.
    CONSTRAINT ck_ward_constituency_range CHECK (effective_to IS NULL OR effective_to > effective_from)
);

-- Entity-declared lookup indexes.
CREATE INDEX ix_ward_constituency_ward         ON ward_constituency (ward_id);
CREATE INDEX ix_ward_constituency_constituency ON ward_constituency (constituency_id);
CREATE INDEX ix_ward_constituency_effective    ON ward_constituency (ward_id, effective_from, effective_to);

-- INVARIANT 1 (DB-owned): at most one CURRENT mapping per ward.
-- Partial unique index — JPA cannot express this; the DB is the only place it can be guaranteed.
-- Scoped to live rows (deleted = false) so a soft-deleted historical row never blocks a new current one.
CREATE UNIQUE INDEX ux_ward_constituency_current
    ON ward_constituency (ward_id)
    WHERE effective_to IS NULL AND deleted = FALSE;

-- INVARIANT 2 (DB-owned): NO overlapping effective ranges for the same ward.
-- Without this, two mappings could both claim the same ward on the same date and "find-my-rep"
-- would be ambiguous. EXCLUDE + GiST is the correct tool; daterange treats NULL effective_to as
-- "unbounded above" (open current period). Applies only to live rows (deleted = false).
-- btree_gist provides the '=' operator class for the scalar ward_id inside a gist EXCLUDE.
CREATE EXTENSION IF NOT EXISTS btree_gist;
ALTER TABLE ward_constituency
    ADD CONSTRAINT ex_ward_constituency_no_overlap
    EXCLUDE USING gist (
        ward_id WITH =,
        daterange(effective_from, effective_to, '[)') WITH &&
    ) WHERE (deleted = FALSE);

COMMENT ON TABLE  ward_constituency                IS 'Effective-dated ward->constituency bridge; re-delimitation closes a row and inserts a new one, never rewrites history (EI-14).';
COMMENT ON COLUMN ward_constituency.effective_from IS 'Inclusive date this mapping took effect.';
COMMENT ON COLUMN ward_constituency.effective_to   IS 'Exclusive end date; NULL = currently in effect. Partial unique + EXCLUDE guarantee one current, non-overlapping mapping per ward.';
COMMENT ON COLUMN ward_constituency.ward_id        IS 'Ward side (FK location.id, type WARD).';
COMMENT ON COLUMN ward_constituency.constituency_id IS 'Constituency side (FK constituency.id).';
