-- =============================================================================
-- V30__communications_notification_preference.sql  —  Notification prefs (M5).
--
-- Responsibility: create the `notification_preference` table behind the JPA entity
-- com.taarifu.communications.domain.model.NotificationPreference (a citizen's opt-in
-- per (type, channel) + quiet hours + language). MUST match the entity so
-- ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §13, UC-G08).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * profile_id is a bare UUID, NOT a FK (identity owns profiles; ARCHITECTURE §3.2).
--   * ONE preference per (profile, type, channel) AMONG LIVE ROWS: the dispatcher looks
--     up exactly one row per pair. Enforced by a PARTIAL UNIQUE INDEX scoped to
--     deleted = false (JPA cannot express partial uniqueness; the DB owns it). The
--     entity's table-level @UniqueConstraint documents intent; ddl-auto=validate does
--     not check it, so the partial index here is the authoritative, soft-delete-aware
--     guarantee.
--   * quiet_from/quiet_to are LOCAL times (no zone) — the dispatcher applies them in the
--     recipient's local zone (EAT); FEED is never suppressed by quiet hours (EI-5).
--   * "Always-on" types (SYSTEM, MODERATION_OUTCOME) cannot be disabled — enforced in the
--     service (a row attempting to disable them is rejected, PRD §13), not by the schema.
--
-- Type mapping contract (entity -> column):
--   Long->bigint identity, UUID->uuid, LocalTime->time without time zone,
--   @Enumerated(STRING)->varchar(<declared length>), boolean->boolean.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE notification_preference (
    -- BaseEntity (ARCHITECTURE §4.2).
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   UUID        NOT NULL,
    version     BIGINT      NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE,
    created_by  UUID,
    updated_at  TIMESTAMP WITH TIME ZONE,
    updated_by  UUID,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP WITH TIME ZONE,
    deleted_by  UUID,

    -- Domain columns (NotificationPreference.java).
    profile_id  UUID        NOT NULL,                         -- bare ref to identity profile; never a FK
    type        VARCHAR(32) NOT NULL,                         -- NotificationType
    channel     VARCHAR(16) NOT NULL,                         -- Channel
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,            -- opt-in (ignored for always-on types)
    quiet_from  TIME WITHOUT TIME ZONE,                       -- quiet window start (local), or NULL
    quiet_to    TIME WITHOUT TIME ZONE,                       -- quiet window end (local), or NULL
    language    VARCHAR(8),                                   -- BCP-47/ISO-639 tag, or NULL = request default

    CONSTRAINT uq_notification_preference_public_id UNIQUE (public_id),
    CONSTRAINT ck_notification_preference_type    CHECK (type    IN ('NEW_ANNOUNCEMENT','REPORT_STATUS','MODERATION_OUTCOME','SYSTEM')),
    CONSTRAINT ck_notification_preference_channel CHECK (channel IN ('FEED','PUSH','SMS','EMAIL'))
);

-- Entity-declared lookup index.
CREATE INDEX ix_notification_preference_profile ON notification_preference (profile_id);

-- INVARIANT (DB-owned): one LIVE preference per (profile, type, channel).
CREATE UNIQUE INDEX ux_notification_preference_pair_live
    ON notification_preference (profile_id, type, channel)
    WHERE deleted = FALSE;

COMMENT ON TABLE  notification_preference            IS 'Per-(type,channel) opt-in + quiet hours + language for a profile; the dispatcher consults it (PRD §13, UC-G08).';
COMMENT ON COLUMN notification_preference.profile_id IS 'Owning profile publicId (identity); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN notification_preference.enabled    IS 'Opt-in for this (type,channel); ignored for always-on types (SYSTEM/MODERATION_OUTCOME), which the service refuses to disable (PRD §13).';
COMMENT ON COLUMN notification_preference.quiet_from IS 'Quiet window start (local time); interruptive channels (PUSH/SMS) suppressed in-window; FEED never suppressed (EI-5).';
COMMENT ON COLUMN notification_preference.language   IS 'Preferred language tag templates render in (Swahili default, ADR-0010); NULL = follow request/account default.';
