-- =============================================================================
-- V31__tokens_core.sql  —  Wallet, append-only ledger, and free-quota counters
--                          (tokens module, M17, PRD §23, D18/D19).
--
-- Responsibility: create the core token-economy tables behind Wallet,
-- TokenTransaction (the append-only ledger), and WalletFreeQuotaState. These
-- MUST match the JPA entities exactly so Hibernate ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * The LEDGER (token_transaction) is the SOURCE OF TRUTH for balances
--     (PRD §23.1); wallet.cached_balance is only a denormalised cache kept in
--     step inside the same transaction. The ledger is APPEND-ONLY: no version,
--     no updated_*, no deleted columns — a correction is a new ADJUST/REFUND row,
--     never an edit (mirrors audit_event, AUTH-DESIGN §11). The application is
--     granted only INSERT+SELECT on it (REVOKE below documents the intent).
--   * idempotency_key is GLOBALLY UNIQUE so a replayed grant/earn/spend/purchase
--     (retried request, duplicate/out-of-order mobile-money webhook) is a no-op —
--     no double-credit, no double-spend (PRD §23.5 idempotent ledger).
--   * one wallet per owner: unique (owner_type, owner_id). Owners are referenced
--     by PUBLIC UUID only (identity/responders) — NO cross-module FK (§3.2).
--   * 🔒 CIVIC-INTEGRITY FENCE (D18): tokens meter convenience/volume/reach/
--     commercial only. No binding democratic action (sign petition/rate rep/
--     binding poll) ever produces a SPEND here — enforced in MeteringService and
--     unit-tested. There is intentionally no schema that ties a balance to a
--     democratic act.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id            -> bigint identity PK
--   UUID public_id     -> uuid not null unique
--   Long version       -> bigint not null              (BaseEntity subclasses only)
--   Instant created_at -> timestamp with time zone
--   UUID *_by          -> uuid
--   boolean deleted    -> boolean not null
--   long  (amount,...) -> bigint
--   int   (used_count) -> integer
--   @Enumerated(STRING)-> varchar(<declared length>)
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- wallet — one token balance per owner (citizen User or organisation/provider).
-- BaseEntity subclass: full audit + soft-delete + optimistic version.
-- -----------------------------------------------------------------------------
CREATE TABLE wallet (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    owner_type      VARCHAR(16)  NOT NULL,                 -- WalletOwnerType: USER | ORGANIZATION
    owner_id        UUID         NOT NULL,                 -- owner public id (identity/responders); no FK (§3.2)
    status          VARCHAR(16)  NOT NULL,                 -- WalletStatus: ACTIVE | FROZEN | CLOSED
    cached_balance  BIGINT       NOT NULL DEFAULT 0,       -- denormalised ledger sum (authoritative = ledger)

    CONSTRAINT uq_wallet_public_id UNIQUE (public_id),
    -- ONE wallet per owner (PRD §23.1). Enforced unconditionally (not partial) — an owner has exactly one.
    CONSTRAINT uq_wallet_owner UNIQUE (owner_type, owner_id),
    CONSTRAINT ck_wallet_owner_type CHECK (owner_type IN ('USER','ORGANIZATION')),
    CONSTRAINT ck_wallet_status     CHECK (status     IN ('ACTIVE','FROZEN','CLOSED')),
    CONSTRAINT ck_wallet_balance_nonneg CHECK (cached_balance >= 0)
);

CREATE INDEX ix_wallet_owner  ON wallet (owner_type, owner_id);
CREATE INDEX ix_wallet_status ON wallet (status);

COMMENT ON TABLE  wallet                IS 'One token balance per owner (User/Organisation). Authoritative balance is the token_transaction ledger; cached_balance is a same-tx cache (PRD §23.1).';
COMMENT ON COLUMN wallet.owner_id       IS 'Owner public id in its home module (identity/responders); referenced by id only — never a cross-module FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN wallet.status         IS 'WalletStatus: FROZEN blocks token spend (anti-abuse) but never the citizen free civic path (PRD §23.5).';
COMMENT ON COLUMN wallet.cached_balance IS 'Denormalised ledger sum, maintained atomically with each appended transaction; ledger is the source of truth.';


-- -----------------------------------------------------------------------------
-- token_transaction — APPEND-ONLY ledger; the source of truth for balances.
-- Deliberately NOT a BaseEntity: no version/updated_*/deleted — never mutated.
-- -----------------------------------------------------------------------------
CREATE TABLE token_transaction (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID         NOT NULL,

    wallet_id        BIGINT       NOT NULL,                -- FK wallet.id
    type             VARCHAR(16)  NOT NULL,                -- TokenTransactionType
    amount           BIGINT       NOT NULL,                -- POSITIVE magnitude; sign carried by type
    balance_after    BIGINT       NOT NULL,                -- running balance this entry produced
    action_code      VARCHAR(64),                          -- metered action / reason code (never a binding action)
    reason           VARCHAR(255),                          -- machine reason (GRANT/ADJUST/REFUND); never PII
    ref_entity_type  VARCHAR(48),                           -- causing entity type (REPORT/PETITION/PAYMENT/...)
    ref_entity_id    UUID,                                  -- causing entity public id (cross-module; no FK)
    idempotency_key  VARCHAR(200) NOT NULL,                 -- GLOBALLY UNIQUE; replays are no-ops (PRD §23.5)
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       UUID,                                  -- actor public id; never PII

    CONSTRAINT uq_token_tx_public_id    UNIQUE (public_id),
    CONSTRAINT uq_token_tx_idempotency  UNIQUE (idempotency_key),
    CONSTRAINT fk_token_tx_wallet       FOREIGN KEY (wallet_id) REFERENCES wallet (id),
    CONSTRAINT ck_token_tx_type CHECK (type IN ('GRANT','EARN','SPEND','PURCHASE','REFUND','EXPIRE','ADJUST')),
    -- amount is a magnitude: always positive; the type fixes whether it credits or debits.
    CONSTRAINT ck_token_tx_amount_pos CHECK (amount > 0),
    -- a wallet balance can never go negative (defence in depth; the services also guard this).
    CONSTRAINT ck_token_tx_balance_nonneg CHECK (balance_after >= 0)
);

CREATE INDEX ix_token_tx_wallet_time ON token_transaction (wallet_id, created_at);
CREATE INDEX ix_token_tx_type        ON token_transaction (type);
CREATE INDEX ix_token_tx_ref         ON token_transaction (ref_entity_type, ref_entity_id);

COMMENT ON TABLE  token_transaction                 IS 'Append-only token ledger — the source of truth for balances (PRD §23.1). Never updated/deleted; corrections are new ADJUST/REFUND rows. App is granted only INSERT+SELECT.';
COMMENT ON COLUMN token_transaction.amount          IS 'Positive magnitude in whole tokens; the type carries the sign (GRANT/EARN/PURCHASE/REFUND credit; SPEND/EXPIRE debit; ADJUST signed via balance_after).';
COMMENT ON COLUMN token_transaction.idempotency_key IS 'Globally-unique key; one business operation = one key, so a replayed/duplicate webhook or retry is a no-op (no double-credit/spend, PRD §23.5).';
COMMENT ON COLUMN token_transaction.action_code     IS 'Metered action or reason; NEVER a binding democratic action — those are never metered (fence, D18).';


-- -----------------------------------------------------------------------------
-- wallet_free_quota_state — per-(wallet, action) consumption counter for the
-- current recurring free-quota window. NOT a ledger entry (a free use moves no
-- tokens), so it is kept out of token_transaction (PRD §23.2).
-- -----------------------------------------------------------------------------
CREATE TABLE wallet_free_quota_state (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    wallet_id       BIGINT       NOT NULL,                 -- FK wallet.id
    action_code     VARCHAR(64)  NOT NULL,                 -- matches action_cost_policy.action_code
    window_start    TIMESTAMP WITH TIME ZONE NOT NULL,     -- UTC start of the current quota window
    used_count      INTEGER      NOT NULL DEFAULT 0,        -- free uses consumed in the current window

    CONSTRAINT uq_wallet_free_quota_public_id UNIQUE (public_id),
    CONSTRAINT fk_wallet_free_quota_wallet FOREIGN KEY (wallet_id) REFERENCES wallet (id),
    CONSTRAINT ck_wallet_free_quota_used_nonneg CHECK (used_count >= 0)
);

CREATE INDEX ix_wallet_free_quota_lookup ON wallet_free_quota_state (wallet_id, action_code);

-- INVARIANT (DB-owned): at most ONE live counter per (wallet, action). JPA cannot express
-- "unique only where deleted = false", so it lives here (mirrors geography ux_ward_constituency_current).
CREATE UNIQUE INDEX ux_wallet_free_quota_live
    ON wallet_free_quota_state (wallet_id, action_code)
    WHERE deleted = FALSE;

COMMENT ON TABLE  wallet_free_quota_state              IS 'Per-(wallet,action) free-use counter for the current recurring quota window; the allowance refreshes simply by the window rolling over — no scheduled job (PRD §23.1/§23.2).';
COMMENT ON COLUMN wallet_free_quota_state.window_start IS 'UTC start of the window this counter belongs to (QuotaPeriod.windowStart); a differing current window means the counter has refreshed.';
COMMENT ON COLUMN wallet_free_quota_state.used_count   IS 'Free uses consumed in the current window; the metering path consumes free quota BEFORE any tokens (PRD §23.2).';


-- -----------------------------------------------------------------------------
-- Ledger immutability intent: the application role must not UPDATE/DELETE the
-- ledger (append-only). The concrete REVOKE is environment-specific (the role
-- name differs per deployment); documented here so the DBA enforces it, mirroring
-- the audit_event approach (AUTH-DESIGN §11). Left as a comment to keep the
-- migration portable across the dev/test/prod roles.
--   REVOKE UPDATE, DELETE ON token_transaction FROM <app_role>;
-- -----------------------------------------------------------------------------
