-- =============================================================================
-- V32__tokens_config.sql  —  Admin-tunable cost/quota policies and behaviour
--                            rewards (tokens module, M17, PRD §23.4).
--
-- Responsibility: create action_cost_policy (per actionCode × role → cost +
-- free-quota period/count) and token_reward (per behaviour → grant + anti-farming
-- cap). Both are BaseEntity subclasses (audit + soft-delete + version) and MUST
-- match the JPA entities for ddl-auto=validate (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * VERSIONED, not mutated in place (PRD §23.4 "admin-tunable; versioned"): a
--     change deactivates the active row (active=false) and inserts a new
--     policy_version. The active row is the one used for new spends; history is
--     preserved so past metering semantics are auditable (PRD §23.5 transparency).
--   * Partial UNIQUE indexes guarantee at most ONE active, non-deleted policy per
--     (action_code, role_name) and one active reward per behaviour. JPA cannot
--     express "unique where active = true", so it lives in SQL (mirrors
--     geography ux_ward_constituency_current).
--   * role_name is the identity RoleName VALUE (string), not an FK — avoids a
--     cross-module enum/table dependency (§3.2). NULL role_name = the action's
--     default/fallback policy.
--   * 🔒 FENCE (D18): no policy may price a binding democratic action; the admin
--     service rejects such action codes before insert, and those actions are never
--     metered at all. Free quotas are sized so civic-core participation never needs
--     tokens (PRD §23.5 accessibility/equity).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- action_cost_policy — what a metered action costs and how much of it is free,
-- per (action_code, role_name). Free quota is consumed BEFORE tokens (PRD §23.2).
-- -----------------------------------------------------------------------------
CREATE TABLE action_cost_policy (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL,
    version            BIGINT       NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE,
    created_by         UUID,
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         UUID,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMP WITH TIME ZONE,
    deleted_by         UUID,

    action_code        VARCHAR(64)  NOT NULL,              -- metered action (FILE_REPORT, ASK_REP, BOOST_REPORT, ...)
    role_name          VARCHAR(32),                         -- identity RoleName value; NULL = default policy
    token_cost         BIGINT       NOT NULL,               -- per-use cost AFTER free quota; 0 = always free
    free_quota_period  VARCHAR(16)  NOT NULL,               -- QuotaPeriod: LIFETIME/DAILY/WEEKLY/MONTHLY
    free_quota_count   INTEGER      NOT NULL,               -- free uses per period; 0 = no free quota
    policy_version     INTEGER      NOT NULL DEFAULT 1,     -- monotonic version for this key (audit)
    active             BOOLEAN      NOT NULL DEFAULT TRUE,  -- exactly one active row per key (partial unique)

    CONSTRAINT uq_action_cost_policy_public_id UNIQUE (public_id),
    CONSTRAINT ck_action_cost_policy_period CHECK (free_quota_period IN ('LIFETIME','DAILY','WEEKLY','MONTHLY')),
    CONSTRAINT ck_action_cost_policy_cost_nonneg  CHECK (token_cost >= 0),
    CONSTRAINT ck_action_cost_policy_quota_nonneg CHECK (free_quota_count >= 0)
);

CREATE INDEX ix_action_cost_policy_lookup ON action_cost_policy (action_code, role_name, active);

-- INVARIANT (DB-owned): at most ONE active, non-deleted policy per (action_code, role_name).
-- A partial unique index handles the NULL role_name (default) rows correctly because COALESCE
-- collapses NULL to a sentinel so two default rows for the same action cannot both be active.
CREATE UNIQUE INDEX ux_action_cost_policy_active
    ON action_cost_policy (action_code, COALESCE(role_name, '*DEFAULT*'))
    WHERE active = TRUE AND deleted = FALSE;

COMMENT ON TABLE  action_cost_policy                  IS 'Per (actionCode × role) cost + recurring free quota; admin-tunable and versioned (PRD §23.4). Free quota consumed before tokens (PRD §23.2).';
COMMENT ON COLUMN action_cost_policy.role_name        IS 'Identity RoleName value (e.g. CITIZEN); NULL = default/fallback policy for the action. Referenced by value, not FK (§3.2).';
COMMENT ON COLUMN action_cost_policy.active           IS 'Exactly one active row per (action_code, role_name) via ux_action_cost_policy_active; superseded rows are deactivated, never deleted (versioned config).';
COMMENT ON COLUMN action_cost_policy.token_cost       IS 'Tokens charged per use AFTER the free allowance; 0 = always free. Binding democratic actions are never priced here (fence, D18).';


-- -----------------------------------------------------------------------------
-- token_reward — how many tokens a validated good-civic-behaviour earns, with an
-- anti-farming cap per period (PRD §23.3/§23.4/§23.5).
-- -----------------------------------------------------------------------------
CREATE TABLE token_reward (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID         NOT NULL,
    version        BIGINT       NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE,
    created_by     UUID,
    updated_at     TIMESTAMP WITH TIME ZONE,
    updated_by     UUID,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMP WITH TIME ZONE,
    deleted_by     UUID,

    behaviour      VARCHAR(48)  NOT NULL,                  -- RewardBehaviour
    grant_amount   BIGINT       NOT NULL,                  -- tokens granted per (validated) occurrence; > 0
    cap_count      INTEGER      NOT NULL,                  -- max grants per cap_period (anti-farming)
    cap_period     VARCHAR(16)  NOT NULL,                  -- QuotaPeriod for the cap window
    active         BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_token_reward_public_id UNIQUE (public_id),
    CONSTRAINT ck_token_reward_behaviour CHECK (behaviour IN
        ('PROFILE_COMPLETED','IDENTITY_VERIFIED_T3','RESOLUTION_CONFIRMED','HELPFUL_CONTRIBUTION','REPUTATION_MILESTONE')),
    CONSTRAINT ck_token_reward_cap_period CHECK (cap_period IN ('LIFETIME','DAILY','WEEKLY','MONTHLY')),
    CONSTRAINT ck_token_reward_grant_pos  CHECK (grant_amount > 0),
    CONSTRAINT ck_token_reward_cap_nonneg CHECK (cap_count >= 0)
);

CREATE INDEX ix_token_reward_behaviour ON token_reward (behaviour, active);

-- INVARIANT (DB-owned): at most ONE active, non-deleted reward per behaviour.
CREATE UNIQUE INDEX ux_token_reward_active
    ON token_reward (behaviour)
    WHERE active = TRUE AND deleted = FALSE;

COMMENT ON TABLE  token_reward              IS 'Per-behaviour token reward + anti-farming cap (PRD §23.3/§23.5). Earning is a positive-behaviour incentive, never democratic weight (fence, D18).';
COMMENT ON COLUMN token_reward.cap_count    IS 'Max grants per cap_period; with the idempotent ledger this prevents farming/double-credit (e.g. self-confirmed loops capped). PRD §23.5.';
COMMENT ON COLUMN token_reward.active       IS 'Exactly one active reward per behaviour via ux_token_reward_active; superseded rows are deactivated, never deleted.';
