-- =============================================================================
-- V33__tokens_payment_seam.sql  —  Phase 2 purchase seam: token_package + payment
--                                  (tokens module, M17, PRD §23.4/§23.6, D19).
--
-- Responsibility: create token_package (purchasable token bundles) and payment
-- (a mobile-money/card purchase lifecycle). Modelled NOW so Phase 2 needs no
-- breaking migration; NO real gateway, catalogue, or money movement ships in MVP
-- (PRD §23.6). Both are BaseEntity subclasses and MUST match the JPA entities for
-- ddl-auto=validate (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * Money is stored in MINOR UNITS as BIGINT, never floating-point — rounding
--     corruption is unacceptable on money (paranoid-on-money; standard fintech).
--   * payment.idempotency_key is UNIQUE: a replayed initiation (retry, duplicate/
--     out-of-order mobile-money webhook) is a no-op (PRD §23.5 anti-fraud).
--   * Tokens are credited (a PURCHASE ledger row in V31) ONLY when a payment
--     reaches PAID, and that credit is idempotent and RECONCILED against the
--     provider — never on the unverified callback alone (PRD §23.5). The Stub
--     PaymentProvider never settles, so MVP credits nothing here.
--   * Owner/wallet linkage is a real intra-module FK (payment -> wallet); the
--     provider rails are TZ mobile money + card (EI-20, D19).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- token_package — a purchasable bundle of tokens at a fixed price (Phase 2).
-- -----------------------------------------------------------------------------
CREATE TABLE token_package (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    version       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE,
    created_by    UUID,
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    UUID,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    UUID,

    name          VARCHAR(120) NOT NULL,
    token_amount  BIGINT       NOT NULL,                   -- tokens credited on purchase; > 0
    price_minor   BIGINT       NOT NULL,                   -- price in minor currency units; >= 0
    currency      VARCHAR(3)   NOT NULL DEFAULT 'TZS',     -- ISO-4217
    audience      VARCHAR(16)  NOT NULL,                   -- PackageAudience: CITIZEN/ORG/PROVIDER
    active        BOOLEAN      NOT NULL DEFAULT FALSE,      -- purchasable flag (off by default in MVP)

    CONSTRAINT uq_token_package_public_id UNIQUE (public_id),
    CONSTRAINT ck_token_package_audience CHECK (audience IN ('CITIZEN','ORG','PROVIDER')),
    CONSTRAINT ck_token_package_amount_pos   CHECK (token_amount > 0),
    CONSTRAINT ck_token_package_price_nonneg CHECK (price_minor >= 0)
);

CREATE INDEX ix_token_package_audience ON token_package (audience, active);

COMMENT ON TABLE  token_package             IS 'Phase 2 purchasable token bundle (PRD §23.4/§23.6). No purchase flow in MVP; the free path always suffices (PRD §23.5).';
COMMENT ON COLUMN token_package.price_minor IS 'Price in the currency minor units (BIGINT) — never floating-point money (rounding safety).';


-- -----------------------------------------------------------------------------
-- payment — lifecycle of one token-purchase attempt via mobile money / card (P2).
-- -----------------------------------------------------------------------------
CREATE TABLE payment (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID         NOT NULL,
    version          BIGINT       NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE,
    created_by       UUID,
    updated_at       TIMESTAMP WITH TIME ZONE,
    updated_by       UUID,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP WITH TIME ZONE,
    deleted_by       UUID,

    wallet_id        BIGINT       NOT NULL,                -- FK wallet.id (credited on PAID)
    package_id       BIGINT,                                -- FK token_package.id; NULL = ad-hoc amount
    provider         VARCHAR(16)  NOT NULL,                 -- PaymentProviderType: MPESA/TIGOPESA/AIRTELMONEY/HALOPESA/CARD
    provider_ref     VARCHAR(128),                          -- provider settlement reference (set async)
    amount_minor     BIGINT       NOT NULL,                 -- amount in minor currency units
    currency         VARCHAR(3)   NOT NULL DEFAULT 'TZS',
    status           VARCHAR(16)  NOT NULL,                 -- PaymentStatus: PENDING/PAID/FAILED/REFUNDED
    idempotency_key  VARCHAR(200) NOT NULL,                 -- UNIQUE; dedups initiation/retries (PRD §23.5)

    CONSTRAINT uq_payment_public_id   UNIQUE (public_id),
    CONSTRAINT uq_payment_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_payment_wallet  FOREIGN KEY (wallet_id)  REFERENCES wallet (id),
    CONSTRAINT fk_payment_package FOREIGN KEY (package_id) REFERENCES token_package (id),
    CONSTRAINT ck_payment_provider CHECK (provider IN ('MPESA','TIGOPESA','AIRTELMONEY','HALOPESA','CARD')),
    CONSTRAINT ck_payment_status   CHECK (status   IN ('PENDING','PAID','FAILED','REFUNDED')),
    CONSTRAINT ck_payment_amount_nonneg CHECK (amount_minor >= 0)
);

CREATE INDEX ix_payment_wallet       ON payment (wallet_id);
CREATE INDEX ix_payment_status       ON payment (status);
CREATE INDEX ix_payment_provider_ref ON payment (provider, provider_ref);

COMMENT ON TABLE  payment                 IS 'Phase 2 token-purchase lifecycle via TZ mobile money / card (PRD §23.4/§23.6, EI-20). Tokens credited (PURCHASE ledger row) only on PAID, idempotently and reconciled — never trust-the-callback (PRD §23.5).';
COMMENT ON COLUMN payment.idempotency_key IS 'Unique; one purchase attempt = one row, so a duplicate/out-of-order webhook or retry is a no-op (anti-fraud, PRD §23.5).';
COMMENT ON COLUMN payment.provider_ref    IS 'Provider settlement reference; reconciliation matches a verified settlement to exactly one payment row — never the raw callback body.';
