-- =============================================================================
-- V34__responders.sql  —  Responder / Service-Provider directory (responders module, M18).
--
-- Responsibility: create the tables behind the responders domain model — the
-- `responder_organisation` body, its `responder` capabilities (+ the
-- `responder_category` / `responder_coverage_area` element-collection side tables),
-- the `routing_rule` table, and the `responder_assignment` (one OWNER + collaborators)
-- table. These MUST match the JPA entities exactly so Hibernate ddl-auto=validate
-- passes (ARCHITECTURE.md §4.1, PRD §24).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * Generalises Area Official / Organisation: a government Area Official is simply
--     staff of a GOVERNMENT_AGENCY organisation (§24.1). One directory holds govt,
--     parastatal, utility, bank, telecom, civic-org and private bodies.
--   * Cross-module references are by id, NOT by FK: report_id, category ids, area ids
--     and user ids point at entities owned by the reporting/geography/identity modules,
--     which are built in parallel (ARCHITECTURE.md §3.2). Storing them as plain uuid
--     columns keeps this module independently buildable; FK/wiring is a later step.
--   * Multisectoral integrity (§24.3): a report has EXACTLY ONE OWNER assignment +
--     zero-or-more collaborators. The DB owns two invariants JPA cannot express:
--       - at most one live OWNER per report  (partial unique index);
--       - at most one live assignment per (report, responder) (partial unique index).
--   * Public-directory visibility (§24.4): only ACTIVE + verified organisations and
--     their ACTIVE responders are ever listed publicly. Enforced by the repository
--     queries; status/verified columns carry the data.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id            -> bigint identity PK
--   UUID public_id     -> uuid not null unique
--   Long version       -> bigint not null
--   Instant created_at -> timestamp with time zone   (Hibernate 6 maps Instant to TIMESTAMP_UTC)
--   UUID *_by / *_id   -> uuid
--   boolean            -> boolean not null
--   int priority       -> integer not null
--   @Enumerated(STRING)-> varchar(<declared length>)
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- responder_organisation — the body behind one or more responder capabilities.
-- -----------------------------------------------------------------------------
CREATE TABLE responder_organisation (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID         NOT NULL,
    version               BIGINT       NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE,
    created_by            UUID,
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            UUID,
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMP WITH TIME ZONE,
    deleted_by            UUID,

    -- Domain columns (Organisation.java).
    name                  VARCHAR(200) NOT NULL,
    type                  VARCHAR(32)  NOT NULL,                 -- OrganisationType
    status                VARCHAR(16)  NOT NULL,                 -- OrganisationStatus
    verified              BOOLEAN      NOT NULL DEFAULT FALSE,   -- §24.4 go-live gate (separate from status)
    contact_phone         VARCHAR(32),                           -- public directory contact (not citizen PII)
    contact_email         VARCHAR(200),
    website_url           VARCHAR(300),
    owner_user_public_id  UUID,                                  -- identity user (by id; no cross-module FK)

    CONSTRAINT uq_responder_org_public_id UNIQUE (public_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns (defense in depth).
    CONSTRAINT ck_responder_org_type   CHECK (type   IN ('GOVERNMENT_AGENCY','PARASTATAL','PRIVATE_COMPANY','UTILITY','BANK','TELECOM','CIVIC_ORG')),
    CONSTRAINT ck_responder_org_status CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','DISABLED'))
);

CREATE INDEX ix_responder_org_type   ON responder_organisation (type);
CREATE INDEX ix_responder_org_status ON responder_organisation (status);

COMMENT ON TABLE  responder_organisation            IS 'Responder body (govt/parastatal/utility/bank/telecom/civic/private) that handles citizen reports; generalises Area Official employer (PRD §24.1).';
COMMENT ON COLUMN responder_organisation.public_id  IS 'Public, non-enumerable UUID exposed in URLs/DTOs (PRD §17); internal id never leaves the backend.';
COMMENT ON COLUMN responder_organisation.verified   IS 'Moderator/Admin verification (PRD §24.4); only ACTIVE + verified orgs appear in the public directory and receive routed reports.';
COMMENT ON COLUMN responder_organisation.status     IS 'OrganisationStatus PENDING/ACTIVE/SUSPENDED/DISABLED; operational lifecycle distinct from verification and soft-delete.';
COMMENT ON COLUMN responder_organisation.owner_user_public_id IS 'Administering identity user, referenced BY ID (no cross-module FK — ARCHITECTURE §3.2).';


-- -----------------------------------------------------------------------------
-- responder — a handling capability of an organisation (the routing target).
-- -----------------------------------------------------------------------------
CREATE TABLE responder (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    organisation_id   BIGINT       NOT NULL,                     -- FK responder_organisation.id (same module)
    name              VARCHAR(200) NOT NULL,
    responder_type    VARCHAR(32)  NOT NULL,                     -- ResponderType (routing target)
    status            VARCHAR(16)  NOT NULL,                     -- ResponderStatus
    coverage_type     VARCHAR(16)  NOT NULL,                     -- CoverageType: AREAS | NATIONWIDE
    sla_policy        VARCHAR(1000),                             -- contractual/agreed SLA text (§24.1)

    CONSTRAINT uq_responder_public_id UNIQUE (public_id),
    CONSTRAINT fk_responder_org       FOREIGN KEY (organisation_id) REFERENCES responder_organisation (id),
    CONSTRAINT ck_responder_type      CHECK (responder_type IN ('GOVERNMENT_AGENCY','PARASTATAL','PRIVATE_COMPANY','UTILITY','BANK','TELECOM','CIVIC_ORG')),
    CONSTRAINT ck_responder_status    CHECK (status         IN ('PENDING','ACTIVE','SUSPENDED','RETIRED')),
    CONSTRAINT ck_responder_coverage  CHECK (coverage_type  IN ('AREAS','NATIONWIDE'))
);

CREATE INDEX ix_responder_org    ON responder (organisation_id);
CREATE INDEX ix_responder_type   ON responder (responder_type);
CREATE INDEX ix_responder_status ON responder (status);

COMMENT ON TABLE  responder                IS 'A handling capability of a responder organisation: sectors/categories handled, geographic coverage, SLA (PRD §24.1).';
COMMENT ON COLUMN responder.responder_type IS 'ResponderType — the kind a RoutingRule resolves a category to (PRD §24.2).';
COMMENT ON COLUMN responder.coverage_type  IS 'AREAS (explicit area-id set in responder_coverage_area) vs NATIONWIDE (covers everywhere) — explicit so widening visibility is auditable (PDPA, §24.4).';


-- -----------------------------------------------------------------------------
-- responder_category — @ElementCollection: reporting category ids a responder handles.
-- Referenced BY ID (no FK into the parallel reporting module).
-- -----------------------------------------------------------------------------
CREATE TABLE responder_category (
    responder_id        BIGINT NOT NULL,                         -- FK responder.id
    category_public_id  UUID   NOT NULL,                         -- reporting IssueCategory public id (by reference)

    CONSTRAINT fk_responder_category_responder FOREIGN KEY (responder_id) REFERENCES responder (id),
    -- A responder handles a category at most once; matches the entity's Set<UUID> semantics.
    CONSTRAINT uq_responder_category UNIQUE (responder_id, category_public_id)
);

CREATE INDEX ix_responder_category_cat ON responder_category (category_public_id);

COMMENT ON TABLE  responder_category IS 'Categories (reporting IssueCategory ids, by reference) a responder handles; element-collection of Responder.handledCategoryIds (PRD §24.1).';


-- -----------------------------------------------------------------------------
-- responder_coverage_area — @ElementCollection: geography area ids a responder covers.
-- Ignored when coverage_type = NATIONWIDE. Referenced BY ID (no FK into geography here).
-- -----------------------------------------------------------------------------
CREATE TABLE responder_coverage_area (
    responder_id    BIGINT NOT NULL,                             -- FK responder.id
    area_public_id  UUID   NOT NULL,                             -- geography Location public id (by reference)

    CONSTRAINT fk_responder_coverage_responder FOREIGN KEY (responder_id) REFERENCES responder (id),
    CONSTRAINT uq_responder_coverage_area UNIQUE (responder_id, area_public_id)
);

CREATE INDEX ix_responder_coverage_area ON responder_coverage_area (area_public_id);

COMMENT ON TABLE responder_coverage_area IS 'Areas (geography Location ids, by reference) a responder covers; element-collection of Responder.coverageAreaIds (PRD §24.1).';


-- -----------------------------------------------------------------------------
-- routing_rule — category(/sub) -> responder kind/sector -> area | citizen-selected.
-- -----------------------------------------------------------------------------
CREATE TABLE routing_rule (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID        NOT NULL,
    version                 BIGINT      NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE,
    created_by              UUID,
    updated_at              TIMESTAMP WITH TIME ZONE,
    updated_by              UUID,
    deleted                 BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP WITH TIME ZONE,
    deleted_by              UUID,

    category_public_id      UUID        NOT NULL,                -- reporting category (by reference)
    sub_category_public_id  UUID,                                -- optional reporting sub-category (by reference)
    responder_type          VARCHAR(32) NOT NULL,                -- ResponderType to route to
    selection_mode          VARCHAR(24) NOT NULL,                -- ProviderSelectionMode
    preferred_responder_id  BIGINT,                              -- optional pinned Responder (FK same module)
    priority                INTEGER     NOT NULL DEFAULT 100,    -- lower = evaluated first (§24.2 ladder)
    active                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_routing_rule_public_id  UNIQUE (public_id),
    CONSTRAINT fk_routing_rule_responder  FOREIGN KEY (preferred_responder_id) REFERENCES responder (id),
    CONSTRAINT ck_routing_rule_type       CHECK (responder_type IN ('GOVERNMENT_AGENCY','PARASTATAL','PRIVATE_COMPANY','UTILITY','BANK','TELECOM','CIVIC_ORG')),
    CONSTRAINT ck_routing_rule_selection  CHECK (selection_mode IN ('AUTO_BY_AREA','CITIZEN_SELECTED'))
);

CREATE INDEX ix_routing_rule_category       ON routing_rule (category_public_id);
CREATE INDEX ix_routing_rule_responder_type ON routing_rule (responder_type);
CREATE INDEX ix_routing_rule_active         ON routing_rule (active);

COMMENT ON TABLE  routing_rule                IS 'Maps a report category(/sub) to a responder kind/sector, narrowed by area or citizen-selected, with a priority/fallback ladder (PRD §24.2).';
COMMENT ON COLUMN routing_rule.selection_mode IS 'AUTO_BY_AREA (platform resolves by sector+area) vs CITIZEN_SELECTED (report flow shows a provider picker) — PRD §24.2.';
COMMENT ON COLUMN routing_rule.priority       IS 'Deterministic evaluation order; lower wins so a specific (sub-category) rule precedes a general one (PRD §24.2).';


-- -----------------------------------------------------------------------------
-- responder_assignment — one OWNER + collaborators link of a responder to a report.
-- The integrity core of multisectoral handling (PRD §24.3).
-- -----------------------------------------------------------------------------
CREATE TABLE responder_assignment (
    id                          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                   UUID        NOT NULL,
    version                     BIGINT      NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE,
    created_by                  UUID,
    updated_at                  TIMESTAMP WITH TIME ZONE,
    updated_by                  UUID,
    deleted                     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMP WITH TIME ZONE,
    deleted_by                  UUID,

    report_id                   UUID        NOT NULL,            -- reporting Report (BY ID; reporting built in parallel)
    responder_id                BIGINT      NOT NULL,            -- FK responder.id (same module)
    role                        VARCHAR(16) NOT NULL,            -- AssignmentRole: OWNER | COLLABORATOR
    status                      VARCHAR(16) NOT NULL,            -- AssignmentStatus
    assigned_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_by_user_public_id  UUID,                            -- identity user (by id)
    sla_policy                  VARCHAR(1000),

    CONSTRAINT uq_responder_assignment_public_id UNIQUE (public_id),
    CONSTRAINT fk_responder_assignment_responder FOREIGN KEY (responder_id) REFERENCES responder (id),
    CONSTRAINT ck_responder_assignment_role      CHECK (role   IN ('OWNER','COLLABORATOR')),
    CONSTRAINT ck_responder_assignment_status    CHECK (status IN ('PENDING','ACCEPTED','IN_PROGRESS','RESOLVED','REASSIGNED','REJECTED'))
);

CREATE INDEX ix_responder_assignment_report    ON responder_assignment (report_id);
CREATE INDEX ix_responder_assignment_responder ON responder_assignment (responder_id);
CREATE INDEX ix_responder_assignment_role      ON responder_assignment (role);
CREATE INDEX ix_responder_assignment_status    ON responder_assignment (status);

-- INVARIANT 1 (DB-owned): at most ONE live OWNER per report (PRD §24.3).
-- A report has exactly one accountable owner; the citizen tracks one issue with an aggregated status.
-- Partial unique index — JPA cannot express this; scoped to live (deleted = false) rows so a
-- soft-deleted historical owner never blocks reassignment.
CREATE UNIQUE INDEX ux_responder_assignment_one_owner
    ON responder_assignment (report_id)
    WHERE role = 'OWNER' AND deleted = FALSE;

-- INVARIANT 2 (DB-owned): a responder is assigned to a given report at most once (live).
-- Prevents accidental duplicate assignment of the same responder (owner or collaborator) to a report.
CREATE UNIQUE INDEX ux_responder_assignment_unique_per_report
    ON responder_assignment (report_id, responder_id)
    WHERE deleted = FALSE;

COMMENT ON TABLE  responder_assignment          IS 'Links a responder to a report as OWNER (exactly one) or COLLABORATOR (zero-or-more); multisectoral accountability (PRD §24.3).';
COMMENT ON COLUMN responder_assignment.report_id IS 'Reporting Report, referenced BY ID — reporting module is built in parallel; FK/wiring is a later integration step (ARCHITECTURE §3.2).';
COMMENT ON COLUMN responder_assignment.role      IS 'AssignmentRole OWNER|COLLABORATOR; the partial unique index ux_responder_assignment_one_owner guarantees one live OWNER per report.';
