-- =============================================================================
-- V36__engagement_petitions.sql  —  Petitions + signatures (engagement module, M9).
--
-- Responsibility: create the tables behind the Petition and PetitionSignature JPA
-- entities — a citizen/organisation petition addressed (by id) to a representative or
-- office, and the one-person-one-signature record that is the load-bearing civic
-- integrity invariant. MUST match the entities exactly so ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1, PRD §9.1, §12.2 M9).
--
-- LOCKED-DECISION / INTEGRITY invariants the DB owns here (PRD §23.5 fence, D13/D16/D18):
--   * ONE PERSON = ONE SIGNATURE per petition: uq_petition_signature_once on
--     (petition_id, signer_profile_id). This is the hard guarantee behind "one person
--     = one signature regardless of token balance" (PRD §23.5). The T3 tier gate and the
--     no-self-petition guard live in the application layer; THIS constraint is the
--     one-per-person half and cannot be bypassed under race.
--   * Cross-module references are by UUID, NOT FK: target_id (institutions: rep/office)
--     and creator_profile_id/creator_org_id (identity) are public ids — engagement must
--     not import institutions/identity tables (modular-monolith boundary, ARCHITECTURE §3.2).
--     petition_signature.petition_id IS a real FK (same module → referential integrity for
--     the derived count).
--   * signature_count is a DERIVED, denormalised counter on petition, bumped atomically
--     with each signature insert; it is NEVER a token-weighted value (integrity fence).
--
-- Type mapping contract (entity -> column), same rules as V2/V3:
--   Long id -> bigint identity PK ; UUID -> uuid ; Long version -> bigint not null ;
--   Instant -> timestamp with time zone ; int -> integer not null ; boolean -> boolean not null ;
--   @Enumerated(STRING) -> varchar(<declared length>) ; String(length=n) -> varchar(n).
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- petition — a citizen/org petition to a representative or office (M9).
-- -----------------------------------------------------------------------------
CREATE TABLE petition (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID          NOT NULL,
    version             BIGINT        NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    -- Domain columns (Petition.java).
    title               VARCHAR(200)  NOT NULL,
    body                VARCHAR(8000) NOT NULL,
    target_type         VARCHAR(16)   NOT NULL,             -- PetitionTargetType: REPRESENTATIVE | OFFICE
    target_id           UUID,                               -- institutions public id (rep/office) — by id only, no FK
    signature_goal      INTEGER       NOT NULL,
    signature_count     INTEGER       NOT NULL DEFAULT 0,   -- derived counter; NEVER token-weighted (PRD §23.5)
    deadline            TIMESTAMP WITH TIME ZONE,
    creator_profile_id  UUID,                               -- identity Profile public id (by id only)
    creator_org_id      UUID,                               -- organisation public id (by id only)
    status              VARCHAR(16)   NOT NULL,             -- PetitionStatus
    response            VARCHAR(8000),                      -- target's published response (RESPONDED)

    CONSTRAINT uq_petition_public_id UNIQUE (public_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns.
    CONSTRAINT ck_petition_target_type CHECK (target_type IN ('REPRESENTATIVE','OFFICE')),
    CONSTRAINT ck_petition_status      CHECK (status      IN ('DRAFT','ACTIVE','SUCCEEDED','RESPONDED','CLOSED'))
);

-- Entity-declared lookup indexes (names kept identical to the @Index set to avoid drift).
CREATE INDEX ix_petition_status         ON petition (status);
CREATE INDEX ix_petition_target         ON petition (target_type, target_id);
CREATE INDEX ix_petition_creator_profile ON petition (creator_profile_id);
CREATE INDEX ix_petition_creator_org     ON petition (creator_org_id);

COMMENT ON TABLE  petition                    IS 'Citizen/org petition to a representative or office (M9, PRD §12.2); signatures are a separate table.';
COMMENT ON COLUMN petition.target_id          IS 'Addressee public id in the institutions module (rep/office); referenced by id only — no cross-module FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN petition.signature_count    IS 'Derived, denormalised valid-signature count; bumped atomically with each signature; NEVER token-weighted (integrity fence, PRD §23.5).';
COMMENT ON COLUMN petition.creator_profile_id IS 'Authoring person identity Profile public id (by id only), or NULL for an org petition.';
COMMENT ON COLUMN petition.creator_org_id     IS 'Authoring organisation public id (by id only), or NULL for a person petition.';
COMMENT ON COLUMN petition.status             IS 'PetitionStatus DRAFT->ACTIVE->SUCCEEDED->RESPONDED->CLOSED (PRD §12.2); only non-DRAFT is publicly visible.';


-- -----------------------------------------------------------------------------
-- petition_signature — ONE person's signature on a petition (binding civic act, UC-E03).
-- The most integrity-critical table in this module (PRD §23.5 fence).
-- -----------------------------------------------------------------------------
CREATE TABLE petition_signature (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID          NOT NULL,
    version             BIGINT        NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    petition_id         BIGINT        NOT NULL,             -- real FK (same module)
    signer_profile_id   UUID          NOT NULL,             -- identity Profile public id (by id only)
    comment             VARCHAR(1000),
    is_public           BOOLEAN       NOT NULL DEFAULT FALSE, -- signer opt-in to public display (PDPA)

    CONSTRAINT uq_petition_signature_public_id UNIQUE (public_id),
    -- THE one-person-one-signature invariant (UC-E03; PRD §23.5). Matches the entity @UniqueConstraint.
    -- NOTE: this is a table-level UNIQUE (not partial) — a soft-deleted signature still blocks a re-sign,
    -- which is correct: withdrawing a signature is a domain action (status), not a physical re-insert.
    CONSTRAINT uq_petition_signature_once UNIQUE (petition_id, signer_profile_id),
    CONSTRAINT fk_petition_signature_petition FOREIGN KEY (petition_id) REFERENCES petition (id)
);

CREATE INDEX ix_petition_signature_petition ON petition_signature (petition_id);
CREATE INDEX ix_petition_signature_signer   ON petition_signature (signer_profile_id);

COMMENT ON TABLE  petition_signature                   IS 'One signature per (petition, signer): the one-person-one-signature integrity invariant behind PRD §23.5 (binding act, UC-E03).';
COMMENT ON COLUMN petition_signature.signer_profile_id IS 'Signer identity Profile public id (by id only — no FK into identity). Forms the one-per-person key with petition_id.';
COMMENT ON COLUMN petition_signature.is_public         IS 'Signer opt-in to be shown publicly; default FALSE (private). Counts toward the goal regardless (PDPA data-minimisation, PRD §18).';
