-- =============================================================================
-- V37__engagement_surveys.sql  —  Surveys/polls + responses (engagement module, M8).
--
-- Responsibility: create the tables behind the Survey and SurveyResponse JPA entities —
-- a survey/poll targeted at an audience (geo/role) with a questions blob, an open
-- window, an anonymity setting, and a binding flag; and the one-response-per-person
-- record. MUST match the entities exactly so ddl-auto=validate passes (ARCHITECTURE.md
-- §4.1, PRD §9.1, §12.2 M8).
--
-- LOCKED-DECISION / INTEGRITY invariants the DB owns here (PRD §23.5 fence, D18):
--   * ONE RESPONSE = ONE PERSON per survey: uq_survey_response_once on
--     (survey_id, responder_profile_id). For a BINDING poll this is the one-per-person
--     half of the integrity fence (the T3 tier gate lives in the app layer); for a
--     non-binding survey it still enforces "one response" (US-8.2). Never balance-gated.
--   * A non-POLL can never be binding: ck_survey_binding_only_poll.
--   * questions / audience_scope / answers are stored as BOUNDED VARCHAR JSON strings,
--     NOT native jsonb — a deliberate KISS choice for this Phase-2 scaffold so validate
--     stays dependency-free (no JSON type mapping). A later migration may promote to jsonb.
--   * Cross-module references (creator_profile_id, creator_org_id) are by UUID, not FK.
--     survey_response.survey_id IS a real FK (same module).
--
-- Type mapping contract — same rules as V36.
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- survey — a survey or poll targeted at an audience (M8).
-- -----------------------------------------------------------------------------
CREATE TABLE survey (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID           NOT NULL,
    version             BIGINT         NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN        NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    title               VARCHAR(200)   NOT NULL,
    description         VARCHAR(4000),
    type                VARCHAR(16)    NOT NULL,            -- SurveyType: SURVEY | POLL
    binding             BOOLEAN        NOT NULL DEFAULT FALSE, -- democratic-weight poll => T3 + one-per-person
    audience_scope      VARCHAR(4000),                     -- JSON string (geo/role); NULL = open to all eligible
    questions           VARCHAR(16000),                    -- JSON string (US-8.1 question/option defs)
    starts_at           TIMESTAMP WITH TIME ZONE,
    ends_at             TIMESTAMP WITH TIME ZONE,
    anonymous           BOOLEAN        NOT NULL DEFAULT FALSE,
    status              VARCHAR(16)    NOT NULL,            -- SurveyStatus
    creator_profile_id  UUID,                              -- identity Profile public id (by id only)
    creator_org_id      UUID,                              -- organisation public id (by id only)

    CONSTRAINT uq_survey_public_id UNIQUE (public_id),
    CONSTRAINT ck_survey_type   CHECK (type   IN ('SURVEY','POLL')),
    CONSTRAINT ck_survey_status CHECK (status IN ('DRAFT','SCHEDULED','OPEN','CLOSED','ARCHIVED')),
    -- A non-poll can never be binding (defense in depth; the entity also enforces this).
    CONSTRAINT ck_survey_binding_only_poll CHECK (binding = FALSE OR type = 'POLL')
);

CREATE INDEX ix_survey_status          ON survey (status);
CREATE INDEX ix_survey_type            ON survey (type);
CREATE INDEX ix_survey_creator_profile ON survey (creator_profile_id);
CREATE INDEX ix_survey_creator_org     ON survey (creator_org_id);

COMMENT ON TABLE  survey                IS 'Survey/poll targeted at an audience (M8, PRD §12.2); responses are a separate table.';
COMMENT ON COLUMN survey.binding        IS 'TRUE = binding poll: responding is a democratic-weight act (T3 + one-per-person, PRD §23.5). Forced FALSE for a non-poll.';
COMMENT ON COLUMN survey.audience_scope IS 'JSON string audience descriptor (area public ids / role names, US-8.1); bounded varchar, not jsonb (scaffold KISS); NULL = open to all eligible tiers.';
COMMENT ON COLUMN survey.questions      IS 'JSON string question/option definitions (US-8.1 single/multi/scale/text); bounded varchar (scaffold).';
COMMENT ON COLUMN survey.anonymous      IS 'TRUE = responder id retained for one-per-person but never exposed in results (PDPA data-minimisation, PRD §18).';
COMMENT ON COLUMN survey.status         IS 'SurveyStatus DRAFT->SCHEDULED->OPEN->CLOSED->ARCHIVED (PRD §12.2); only OPEN accepts responses, only non-DRAFT is publicly visible.';


-- -----------------------------------------------------------------------------
-- survey_response — ONE respondent's answers (one-per-person; binding => T3 in app layer).
-- -----------------------------------------------------------------------------
CREATE TABLE survey_response (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID          NOT NULL,
    version               BIGINT        NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE,
    created_by            UUID,
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            UUID,
    deleted               BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMP WITH TIME ZONE,
    deleted_by            UUID,

    survey_id             BIGINT        NOT NULL,           -- real FK (same module)
    responder_profile_id  UUID          NOT NULL,           -- identity Profile public id (by id only)
    answers               VARCHAR(16000),                   -- JSON string answers payload

    CONSTRAINT uq_survey_response_public_id UNIQUE (public_id),
    -- THE one-response-per-person invariant (US-8.2; binding poll => fence half, PRD §23.5).
    CONSTRAINT uq_survey_response_once UNIQUE (survey_id, responder_profile_id),
    CONSTRAINT fk_survey_response_survey FOREIGN KEY (survey_id) REFERENCES survey (id)
);

CREATE INDEX ix_survey_response_survey    ON survey_response (survey_id);
CREATE INDEX ix_survey_response_responder ON survey_response (responder_profile_id);

COMMENT ON TABLE  survey_response                      IS 'One response per (survey, responder): one-response-per-person (US-8.2); for a binding poll this is the fence half (PRD §23.5).';
COMMENT ON COLUMN survey_response.responder_profile_id IS 'Responder identity Profile public id (by id only). Retained even for anonymous surveys (never exposed then) so one-per-person holds.';
