-- =============================================================================
-- V38__engagement_qa.sql  —  Public Q&A: questions + answers (engagement module, M10).
--
-- Responsibility: create the tables behind the Question and Answer JPA entities — a
-- public question put (by id) to a representative, with an upvote counter and a
-- lifecycle, and the single answer a representative may publish. MUST match the entities
-- exactly so ddl-auto=validate passes (ARCHITECTURE.md §4.1, PRD §9.1, §12.2 M10).
--
-- LOCKED-DECISION / INTEGRITY notes (D16):
--   * Asking is a T2 action (PRD §7.3) — the tier gate lives in the app layer
--     (@RequiresTier("T2")). Asking is NOT binding, so there is deliberately NO
--     one-per-person constraint on questions (a citizen may ask several).
--   * No-self-question (a rep may not ask about themselves) and answer-by-target-only
--     are app-layer conflict guards (D16), audited — not schema constraints (they need
--     cross-module identity/institutions context).
--   * ONE answer per question: uq_qa_answer_question (a question is ANSWERED once).
--   * Cross-module references (asker_profile_id, target_rep_id, answered_by_rep_id) are
--     by UUID, not FK (institutions/identity boundary, ARCHITECTURE §3.2). qa_answer.question_id
--     IS a real FK (same module).
--
-- Type mapping contract — same rules as V36/V37. Tables prefixed qa_ to avoid any clash
-- with a future top-level `question`/`answer` concept in another module.
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- qa_question — a public question to a representative (M10).
-- -----------------------------------------------------------------------------
CREATE TABLE qa_question (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID          NOT NULL,
    version           BIGINT        NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    asker_profile_id  UUID          NOT NULL,               -- identity Profile public id (by id only)
    target_rep_id     UUID          NOT NULL,               -- institutions Representative public id (by id only)
    body              VARCHAR(4000) NOT NULL,
    upvotes           INTEGER       NOT NULL DEFAULT 0,
    status            VARCHAR(16)   NOT NULL,               -- QuestionStatus

    CONSTRAINT uq_qa_question_public_id UNIQUE (public_id),
    CONSTRAINT ck_qa_question_status CHECK (status IN ('OPEN','ANSWERED','DECLINED','MODERATED'))
);

CREATE INDEX ix_qa_question_status     ON qa_question (status);
CREATE INDEX ix_qa_question_target_rep ON qa_question (target_rep_id);
CREATE INDEX ix_qa_question_asker      ON qa_question (asker_profile_id);

COMMENT ON TABLE  qa_question                  IS 'Public Q&A question to a representative (M10, PRD §12.2). Asking is a T2 act; NOT one-per-person by design.';
COMMENT ON COLUMN qa_question.asker_profile_id IS 'Asker identity Profile public id (by id only — no FK into identity).';
COMMENT ON COLUMN qa_question.target_rep_id    IS 'Targeted representative public id in the institutions module (by id only — no cross-module FK).';
COMMENT ON COLUMN qa_question.upvotes          IS 'Denormalised upvote counter (UC-E11); per-voter one-vote + no-self-upvote are the M10 upvote sub-feature, not this scaffold.';
COMMENT ON COLUMN qa_question.status           IS 'QuestionStatus OPEN->ANSWERED|DECLINED|MODERATED (PRD §12.2); only OPEN/ANSWERED are publicly visible.';


-- -----------------------------------------------------------------------------
-- qa_answer — a representative's single answer to a question (UC-E10).
-- -----------------------------------------------------------------------------
CREATE TABLE qa_answer (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID          NOT NULL,
    version             BIGINT        NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    question_id         BIGINT        NOT NULL,             -- real FK (same module); one answer per question
    answered_by_rep_id  UUID          NOT NULL,             -- institutions Representative public id (must = question target)
    body                VARCHAR(8000) NOT NULL,

    CONSTRAINT uq_qa_answer_public_id UNIQUE (public_id),
    -- ONE answer per question (matches the entity @UniqueConstraint on question_id).
    CONSTRAINT uq_qa_answer_question UNIQUE (question_id),
    CONSTRAINT fk_qa_answer_question FOREIGN KEY (question_id) REFERENCES qa_question (id)
);

CREATE INDEX ix_qa_answer_answered_by ON qa_answer (answered_by_rep_id);

COMMENT ON TABLE  qa_answer                    IS 'A representative''s single answer to a Q&A question (UC-E10); one answer per question.';
COMMENT ON COLUMN qa_answer.answered_by_rep_id IS 'Answering representative public id (institutions, by id only); must equal the question target — verified in the app layer (D16).';
