-- =============================================================================
-- V3__identity.sql  —  Accounts, profiles, locations, roles, verification (identity).
--
-- Responsibility: create the identity module tables behind the JPA entities — one
-- account per person (app_user, unique phone), 1:1 profile with field-encrypted ID
-- + blind-index dedup, many private profile_locations with one-primary/one-electoral
-- singletons, the additive role catalogue + scoped assignments, verification queue,
-- and rotating refresh tokens. MUST match the entities so ddl-auto=validate passes
-- (ARCHITECTURE.md §4, §6; PRD §6.3, §7, §9.1).
--
-- LOCKED-DECISION invariants the DB enforces here (PRD §19/§6.4, CLAUDE.md §12):
--   * ONE ACCOUNT PER PERSON: app_user.phone UNIQUE (signup) + profile.id_hash UNIQUE
--     blind-index dedup at verification (D11/D15). id_no itself is stored ENCRYPTED
--     (randomised ciphertext) so it CANNOT enforce uniqueness or be searched — the
--     deterministic id_hash is the dedup key, by design (PRD §18).
--   * MULTI-LOCATION, ONE PRIMARY + ONE ELECTORAL: two partial unique indexes on
--     profile_location enforce at most one is_primary and one is_electoral per profile
--     (JPA cannot express partial uniqueness — the DB owns these). ProfileLocation is
--     PRIVATE PII: never indexed for public search, never in a public DTO (PRD §9.0, §22.1).
--   * ADDITIVE, SCOPED ROLES: role_assignment is a join carrying scope
--     (areaIds[]/categoryIds[]/constituencyId); a user holds many assignments (§6.4),
--     never a single mutually-exclusive userType.
--
-- Type mapping contract (entity -> column) — same rules as V2:
--   Long->bigint identity, UUID->uuid, Long version->bigint not null,
--   Instant->timestamp with time zone, LocalDate->date, boolean->boolean not null,
--   @Enumerated(STRING)->varchar(<declared length>), @Convert(Encrypted)->varchar.
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- app_user — the authentication subject; one account per phone (D11/D15).
-- -----------------------------------------------------------------------------
CREATE TABLE app_user (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    phone           VARCHAR(20)  NOT NULL,                 -- E.164; the unique account key
    email           VARCHAR(254),                          -- optional, NOT unique
    handle          VARCHAR(64),                           -- display only; never an authz key
    password_hash   VARCHAR(100),                          -- BCrypt; NULL for OTP-only accounts
    status          VARCHAR(16)  NOT NULL,                 -- UserStatus: PENDING/ACTIVE/SUSPENDED/DISABLED
    trust_tier      VARCHAR(4)   NOT NULL,                 -- TrustTier: T0..T3 (cached; re-checked live)
    mfa_enabled     BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_app_user_public_id UNIQUE (public_id),
    CONSTRAINT uq_app_user_phone     UNIQUE (phone),       -- HARD one-account-per-phone guarantee (D11/D15)
    -- Enum domain guards (mirror Hibernate's generated CHECKs for UserStatus / TrustTier).
    CONSTRAINT ck_app_user_status     CHECK (status     IN ('PENDING','ACTIVE','SUSPENDED','DISABLED')),
    CONSTRAINT ck_app_user_trust_tier CHECK (trust_tier IN ('T0','T1','T2','T3'))
);

-- Entity @Index set. ux_app_user_phone is satisfied by uq_app_user_phone above.
CREATE INDEX ix_app_user_email  ON app_user (email);
CREATE INDEX ix_app_user_status ON app_user (status);

COMMENT ON TABLE  app_user            IS 'Platform account = authentication subject; exactly one per person (phone-unique + ID dedup). Roles are additive (§6.4).';
COMMENT ON COLUMN app_user.phone      IS 'E.164 mobile number; UNIQUE — the hard one-account-per-phone integrity guarantee (D11/D15).';
COMMENT ON COLUMN app_user.public_id  IS 'Public UUID = JWT subject and URL id (never the mutable phone/handle).';
COMMENT ON COLUMN app_user.trust_tier IS 'Cached TrustTier T0..T3; a JWT hint only — high-stakes actions re-resolve the live tier server-side (PRD §17/§18).';
COMMENT ON COLUMN app_user.password_hash IS 'BCrypt hash only, never plaintext; NULL for OTP-only accounts (ADR-0007).';


-- -----------------------------------------------------------------------------
-- profile — the human/organisation behind an account (1:1); holds encrypted ID + dedup hash.
-- -----------------------------------------------------------------------------
CREATE TABLE profile (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    user_id         BIGINT       NOT NULL,                 -- 1:1 owning account
    type            VARCHAR(16)  NOT NULL,                 -- ProfileType: PERSON/ORGANIZATION
    first_name      VARCHAR(120),
    last_name       VARCHAR(120),
    id_type         VARCHAR(16),                           -- IdType: NATIONAL/VOTER/PASSPORT (NULL if none)
    id_no           VARCHAR(512),                          -- ENCRYPTED ciphertext (EncryptedStringConverter) — never plaintext/logged (PRD §18)
    id_hash         VARCHAR(64),                            -- deterministic blind index over idType+idNo; UNIQUE = dedup key (D15)
    id_verified     BOOLEAN      NOT NULL DEFAULT FALSE,    -- gates T3
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    phone_verified  BOOLEAN      NOT NULL DEFAULT FALSE,    -- gates T1
    verified_at     TIMESTAMP WITH TIME ZONE,
    date_of_birth   DATE,
    gender          VARCHAR(16),
    nationality     VARCHAR(3),

    CONSTRAINT uq_profile_public_id UNIQUE (public_id),
    CONSTRAINT ux_profile_id_hash   UNIQUE (id_hash),       -- matches entity @UniqueConstraint; dedup without decrypting
    -- Enum domain guards (mirror Hibernate's generated CHECKs for ProfileType / IdType).
    CONSTRAINT ck_profile_type    CHECK (type    IN ('PERSON','ORGANIZATION')),
    CONSTRAINT ck_profile_id_type CHECK (id_type IS NULL OR id_type IN ('NATIONAL','VOTER','PASSPORT')),
    CONSTRAINT fk_profile_user      FOREIGN KEY (user_id) REFERENCES app_user (id)
);

-- ix_profile_user is declared UNIQUE on the entity (enforces the 1:1) — use a unique index.
CREATE UNIQUE INDEX ix_profile_user ON profile (user_id);
CREATE INDEX        ix_profile_type ON profile (type);

COMMENT ON TABLE  profile          IS 'Human/organisation identity behind an account (1:1 app_user). Carries the most sensitive PII (government ID).';
COMMENT ON COLUMN profile.id_no    IS 'Government ID number stored ENCRYPTED at rest (randomised ciphertext); decrypt only when lawful (PDPA, PRD §18). Never log/expose.';
COMMENT ON COLUMN profile.id_hash  IS 'Deterministic blind index over (id_type,id_no); UNIQUE — enforces one-person-one-account dedup WITHOUT decrypting (D15).';
COMMENT ON COLUMN profile.id_verified IS 'Government-ID verified; gates trust-tier T3.';


-- -----------------------------------------------------------------------------
-- profile_location — a profile's pinned places. PRIVATE PII. One primary + one electoral.
-- -----------------------------------------------------------------------------
CREATE TABLE profile_location (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID        NOT NULL,
    version               BIGINT      NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE,
    created_by            UUID,
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            UUID,
    deleted               BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMP WITH TIME ZONE,
    deleted_by            UUID,

    profile_id            BIGINT      NOT NULL,             -- owning profile (many per profile)
    ward_id               BIGINT      NOT NULL,             -- pinned ward (FK location, type WARD) — min pin granularity
    constituency_id       BIGINT,                           -- derived constituency at pin time (FK constituency); NULL until resolved
    association_type      VARCHAR(24) NOT NULL,             -- AssociationType: HOME_ANCESTRAL/RESIDENCE/WORK/...
    is_primary            BOOLEAN     NOT NULL DEFAULT FALSE,
    is_electoral          BOOLEAN     NOT NULL DEFAULT FALSE,
    electoral_changed_at  TIMESTAMP WITH TIME ZONE,         -- supports the electoral-change cooldown (D13)

    CONSTRAINT uq_profile_location_public_id  UNIQUE (public_id),
    -- Enum domain guard (mirror Hibernate's generated CHECK for AssociationType).
    CONSTRAINT ck_profile_location_association CHECK (association_type IN ('HOME_ANCESTRAL','RESIDENCE','WORK','FAMILY','BUSINESS','PROPERTY','INTEREST')),
    CONSTRAINT fk_profile_location_profile      FOREIGN KEY (profile_id)      REFERENCES profile (id),
    CONSTRAINT fk_profile_location_ward         FOREIGN KEY (ward_id)         REFERENCES location (id),
    CONSTRAINT fk_profile_location_constituency FOREIGN KEY (constituency_id) REFERENCES constituency (id)
);

-- Entity-declared lookup indexes.
CREATE INDEX ix_profile_location_profile      ON profile_location (profile_id);
CREATE INDEX ix_profile_location_ward         ON profile_location (ward_id);
CREATE INDEX ix_profile_location_constituency ON profile_location (constituency_id);

-- INVARIANT (DB-owned, JPA cannot express): at most ONE primary and ONE electoral per profile.
-- Scoped to live rows so a soft-deleted old primary/electoral never blocks setting a new one.
CREATE UNIQUE INDEX ux_profile_location_one_primary
    ON profile_location (profile_id)
    WHERE is_primary = TRUE AND deleted = FALSE;
CREATE UNIQUE INDEX ux_profile_location_one_electoral
    ON profile_location (profile_id)
    WHERE is_electoral = TRUE AND deleted = FALSE;

COMMENT ON TABLE  profile_location              IS 'PRIVATE PII. A profile pins many places; exactly one primary (default context) and one electoral (binding civic weight). Never in public search/DTO (PRD §9.0, §22.1).';
COMMENT ON COLUMN profile_location.ward_id      IS 'Pinned ward (FK location, type WARD) — minimum pin granularity from which both admin chain and constituency are derived (PRD §9.0).';
COMMENT ON COLUMN profile_location.is_electoral IS 'The single binding-civic-weight location; voter-ID-authoritative, change rate-limited (cooldown) and audited (D13).';
COMMENT ON COLUMN profile_location.electoral_changed_at IS 'Last electoral-flag change instant; backs the cooldown enforced in the auth/profile increment (D13).';


-- -----------------------------------------------------------------------------
-- role — the grantable role catalogue (one row per RoleName).
-- -----------------------------------------------------------------------------
CREATE TABLE role (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    name            VARCHAR(32)  NOT NULL,                 -- RoleName: CITIZEN/REPRESENTATIVE/RESPONDER_AGENT/...
    description     VARCHAR(255),

    CONSTRAINT uq_role_public_id UNIQUE (public_id),
    CONSTRAINT uq_role_name      UNIQUE (name),            -- satisfies entity ux_role_name(unique)
    -- Enum domain guard (mirror Hibernate's generated CHECK for RoleName).
    CONSTRAINT ck_role_name CHECK (name IN ('GUEST','CITIZEN','ORG_MEMBER','ORG_ADMIN','REPRESENTATIVE','RESPONDER_AGENT','RESPONDER_ADMIN','MODERATOR','ADMIN','ROOT'))
);

COMMENT ON TABLE  role      IS 'Role catalogue (reference). Roles are additive on one account via role_assignment (§6.4).';
COMMENT ON COLUMN role.name IS 'Canonical RoleName; UNIQUE. Seeded by a later reference migration so the catalogue is admin-manageable + auditable.';


-- -----------------------------------------------------------------------------
-- role_assignment — additive, scoped grant of a role to a user.
-- -----------------------------------------------------------------------------
CREATE TABLE role_assignment (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    user_id         BIGINT       NOT NULL,                 -- account holding the grant
    role_id         BIGINT       NOT NULL,                 -- granted role
    status          VARCHAR(24)  NOT NULL,                 -- RoleStatus: PENDING_VERIFICATION/ACTIVE/SUSPENDED/FORMER
    constituency_id BIGINT,                                -- single electoral scope (FK constituency); NULL = not constituency-scoped
    effective_from  TIMESTAMP WITH TIME ZONE,              -- NULL = effective on creation
    effective_to    TIMESTAMP WITH TIME ZONE,              -- NULL = open-ended

    CONSTRAINT uq_role_assignment_public_id UNIQUE (public_id),
    -- Enum domain guard (mirror Hibernate's generated CHECK for RoleStatus).
    CONSTRAINT ck_role_assignment_status CHECK (status IN ('PENDING_VERIFICATION','ACTIVE','SUSPENDED','FORMER')),
    CONSTRAINT fk_role_assignment_user         FOREIGN KEY (user_id)         REFERENCES app_user (id),
    CONSTRAINT fk_role_assignment_role         FOREIGN KEY (role_id)         REFERENCES role (id),
    CONSTRAINT fk_role_assignment_constituency FOREIGN KEY (constituency_id) REFERENCES constituency (id)
);

CREATE INDEX ix_role_assignment_user   ON role_assignment (user_id);
CREATE INDEX ix_role_assignment_role   ON role_assignment (role_id);
CREATE INDEX ix_role_assignment_status ON role_assignment (status);

COMMENT ON TABLE  role_assignment                 IS 'Scoped, additive grant of a role to a user (RBAC + attribute scope). A user holds many; never a single mutually-exclusive userType (§6.4).';
COMMENT ON COLUMN role_assignment.constituency_id IS 'Single electoral scope (e.g. an MP limited to their own constituency); real FK because it is one electoral unit.';

-- @ElementCollection side tables for the multi-valued, cross-module scope sets (public UUIDs, not FKs by design — see RoleAssignment javadoc).
CREATE TABLE role_assignment_area (
    role_assignment_id BIGINT NOT NULL,                    -- FK role_assignment.id
    area_public_id     UUID   NOT NULL,                    -- public id of a scoped Location (any level)
    CONSTRAINT pk_role_assignment_area PRIMARY KEY (role_assignment_id, area_public_id),
    CONSTRAINT fk_role_assignment_area FOREIGN KEY (role_assignment_id) REFERENCES role_assignment (id)
);
COMMENT ON TABLE role_assignment_area IS 'Area scope set: public ids of Locations a role_assignment is limited to (empty = unrestricted). Resolved via geography public API, not a cross-module FK (KISS).';

CREATE TABLE role_assignment_category (
    role_assignment_id BIGINT NOT NULL,                    -- FK role_assignment.id
    category_public_id UUID   NOT NULL,                    -- public id of a scoped issue category (reporting module)
    CONSTRAINT pk_role_assignment_category PRIMARY KEY (role_assignment_id, category_public_id),
    CONSTRAINT fk_role_assignment_category FOREIGN KEY (role_assignment_id) REFERENCES role_assignment (id)
);
COMMENT ON TABLE role_assignment_category IS 'Category scope set: public ids of issue categories a role_assignment is limited to (empty = unrestricted). Resolved via reporting public API when built.';


-- -----------------------------------------------------------------------------
-- verification_request — operator-assisted verification queue (ID / rep claim / org).
-- -----------------------------------------------------------------------------
CREATE TABLE verification_request (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL,
    version            BIGINT       NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE,
    created_by         UUID,
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         UUID,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMP WITH TIME ZONE,
    deleted_by         UUID,

    subject_user_id    BIGINT       NOT NULL,              -- account being verified
    type               VARCHAR(16)  NOT NULL,              -- VerificationType: ID/REP_CLAIM/ORG
    status             VARCHAR(16)  NOT NULL,              -- VerificationStatus: PENDING/APPROVED/REJECTED/MORE_INFO
    evidence_ref       VARCHAR(512),                       -- object-store key — NEVER the document bytes (PRD §18)
    reviewer_public_id UUID,                               -- reviewing actor publicId; NULL while unassigned
    review_note        VARCHAR(1000),
    decided_at         TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_verification_request_public_id UNIQUE (public_id),
    -- Enum domain guards (mirror Hibernate's generated CHECKs for VerificationType / VerificationStatus).
    CONSTRAINT ck_verification_type   CHECK (type   IN ('ID','REP_CLAIM','ORG')),
    CONSTRAINT ck_verification_status CHECK (status IN ('PENDING','APPROVED','REJECTED','MORE_INFO')),
    CONSTRAINT fk_verification_subject FOREIGN KEY (subject_user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_verification_subject ON verification_request (subject_user_id);
CREATE INDEX ix_verification_status  ON verification_request (status);
CREATE INDEX ix_verification_type    ON verification_request (type);

COMMENT ON TABLE  verification_request              IS 'Operator-assisted verification queue backing the IdentityVerificationProvider MVP/degradation path (EI-1/EI-2).';
COMMENT ON COLUMN verification_request.evidence_ref IS 'Object-store reference to submitted evidence; never the raw PII document — keeps PII out of the core table (PRD §18).';


-- -----------------------------------------------------------------------------
-- refresh_token — persisted HASHED refresh tokens for the rotating-refresh scheme.
-- -----------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    user_id         BIGINT       NOT NULL,                 -- owning account
    token_hash      VARCHAR(100) NOT NULL,                 -- SHA-256+ hash of the token; UNIQUE. Never the raw token (PRD §18)
    family_id       UUID         NOT NULL,                 -- rotation-chain id; reuse revokes the whole family
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    used            BOOLEAN      NOT NULL DEFAULT FALSE,    -- single-use
    revoked         BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_refresh_token_public_id UNIQUE (public_id),
    CONSTRAINT uq_refresh_token_hash      UNIQUE (token_hash),  -- satisfies entity ux_refresh_token_hash(unique)
    CONSTRAINT fk_refresh_token_user      FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_refresh_token_user   ON refresh_token (user_id);
CREATE INDEX ix_refresh_token_family ON refresh_token (family_id);

COMMENT ON TABLE  refresh_token            IS 'Persisted HASHED refresh tokens making refresh revocable; rotation in a family, reuse triggers family revocation (ADR-0007).';
COMMENT ON COLUMN refresh_token.token_hash IS 'SHA-256+ hash of the refresh token; UNIQUE. A DB compromise yields no usable tokens (PRD §18).';
