-- =============================================================================
-- V40__moderation_flag.sql  —  Citizen content flags (moderation module, M12).
--
-- Responsibility: create the `moderation_flag` table behind the JPA entity
-- `com.taarifu.moderation.domain.model.Flag` (PRD §18, US-12.1, UC-E13/H01). One row
-- per citizen-flag of a piece of content. MUST match the entity so ddl-auto=validate
-- passes (ARCHITECTURE.md §4.1, ADR-0005).
--
-- INTEGRITY invariants the DB enforces here:
--   * ANTI-BRIGADING: ux_mod_flag_flagger_subject UNIQUE (flagger_profile_id,
--     subject_type, subject_id) — one live flag per citizen per subject, so the flag
--     count that drives queue severity reflects DISTINCT flaggers (the service
--     pre-checks for a clean 409; this index is the hard backstop).
--   * CROSS-MODULE BY ID ONLY: subject_id / flagger_profile_id are UUID references to
--     other modules' aggregates (reporting/engagement/identity), NOT foreign keys —
--     the moderation module must not couple to another module's tables
--     (ARCHITECTURE.md §3.2). No FK is therefore declared on them by design.
--   * NO TOKENS ON THE FLAG PATH: flagging is a civic-core safety action; nothing
--     token-related exists on this table (integrity fence, D18, §23.5).
--
-- Type mapping contract (entity -> column):
--   Long->bigint identity, UUID->uuid, Long version->bigint not null,
--   Instant->timestamp with time zone, boolean->boolean not null,
--   @Enumerated(STRING)->varchar(<declared length>), String->varchar(<length>).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE moderation_flag (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID         NOT NULL,
    version              BIGINT       NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE,
    created_by           UUID,
    updated_at           TIMESTAMP WITH TIME ZONE,
    updated_by           UUID,
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMP WITH TIME ZONE,
    deleted_by           UUID,

    subject_type         VARCHAR(24)  NOT NULL,                -- FlagSubjectType: REPORT/COMMENT/...
    subject_id           UUID         NOT NULL,                -- public id of flagged content (cross-module ref, NOT a FK)
    flagger_profile_id   UUID         NOT NULL,                -- flagging citizen's account/profile public id (cross-module ref, NOT a FK)
    reason               VARCHAR(16)  NOT NULL,                -- FlagReason: ABUSE/SPAM/PII/HARASSMENT/MISINFORMATION/OTHER
    detail               VARCHAR(1000),                        -- optional free-text; never copied content/PII
    status               VARCHAR(16)  NOT NULL,                -- FlagStatus: OPEN/RESOLVED/DISMISSED
    moderation_item_id   UUID,                                 -- public id of the raised ModerationItem (cross-table ref by public id)

    CONSTRAINT uq_mod_flag_public_id UNIQUE (public_id),
    -- ANTI-BRIGADING: one flag per (citizen, subject). Matches entity @UniqueConstraint.
    CONSTRAINT ux_mod_flag_flagger_subject UNIQUE (flagger_profile_id, subject_type, subject_id),
    -- Enum domain guards (mirror Hibernate's generated CHECKs).
    CONSTRAINT ck_mod_flag_subject_type CHECK (subject_type IN
        ('REPORT','COMMENT','ANNOUNCEMENT','PETITION','QUESTION','PROFILE','RATING','OTHER')),
    CONSTRAINT ck_mod_flag_reason CHECK (reason IN
        ('ABUSE','SPAM','PII','HARASSMENT','MISINFORMATION','OTHER')),
    CONSTRAINT ck_mod_flag_status CHECK (status IN ('OPEN','RESOLVED','DISMISSED'))
);

-- Entity @Index set: subject lookup (close-on-resolve), flagger lookup, status filter.
CREATE INDEX ix_mod_flag_subject ON moderation_flag (subject_type, subject_id);
CREATE INDEX ix_mod_flag_flagger ON moderation_flag (flagger_profile_id);
CREATE INDEX ix_mod_flag_status  ON moderation_flag (status);

COMMENT ON TABLE  moderation_flag                    IS 'One citizen-flag of a piece of content (US-12.1). Subject/flagger referenced by public id across modules (no FK, ARCHITECTURE §3.2).';
COMMENT ON COLUMN moderation_flag.subject_id         IS 'Public id of the flagged content in its owning module — cross-module reference, NEVER a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN moderation_flag.flagger_profile_id IS 'Flagging citizen account public id (JWT-subject grain) — cross-module reference, never a FK.';
COMMENT ON COLUMN moderation_flag.detail             IS 'Optional free-text flag detail; never copied content/PII (moderators open the subject to see it).';
