-- =============================================================================
-- V41__moderation_item_action.sql  —  Moderation queue + append-only action log (M12).
--
-- Responsibility: create `moderation_item` (the prioritised moderator queue) and
-- `moderation_action` (the IMMUTABLE, append-only decision log) behind the JPA entities
-- `com.taarifu.moderation.domain.model.ModerationItem` / `.ModerationAction`
-- (PRD §18, §25.8, US-12.2, UC-H01/H02). MUST match the entities so ddl-auto=validate
-- passes (ARCHITECTURE.md §4.1, ADR-0005).
--
-- INTEGRITY invariants the DB enforces here:
--   * ONE LIVE QUEUE ITEM PER SUBJECT: ux_mod_item_subject_open UNIQUE
--     (subject_type, subject_id) — many flags collapse into one review unit
--     (the entity @SQLRestriction hides soft-deleted rows, so at most one LIVE row).
--   * SLA BY SEVERITY (§25.8): sla_due_at is stamped from the severity's review target
--     (CRITICAL ≤4h … LOW ≤72h) so the queue is prioritised and breaches surfaced.
--   * APPEND-ONLY ACTION LOG: moderation_action is INSERT + SELECT only — a moderation
--     action is NEVER updated/deleted (a reversal is a NEW action). The grant block
--     below revokes UPDATE/DELETE from the runtime role, enforcing immutability at the
--     database (same pattern as audit_event / V5), not merely by convention (§18, §25.8).
--   * REAL FK WITHIN THE MODULE: moderation_action.item_id is a true FK to
--     moderation_item (same module — ARCHITECTURE §4.3). People (moderator/author) are
--     UUID cross-module references, never FKs.
--
-- Type mapping contract (entity -> column): as V40, plus int->integer not null.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- moderation_item — the prioritised moderator queue (one live row per subject).
-- -----------------------------------------------------------------------------
CREATE TABLE moderation_item (
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                  UUID         NOT NULL,
    version                    BIGINT       NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE,
    created_by                 UUID,
    updated_at                 TIMESTAMP WITH TIME ZONE,
    updated_by                 UUID,
    deleted                    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at                 TIMESTAMP WITH TIME ZONE,
    deleted_by                 UUID,

    subject_type               VARCHAR(24)  NOT NULL,          -- FlagSubjectType
    subject_id                 UUID         NOT NULL,          -- public id of content under review (cross-module ref)
    subject_author_profile_id  UUID,                           -- author account public id (JWT-subject grain) for the D16 self-action guard; NULL = author-less
    severity                   VARCHAR(16)  NOT NULL,          -- ModerationSeverity: LOW/MEDIUM/HIGH/CRITICAL
    status                     VARCHAR(16)  NOT NULL,          -- ModerationItemStatus: PENDING/IN_REVIEW/ACTIONED/DISMISSED
    flag_count                 INTEGER      NOT NULL,          -- distinct flaggers (queue ordering / escalation)
    assigned_moderator_id      UUID,                           -- claiming moderator account public id; NULL while PENDING
    sla_due_at                 TIMESTAMP WITH TIME ZONE NOT NULL,  -- §25.8 review deadline = created + severity target
    closed_at                  TIMESTAMP WITH TIME ZONE,       -- terminal-close instant; NULL until ACTIONED/DISMISSED

    CONSTRAINT uq_mod_item_public_id UNIQUE (public_id),
    -- ONE LIVE QUEUE ITEM PER SUBJECT. Matches entity @UniqueConstraint.
    CONSTRAINT ux_mod_item_subject_open UNIQUE (subject_type, subject_id),
    CONSTRAINT ck_mod_item_subject_type CHECK (subject_type IN
        ('REPORT','COMMENT','ANNOUNCEMENT','PETITION','QUESTION','PROFILE','RATING','OTHER')),
    CONSTRAINT ck_mod_item_severity CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT ck_mod_item_status   CHECK (status   IN ('PENDING','IN_REVIEW','ACTIONED','DISMISSED'))
);

-- Entity @Index set: queue ordering, assignee lookup, SLA sweep, author lookup (D16).
CREATE INDEX ix_mod_item_status_sev ON moderation_item (status, severity);
CREATE INDEX ix_mod_item_assignee   ON moderation_item (assigned_moderator_id);
CREATE INDEX ix_mod_item_sla        ON moderation_item (sla_due_at);
CREATE INDEX ix_mod_item_author     ON moderation_item (subject_author_profile_id);

COMMENT ON TABLE  moderation_item                            IS 'Prioritised moderator queue; one LIVE row per (subject_type, subject_id) — many flags collapse here (UC-H01).';
COMMENT ON COLUMN moderation_item.subject_author_profile_id  IS 'Author account public id (JWT-subject grain) used by the D16 self-action guard; NULL when the subject has no surfaced author. Backfilled by wiring from the owning module.';
COMMENT ON COLUMN moderation_item.sla_due_at                 IS 'Review-SLA deadline = created + ModerationSeverity.reviewTarget (§25.8: CRITICAL ≤4h, HIGH/MEDIUM ≤24h, LOW ≤72h).';


-- -----------------------------------------------------------------------------
-- moderation_action — APPEND-ONLY log of moderator decisions (UPDATE/DELETE revoked).
-- -----------------------------------------------------------------------------
CREATE TABLE moderation_action (
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                  UUID         NOT NULL,
    version                    BIGINT       NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE,
    created_by                 UUID,
    updated_at                 TIMESTAMP WITH TIME ZONE,
    updated_by                 UUID,
    deleted                    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at                 TIMESTAMP WITH TIME ZONE,
    deleted_by                 UUID,

    item_id                    BIGINT       NOT NULL,          -- FK moderation_item.id (real FK, same module)
    type                       VARCHAR(16)  NOT NULL,          -- ModerationActionType: APPROVE/HIDE/REMOVE/WARN/SUSPEND/VERIFY_REQUEST
    moderator_profile_id       UUID         NOT NULL,          -- acting moderator account public id (cross-module ref)
    subject_author_profile_id  UUID,                           -- frozen author account public id at action time (for appeal checks); NULL = none
    reason_code                VARCHAR(64)  NOT NULL,          -- machine reason; never PII/content
    note                       VARCHAR(1000),                  -- optional operator note; never content
    taken_at                   TIMESTAMP WITH TIME ZONE NOT NULL,  -- append-only decision instant

    CONSTRAINT uq_mod_action_public_id UNIQUE (public_id),
    CONSTRAINT ck_mod_action_type CHECK (type IN
        ('APPROVE','HIDE','REMOVE','WARN','SUSPEND','VERIFY_REQUEST')),
    CONSTRAINT fk_mod_action_item FOREIGN KEY (item_id) REFERENCES moderation_item (id)
);

-- Entity @Index set: item history, moderator activity, (type, taken_at) reporting.
CREATE INDEX ix_mod_action_item      ON moderation_action (item_id);
CREATE INDEX ix_mod_action_moderator ON moderation_action (moderator_profile_id);
CREATE INDEX ix_mod_action_type_time ON moderation_action (type, taken_at);

COMMENT ON TABLE  moderation_action      IS 'APPEND-ONLY log of moderator decisions. INSERT+SELECT only (UPDATE/DELETE revoked below). A reversal is a NEW action — history is never mutated (§18, §25.8).';
COMMENT ON COLUMN moderation_action.subject_author_profile_id IS 'Author account public id frozen at action time so an appeal can verify the appellant + appeal independence without re-reading the (mutable) item.';
COMMENT ON COLUMN moderation_action.reason_code IS 'Machine reason for the decision (e.g. RULE_HARASSMENT); never PII/content.';


-- -----------------------------------------------------------------------------
-- APPEND-ONLY ENFORCEMENT — revoke UPDATE/DELETE on moderation_action from the
-- runtime DB role (same pattern + rationale as V5 audit_event). The application is
-- granted INSERT + SELECT only; the schema owner keeps full rights for later
-- forward migrations. Guarded by a DO block so it degrades to a NOTICE when the
-- least-privileged role is absent (e.g. local dev connecting as the owner) — the
-- invariant is then carried by the INSERT-only entity mapping (type/note/taken_at all
-- updatable=false) until the dedicated role exists.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'taarifu_app') THEN
        EXECUTE 'GRANT INSERT, SELECT ON moderation_action TO taarifu_app';
        EXECUTE 'REVOKE UPDATE, DELETE, TRUNCATE ON moderation_action FROM taarifu_app';
        RAISE NOTICE 'moderation_action: granted INSERT+SELECT, revoked UPDATE/DELETE/TRUNCATE from role taarifu_app (append-only, §25.8).';
    ELSE
        RAISE NOTICE 'moderation_action: runtime role "taarifu_app" not found; append-only is carried by the entity mapping only. Create the least-privileged role and re-apply grants in your environment.';
    END IF;
END
$$;
