-- =============================================================================
-- V42__moderation_appeal.sql  —  Appeals against moderation actions (M12, §25.8).
--
-- Responsibility: create `moderation_appeal` behind the JPA entity
-- `com.taarifu.moderation.domain.model.Appeal` (PRD §25.8, UC-H03). One appeal per
-- moderation action, decided by an INDEPENDENT moderator. MUST match the entity so
-- ddl-auto=validate passes (ARCHITECTURE.md §4.1, ADR-0005).
--
-- INTEGRITY invariants (the appeal-independence guarantees, §25.8 / Appendix F ᵉ):
--   * APPEAL INDEPENDENCE (D16): handled_by_moderator_id MUST differ from the appealed
--     action's moderator_profile_id — a moderator may never adjudicate an appeal of
--     their OWN action. Enforced in AppealService (CONFLICT_OF_INTEREST + audit) and
--     re-asserted in Appeal.decide() (defence-in-depth). It is a cross-row rule, so it
--     is NOT a single-column DB CHECK; the DB owns the structural rules below.
--   * ONE LIVE APPEAL PER ACTION: ux_mod_appeal_action UNIQUE (action_id) — a decision
--     is final unless escalated (the service pre-checks for a clean 409; this is the
--     hard backstop). Matches entity @UniqueConstraint.
--   * AFFECTED-PARTY-ONLY: only the actioned content's author may appeal — enforced in
--     the service against the action's frozen subject_author_profile_id.
--   * REAL FK WITHIN THE MODULE: action_id is a true FK to moderation_action (same
--     module — ARCHITECTURE §4.3). Appellant/handler are UUID cross-module references.
--
-- Type mapping contract (entity -> column): as V40/V41.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


CREATE TABLE moderation_appeal (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL,
    version                  BIGINT       NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE,
    created_by               UUID,
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               UUID,
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    deleted_by               UUID,

    action_id                BIGINT       NOT NULL,            -- FK moderation_action.id (real FK, same module)
    appellant_profile_id     UUID         NOT NULL,            -- affected author account public id (cross-module ref)
    grounds                  VARCHAR(2000),                    -- appellant's grounds; never content/PII
    status                   VARCHAR(16)  NOT NULL,            -- AppealStatus: OPEN/UPHELD/OVERTURNED
    handled_by_moderator_id  UUID,                             -- deciding (INDEPENDENT) moderator account public id; NULL while OPEN
    decision_note            VARCHAR(1000),                    -- decision rationale; never PII/content
    decided_at               TIMESTAMP WITH TIME ZONE,         -- decision instant; NULL while OPEN

    CONSTRAINT uq_mod_appeal_public_id UNIQUE (public_id),
    -- ONE LIVE APPEAL PER ACTION. Matches entity @UniqueConstraint.
    CONSTRAINT ux_mod_appeal_action UNIQUE (action_id),
    CONSTRAINT ck_mod_appeal_status CHECK (status IN ('OPEN','UPHELD','OVERTURNED')),
    CONSTRAINT fk_mod_appeal_action FOREIGN KEY (action_id) REFERENCES moderation_action (id)
);

-- Entity @Index set: appellant lookup, status queue, handler activity.
CREATE INDEX ix_mod_appeal_appellant ON moderation_appeal (appellant_profile_id);
CREATE INDEX ix_mod_appeal_status    ON moderation_appeal (status);
CREATE INDEX ix_mod_appeal_handler   ON moderation_appeal (handled_by_moderator_id);

COMMENT ON TABLE  moderation_appeal                         IS 'Appeal against a moderation action, decided by an INDEPENDENT moderator (§25.8 footnote ᵉ). One live appeal per action.';
COMMENT ON COLUMN moderation_appeal.appellant_profile_id    IS 'Affected content-author account public id (JWT-subject grain) — only the affected party may appeal (verified server-side).';
COMMENT ON COLUMN moderation_appeal.handled_by_moderator_id IS 'Deciding moderator account public id; MUST differ from the appealed action moderator (appeal independence, D16/§25.8) — enforced in the service + entity.';
