-- =============================================================================
-- V43__accountability_contribution.sql  —  Representative contributions (accountability, M6).
--
-- Responsibility: create representative_contribution + its attachment side table behind
-- com.taarifu.accountability.domain.model.RepresentativeContribution (PRD §10 Epic M6,
-- US-6.1; EI-11). MUST match the entity so ddl-auto=validate passes (ADR-0005).
--
-- CURATED AUTHORSHIP (D-Q4): rows are created by ROLE_ADMIN / authorised authors (curator
-- tooling), never citizens. Taarifu is NOT the source of truth — every row carries
-- provenance via source_url and is shown attributably (EI-11).
--
-- MODULE ISOLATION: representative_id is the PUBLIC UUID of a representative that lives in
-- the institutions module — referenced by id only, NOT a foreign key (this module must not
-- couple to institutions' tables). Resolved via institutions' public API at wiring.
--
-- attachment_refs are OBJECT-STORE KEYS, never bytes (PRD §18, EI-8).
--
-- Type mapping contract (entity -> column):
--   Long->bigint identity, UUID->uuid, Long version->bigint not null,
--   Instant->timestamp with time zone, LocalDate->date, boolean->boolean not null,
--   @Enumerated(STRING)->varchar(<declared length>), String->varchar(<length>).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- representative_contribution — one curated contribution record (speech/motion/bill/...).
-- -----------------------------------------------------------------------------
CREATE TABLE representative_contribution (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID         NOT NULL,
    version             BIGINT       NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    representative_id   UUID         NOT NULL,               -- public id (institutions module); NOT an FK by design
    type                VARCHAR(16)  NOT NULL,               -- ContributionType
    title               VARCHAR(280) NOT NULL,
    summary             VARCHAR(4000),
    occurred_on         DATE         NOT NULL,               -- House sitting date
    parliament_session  VARCHAR(120),
    source_url          VARCHAR(1000),                       -- provenance (Hansard/official)

    CONSTRAINT uq_representative_contribution_public_id UNIQUE (public_id),
    -- Enum domain guard (mirror Hibernate's generated CHECK for ContributionType).
    CONSTRAINT ck_contribution_type CHECK (type IN ('SPEECH','MOTION','BILL','QUESTION','VOTE','COMMITTEE'))
);

-- Entity @Index set.
CREATE INDEX ix_contribution_representative ON representative_contribution (representative_id);
CREATE INDEX ix_contribution_type           ON representative_contribution (type);
CREATE INDEX ix_contribution_date           ON representative_contribution (occurred_on);

COMMENT ON TABLE  representative_contribution                  IS 'Curated representative contribution (M6, US-6.1). Created by ROLE_ADMIN/authorised authors (D-Q4); citizens read-only. Carries provenance (source_url) — Taarifu is not the source of truth (EI-11).';
COMMENT ON COLUMN representative_contribution.representative_id IS 'PUBLIC UUID of a representative (institutions module); referenced by id, never an FK (module isolation).';
COMMENT ON COLUMN representative_contribution.source_url        IS 'Provenance URL (Hansard/official); accountability records must be attributable (EI-11).';


-- -----------------------------------------------------------------------------
-- contribution_attachment — @ElementCollection of object-store references (never bytes).
-- -----------------------------------------------------------------------------
CREATE TABLE contribution_attachment (
    contribution_id BIGINT       NOT NULL,                   -- FK representative_contribution.id
    attachment_ref  VARCHAR(512) NOT NULL,                   -- object-store key (signed-URL/virus-scan hook)
    CONSTRAINT fk_contribution_attachment FOREIGN KEY (contribution_id)
        REFERENCES representative_contribution (id)
);
CREATE INDEX ix_contribution_attachment ON contribution_attachment (contribution_id);

COMMENT ON TABLE  contribution_attachment            IS 'Object-store REFERENCES for a contribution''s supporting documents — never the bytes (PRD §18, EI-8).';
COMMENT ON COLUMN contribution_attachment.attachment_ref IS 'Object-store key resolved via signed URL with virus-scan-on-upload; never inline document content.';
