-- =============================================================================
-- V44__accountability_attendance.sql  —  Representative attendance (accountability, M6).
--
-- Responsibility: create attendance behind com.taarifu.accountability.domain.model.Attendance
-- (PRD §10 Epic M6, US-6.1; EI-11). MUST match the entity so ddl-auto=validate passes.
--
-- CURATED AUTHORSHIP (D-Q4): created by ROLE_ADMIN / authorised authors from official records.
--
-- MODULE ISOLATION: representative_id is the PUBLIC UUID of a representative (institutions
-- module) — referenced by id only, NOT a foreign key.
--
-- INVARIANT: exactly ONE authoritative attendance row per (representative, session) — a rep is
-- either present or absent for a sitting. The unique constraint makes a re-import update rather
-- than duplicate and keeps the present/total aggregate correct.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- attendance — one present/absent row per (representative, session).
-- -----------------------------------------------------------------------------
CREATE TABLE attendance (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL,
    version           BIGINT       NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    representative_id UUID         NOT NULL,                 -- public id (institutions module); NOT an FK by design
    session_ref       VARCHAR(120) NOT NULL,                -- session/sitting reference
    present           BOOLEAN      NOT NULL,

    CONSTRAINT uq_attendance_public_id UNIQUE (public_id),
    -- One authoritative row per (representative, session) — matches entity @UniqueConstraint.
    CONSTRAINT ux_attendance_rep_session UNIQUE (representative_id, session_ref)
);

-- Entity @Index set (the rep+session lookup is served by ux_attendance_rep_session above).
CREATE INDEX ix_attendance_representative ON attendance (representative_id);

COMMENT ON TABLE  attendance                   IS 'Per-session attendance for a representative (M6, US-6.1). Curated by ROLE_ADMIN (D-Q4). One authoritative row per (rep, session).';
COMMENT ON COLUMN attendance.representative_id  IS 'PUBLIC UUID of a representative (institutions module); referenced by id, never an FK (module isolation).';
COMMENT ON COLUMN attendance.session_ref        IS 'Stable session/sitting reference; part of the one-row-per-session uniqueness key.';
