-- =============================================================================
-- V45__accountability_promise.sql  —  Representative promises (accountability, M6).
--
-- Responsibility: create promise + its linked-project side table behind
-- com.taarifu.accountability.domain.model.Promise (PRD §10 Epic M6, US-6.3). MUST match the
-- entity so ddl-auto=validate passes.
--
-- CURATED AUTHORSHIP (D-Q4): created/status-advanced by ROLE_ADMIN / authorised authors with
-- evidence. A move to KEPT/BROKEN is an authored, evidence-backed judgement (neutrality requires
-- provenance — election-period neutrality, PRD §10).
--
-- MODULE ISOLATION: representative_id (institutions) and linked project ids (projects module) are
-- PUBLIC UUIDs referenced by id only, NOT foreign keys. evidence_ref is an OBJECT-STORE KEY,
-- never bytes (PRD §18).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- promise — a tracked public commitment by a representative.
-- -----------------------------------------------------------------------------
CREATE TABLE promise (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID          NOT NULL,
    version           BIGINT        NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    created_by        UUID,
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        UUID,
    deleted           BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        UUID,

    representative_id UUID          NOT NULL,                -- public id (institutions module); NOT an FK by design
    text              VARCHAR(2000) NOT NULL,
    made_at           DATE          NOT NULL,
    status            VARCHAR(16)   NOT NULL,                -- PromiseStatus
    evidence_ref      VARCHAR(512),                          -- object-store key; never bytes

    CONSTRAINT uq_promise_public_id UNIQUE (public_id),
    -- Enum domain guard (mirror Hibernate's generated CHECK for PromiseStatus).
    CONSTRAINT ck_promise_status CHECK (status IN ('MADE','IN_PROGRESS','KEPT','BROKEN'))
);

-- Entity @Index set.
CREATE INDEX ix_promise_representative ON promise (representative_id);
CREATE INDEX ix_promise_status         ON promise (status);

COMMENT ON TABLE  promise                   IS 'Tracked public commitment by a representative (M6, US-6.3). Curated by ROLE_ADMIN (D-Q4); status moves are evidence-backed.';
COMMENT ON COLUMN promise.representative_id  IS 'PUBLIC UUID of a representative (institutions module); referenced by id, never an FK (module isolation).';
COMMENT ON COLUMN promise.evidence_ref       IS 'Object-store key for supporting evidence; never inline content (PRD §18).';


-- -----------------------------------------------------------------------------
-- promise_project — @ElementCollection of linked project public ids (projects module).
-- A Set<UUID> → composite PK (no duplicate link per promise). NOT an FK by design.
-- -----------------------------------------------------------------------------
CREATE TABLE promise_project (
    promise_id        BIGINT NOT NULL,                       -- FK promise.id
    project_public_id UUID   NOT NULL,                       -- public id of a linked project (projects module)
    CONSTRAINT pk_promise_project PRIMARY KEY (promise_id, project_public_id),
    CONSTRAINT fk_promise_project FOREIGN KEY (promise_id) REFERENCES promise (id)
);

COMMENT ON TABLE  promise_project                  IS 'Linked project public ids for a promise (empty = none). Resolved via the projects module API; not a cross-module FK by design (module isolation).';
COMMENT ON COLUMN promise_project.project_public_id IS 'PUBLIC UUID of a project (projects module); referenced by id, never an FK.';
