-- =============================================================================
-- V46__accountability_rating.sql  —  Binding representative/office/project ratings (M6).
--
-- Responsibility: create rating behind com.taarifu.accountability.domain.model.Rating
-- (PRD §10 Epic M6, US-6.2; §23 civic-integrity fence; D13/D16/D18). MUST match the entity so
-- ddl-auto=validate passes.
--
-- THE CIVIC-INTEGRITY FENCE — invariants the DB enforces here (D16/D18, §23):
--   * ONE PER PERSON: ux_rating_one_per_rater_subject_period UNIQUE
--     (subject_type, subject_id, rater_profile_id, period) — one person, one rating per period,
--     REGARDLESS of any token balance. A second submit is a hard 409 (matches entity
--     @UniqueConstraint). This is the arithmetic of "wealth cannot buy democratic weight".
--   * SCORE DOMAIN: ck_rating_score CHECK (score BETWEEN 1 AND 5) — bounds the aggregate.
--   * NO TOKEN COLUMN: there is deliberately NO token/balance/cost column on this table. A token
--     balance must never appear anywhere on a binding action's path (§23 fence). The aggregate
--     score is computed from these append-only rows only — never stored on the subject.
--
-- Tier (T3) and no-self-action are enforced in the application layer (@RequiresTier live-resolved +
-- ScopeGuard.isNotSelf); electoral scope is the documented // TODO(wiring) (D13).
--
-- MODULE ISOLATION: subject_id (institutions/projects) and rater_profile_id (identity) are PUBLIC
-- UUIDs referenced by id only, NOT foreign keys.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- rating — one citizen's binding score for a subject in a period.
-- -----------------------------------------------------------------------------
CREATE TABLE rating (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID          NOT NULL,
    version          BIGINT        NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE,
    created_by       UUID,
    updated_at       TIMESTAMP WITH TIME ZONE,
    updated_by       UUID,
    deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP WITH TIME ZONE,
    deleted_by       UUID,

    subject_type     VARCHAR(16)   NOT NULL,                 -- RatingSubjectType
    subject_id       UUID          NOT NULL,                 -- public id (institutions/projects); NOT an FK by design
    rater_profile_id UUID          NOT NULL,                 -- public id of the rater (identity); from the security context, never the body
    score            INTEGER       NOT NULL,                 -- 1..5
    comment          VARCHAR(2000),
    period           VARCHAR(16)   NOT NULL,                 -- e.g. 2026-Q2

    CONSTRAINT uq_rating_public_id UNIQUE (public_id),
    -- ONE rating per (rater, subject, period) — the one-per-person integrity invariant (D16, §23).
    CONSTRAINT ux_rating_one_per_rater_subject_period
        UNIQUE (subject_type, subject_id, rater_profile_id, period),
    -- Enum domain guard (mirror Hibernate's generated CHECK for RatingSubjectType).
    CONSTRAINT ck_rating_subject_type CHECK (subject_type IN ('REPRESENTATIVE','OFFICE','PROJECT')),
    -- Score domain guard — bounds the computed aggregate.
    CONSTRAINT ck_rating_score CHECK (score BETWEEN 1 AND 5)
);

-- Entity @Index set (subject lookup, rater lookup, period).
CREATE INDEX ix_rating_subject ON rating (subject_type, subject_id);
CREATE INDEX ix_rating_rater   ON rating (rater_profile_id);
CREATE INDEX ix_rating_period  ON rating (period);

COMMENT ON TABLE  rating                  IS 'Binding one-per-person rating (M6, US-6.2; §23 fence). T3 + no-self enforced in app; one-per-(rater,subject,period) + score 1..5 enforced here. NO token column — wealth cannot buy democratic weight (D18).';
COMMENT ON COLUMN rating.subject_id        IS 'PUBLIC UUID of the rated subject (institutions/projects); referenced by id, never an FK (module isolation).';
COMMENT ON COLUMN rating.rater_profile_id  IS 'PUBLIC UUID of the rater (identity); taken from the security context, never the request body — a caller can never rate as someone else.';
COMMENT ON COLUMN rating.period            IS 'Rating period (e.g. 2026-Q2); third axis of the one-per-person uniqueness key.';
