-- =============================================================================
-- V47__media.sql  —  Media & Attachments (media module, PRD §21 EI-8, §18).
--
-- Responsibility: create the single `media_object` table behind the media domain
-- model — the durable index for binaries held in S3-compatible object storage,
-- and the quarantine-then-serve scan-state machine that decides servability.
-- This MUST match the JPA entity exactly so Hibernate ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1, PRD §21 EI-8).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * The BYTES live in object storage; this row is the index + access-control
--     anchor + scan-state machine. Clients transfer bytes directly via pre-signed
--     URLs (never through the app) — essential for low-bandwidth, national scale
--     (PRD §15).
--   * scan_status is the load-bearing integrity column (EI-8): only CLEAN is ever
--     served. PENDING/INFECTED/FAILED fail safe — the upload is accepted but
--     delivery is deferred/blocked, so unsafe or unscanned media never reaches a
--     citizen's device. A CHECK constraint mirrors the ScanStatus enum (defense in
--     depth: the DB rejects any value outside the enum).
--   * owner_type + owner_id reference the HOST resource (Report/Profile/etc.) BY ID
--     only — NOT a real FK — because the host lives in another feature module this
--     module must not couple to (ARCHITECTURE.md §3.2). The host module owns
--     ownership/visibility checks. This is a deliberate, documented exception to
--     the "real FKs everywhere" rule, forced by the module boundary.
--   * object_key is the server-generated, collision-free, path-traversal-safe
--     storage key (quarantine/yyyy/MM/<uuid>); UNIQUE so a scan callback resolves
--     exactly one row. The original client filename is retained for display only,
--     never used to build a path.
--   * exif_stripped records the EXIF/geo-strip privacy pass (EI-8, §18): photos
--     embed GPS; serving them would leak a reporter's exact location even though
--     the Report's incident geo is captured/access-controlled separately. The flag
--     is the seam proving the strip ran before serve.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id              -> bigint identity PK
--   UUID public_id       -> uuid not null unique
--   Long version         -> bigint not null
--   Instant created_at   -> timestamp with time zone (Hibernate 6 maps Instant -> TIMESTAMP_UTC)
--   UUID *_by / owner_id / uploaded_by_profile_id -> uuid
--   boolean deleted/exif_stripped -> boolean not null
--   String @Enumerated(STRING) scan_status        -> varchar(16)
--   String columns       -> varchar(<declared length>)
--   Long size_bytes      -> bigint
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- media_object — one uploaded binary held behind the quarantine-then-serve flow.
-- -----------------------------------------------------------------------------
CREATE TABLE media_object (
    -- BaseEntity (ARCHITECTURE.md §4.2): internal PK + public UUID + audit + soft-delete + version.
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID         NOT NULL,
    version                 BIGINT       NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE,
    created_by              UUID,
    updated_at              TIMESTAMP WITH TIME ZONE,
    updated_by              UUID,
    deleted                 BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP WITH TIME ZONE,
    deleted_by              UUID,

    -- Domain columns (MediaObject.java).
    owner_type              VARCHAR(48)  NOT NULL,                 -- host discriminator (REPORT, PROFILE_AVATAR, ...)
    owner_id                UUID         NOT NULL,                 -- host resource public id (by-id ref; NOT a FK — boundary)
    object_key              VARCHAR(512) NOT NULL,                 -- server-generated storage key (quarantine/yyyy/MM/<uuid>)
    original_filename       VARCHAR(255),                         -- client display name; never used as a path
    content_type            VARCHAR(128),                         -- declared MIME type
    size_bytes              BIGINT,                               -- declared size for quota/max-size
    scan_status             VARCHAR(16)  NOT NULL DEFAULT 'PENDING', -- EI-8 state machine; only CLEAN is servable
    uploaded_by_profile_id  UUID,                                 -- uploader profile public id (by-id ref)
    exif_stripped           BOOLEAN      NOT NULL DEFAULT FALSE,  -- EXIF/geo-strip privacy pass done? (EI-8, §18)

    CONSTRAINT uq_media_object_public_id  UNIQUE (public_id),
    CONSTRAINT uq_media_object_object_key UNIQUE (object_key),
    -- Enum domain guard mirrors Hibernate's generated CHECK for the @Enumerated(STRING) column.
    CONSTRAINT ck_media_object_scan_status CHECK (scan_status IN ('PENDING','CLEAN','INFECTED','FAILED'))
);

-- Indexes mirror the entity @Index set (names kept identical to avoid drift).
-- Hosts list their attachments by (owner_type, owner_id).
CREATE INDEX ix_media_object_owner       ON media_object (owner_type, owner_id);
-- The scan/promote worker and ops dashboards filter by scan state.
CREATE INDEX ix_media_object_scan_status ON media_object (scan_status);
-- uq_media_object_object_key already provides the unique index the entity declares as
-- ix_media_object_key(unique); no separate index needed.

COMMENT ON TABLE  media_object                        IS 'Index/access-anchor/scan-state for one binary in object storage; bytes transfer via pre-signed URLs (PRD §21 EI-8).';
COMMENT ON COLUMN media_object.public_id              IS 'Public, non-enumerable UUID exposed in URLs/DTOs (PRD §17); internal id never leaves the backend.';
COMMENT ON COLUMN media_object.owner_type             IS 'Host-resource discriminator (REPORT, PROFILE_AVATAR, VERIFICATION_EVIDENCE, ANNOUNCEMENT, ...).';
COMMENT ON COLUMN media_object.owner_id               IS 'Host resource public id; referenced BY ID only (host lives in another module — ARCHITECTURE.md §3.2), so deliberately NOT a real FK.';
COMMENT ON COLUMN media_object.object_key             IS 'Server-generated unique storage key (quarantine/yyyy/MM/<uuid>); collision-free, path-traversal-safe; resolves a scan callback to one row.';
COMMENT ON COLUMN media_object.original_filename      IS 'Client-supplied display filename; retained for display/download only, never used to build a storage path.';
COMMENT ON COLUMN media_object.scan_status            IS 'EI-8 quarantine-then-serve state: PENDING(initial)|CLEAN(servable)|INFECTED(never served)|FAILED(scan errored, fail-safe).';
COMMENT ON COLUMN media_object.uploaded_by_profile_id IS 'Uploader profile public id (by-id ref to identity module); set from the authenticated principal, not the request body.';
COMMENT ON COLUMN media_object.exif_stripped          IS 'TRUE once the EXIF/geo-strip privacy pass ran (EI-8, §18): photos embed GPS; never serve un-stripped images.';
