-- =============================================================================
-- V4__identity_auth.sql  —  OTP challenge store for the auth increment (identity).
--
-- Responsibility: create the `otp_challenge` table behind the JPA entity
-- `com.taarifu.identity.domain.model.OtpChallenge` (AUTH-DESIGN §3, §13.1,
-- ADR-0011). It persists the SERVER side of an OTP flow (signup / login /
-- channel-verify) so a challenge survives a process/Redis restart mid-flow and is
-- auditable; the fast anti-automation counters (send-rate, per-IP) live in Redis
-- (AuthRateLimiter), NOT here. MUST match the entity so ddl-auto=validate passes
-- (ARCHITECTURE.md §4.1, ADR-0005).
--
-- SECURITY / PDPA invariants the DB shape enforces here (PRD §18, S-4):
--   * The plaintext OTP code is NEVER stored — only `code_hash` (keyed HMAC-SHA-256
--     via CryptoPort.blindIndex). A DB read yields no usable code.
--   * The delivery target (`phone`/`email`) is stored in clear because it is
--     transient (TTL ~5 min) and already present on app_user for existing accounts,
--     but it is PII-adjacent and is NEVER logged (handled in the entity/services).
--   * `attempts`/`max_attempts`/`consumed`/`expires_at` give the DB the per-challenge
--     verify-attempt cap, single-use, and TTL fail-closed semantics (§25.1 "minutes").
--
-- Type mapping contract (entity -> column) — identical rules to V2/V3:
--   Long->bigint identity, UUID->uuid, Long version->bigint not null,
--   Instant->timestamp with time zone, int (primitive)->integer not null,
--   boolean->boolean not null, @Enumerated(STRING)->varchar(<declared length>),
--   nullable ManyToOne FK -> nullable bigint FK.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- otp_challenge — short-lived, single-use OTP challenge (PII-light; counters in Redis).
-- -----------------------------------------------------------------------------
CREATE TABLE otp_challenge (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    phone           VARCHAR(20),                            -- E.164 target for an SMS challenge; NULL for email. Never logged (S-4)
    email           VARCHAR(254),                           -- target for an email challenge; NULL for SMS. Never logged (S-4)
    purpose         VARCHAR(16)  NOT NULL,                  -- OtpPurpose: SIGNUP/LOGIN/VERIFY (binds the code to its flow)
    channel         VARCHAR(8)   NOT NULL,                  -- OtpChannel: SMS/EMAIL
    code_hash       VARCHAR(64)  NOT NULL,                  -- keyed HMAC-SHA-256 of the OTP; NEVER the plaintext (S-4, PRD §18)
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,      -- TTL ~5 min; a verify after this fails closed (§25.1)
    attempts        INTEGER      NOT NULL DEFAULT 0,         -- verify attempts so far (primitive int on the entity)
    max_attempts    INTEGER      NOT NULL DEFAULT 5,         -- cap before the challenge is burned
    consumed        BOOLEAN      NOT NULL DEFAULT FALSE,     -- single-use; a consumed challenge never re-verifies
    user_id         BIGINT,                                 -- owning account FK; NULL for signup-before-account

    CONSTRAINT uq_otp_challenge_public_id UNIQUE (public_id),
    -- Enum domain guards (mirror Hibernate's generated CHECKs for OtpPurpose / OtpChannel).
    CONSTRAINT ck_otp_challenge_purpose CHECK (purpose IN ('SIGNUP','LOGIN','VERIFY')),
    CONSTRAINT ck_otp_challenge_channel CHECK (channel IN ('SMS','EMAIL')),
    -- Integrity guard: a challenge must have at least one delivery target.
    CONSTRAINT ck_otp_challenge_target  CHECK (phone IS NOT NULL OR email IS NOT NULL),
    CONSTRAINT fk_otp_challenge_user    FOREIGN KEY (user_id) REFERENCES app_user (id)
);

-- Entity @Index set: phone lookup (request flow), expiry sweep (soft-delete stale rows), FK column.
CREATE INDEX ix_otp_challenge_phone   ON otp_challenge (phone);
CREATE INDEX ix_otp_challenge_expires ON otp_challenge (expires_at);
CREATE INDEX ix_otp_challenge_user    ON otp_challenge (user_id);

COMMENT ON TABLE  otp_challenge               IS 'Short-lived, single-use OTP challenge (signup/login/verify). Survives a Redis flush mid-flow; fast send/attempt counters live in Redis, not here (AUTH-DESIGN §3/§13.1).';
COMMENT ON COLUMN otp_challenge.code_hash     IS 'Keyed HMAC-SHA-256 of the OTP code (CryptoPort.blindIndex); NEVER the plaintext — a DB read yields no usable code (S-4, PRD §18).';
COMMENT ON COLUMN otp_challenge.phone         IS 'E.164 delivery target for an SMS challenge (NULL for email). PII-adjacent and transient (~5 min); NEVER logged (S-4).';
COMMENT ON COLUMN otp_challenge.email         IS 'Delivery target for an email challenge (NULL for SMS). PII-adjacent and transient; NEVER logged (S-4).';
COMMENT ON COLUMN otp_challenge.purpose       IS 'OtpPurpose binding the code to its flow so a SIGNUP code cannot complete a LOGIN (replay guard).';
COMMENT ON COLUMN otp_challenge.expires_at    IS 'TTL expiry (~5 min); verify after this fails closed (§25.1 "minutes"). Indexed for the stale-row soft-delete sweep.';
COMMENT ON COLUMN otp_challenge.consumed      IS 'Single-use flag; set TRUE on a successful verify so the challenge can never be replayed.';
COMMENT ON COLUMN otp_challenge.user_id       IS 'Owning account FK; NULL for signup-before-account (the phone has no app_user yet).';
