-- =============================================================================
-- V5__common_audit.sql  —  Immutable, append-only security audit store (common.audit).
--
-- Responsibility: create the `audit_event` table behind the JPA entity
-- `com.taarifu.common.audit.domain.model.AuditEvent` (AUTH-DESIGN §11, ADR-0011 §8,
-- review item L-1). One row per security-relevant decision (auth / authz / identity
-- lifecycle). MUST match the entity so ddl-auto=validate passes (ADR-0005).
--
-- WHY this table is shaped UNLIKE every other table (deliberate, not an omission):
--   * It is NOT a BaseEntity. It has NO `version`, NO `created_*`/`updated_*`, and
--     NO `deleted*` columns — an audit event is written once and NEVER updated,
--     NEVER soft-deleted. The per-row BaseEntity audit columns answer "who last
--     touched this row"; this table answers "what security event happened", which
--     must be tamper-evident and permanent (PRD §18, §25.1).
--   * APPEND-ONLY BY DESIGN: the application performs INSERT + SELECT only. There is
--     no UPDATE/DELETE path in application code, and the grant below REVOKES
--     UPDATE/DELETE from the runtime DB role so the invariant is enforced at the
--     database, not merely by convention (L-1).
--   * PRIVACY: references/hashes ONLY — never raw PII. actor/subject are publicIds
--     (UUID), the client IP is stored HASHED (`client_ip_hash`), rich detail is an
--     object-store key (`detail_ref`). No phone, idNo, OTP value, or raw token is
--     ever written here (PRD §18, PDPA).
--   * ERASURE: a verified erasure APPENDS a new IDENTITY_ERASED tombstone event;
--     history is never mutated (§25.1). The append-only grant makes that the only
--     possible mechanism.
--   * TAMPER-EVIDENCE: `prev_hash`/`entry_hash` form an optional hash-chain
--     (entry_hash = H(prev_hash || canonical(row))) so a removed/edited row breaks
--     the chain. The chain is best-effort and computed by the writer.
--
-- Type mapping contract (entity -> column):
--   Long->bigint identity, UUID->uuid, Instant->timestamp with time zone,
--   @Enumerated(STRING)->varchar(<declared length>), String->varchar(<length>).
--   No `version`/audit/soft-delete columns — the entity declares none.
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- audit_event — immutable, append-only security/authz/identity-lifecycle log.
-- -----------------------------------------------------------------------------
CREATE TABLE audit_event (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL,                -- public, non-enumerable event id
    occurred_at        TIMESTAMP WITH TIME ZONE NOT NULL,    -- server-side event instant (UTC)
    event_type         VARCHAR(64)  NOT NULL,                -- AuditEventType (catalogue §11.2)
    actor_public_id    UUID,                                 -- acting principal publicId; SYSTEM_ACTOR sentinel for system; NULL for anonymous (S-5)
    subject_public_id  UUID,                                 -- entity/account acted upon
    actor_roles        VARCHAR(255),                         -- active role names at action time (multi-hat audit, D16); never PII
    outcome            VARCHAR(16)  NOT NULL,                -- AuditOutcome: SUCCESS/FAILURE/DENIED
    reason_code        VARCHAR(64),                          -- machine reason (e.g. INVALID_CREDENTIALS, REUSE_DETECTED); never PII
    client_ip_hash     VARCHAR(64),                          -- HASHED client IP; never the raw IP (PDPA, S-5)
    correlation_id     UUID,                                 -- request/trace id joining to logs/OTel
    detail_ref         VARCHAR(512),                         -- object-store key for non-PII detail; never inline PII
    prev_hash          VARCHAR(64),                          -- previous entry's entry_hash (tamper-evident chain); NULL for the first
    entry_hash         VARCHAR(64),                          -- this entry's chain hash = H(prev_hash || canonical(row))

    CONSTRAINT uq_audit_event_public_id UNIQUE (public_id),
    -- Enum domain guards (mirror Hibernate's generated CHECKs for AuditEventType / AuditOutcome).
    CONSTRAINT ck_audit_event_type CHECK (event_type IN (
        'AUTH_OTP_REQUESTED','AUTH_OTP_VERIFIED','AUTH_OTP_FAILED','AUTH_SIGNUP_COMPLETED',
        'AUTH_LOGIN_SUCCEEDED','AUTH_LOGIN_FAILED','AUTH_LOGIN_LOCKED','AUTH_TOKEN_REFRESHED',
        'AUTH_REFRESH_REJECTED','AUTH_REFRESH_EXPIRED','AUTH_REFRESH_REUSE_DETECTED','AUTH_FAMILY_REVOKED',
        'AUTH_LOGOUT','AUTH_LOGOUT_ALL','AUTH_TIER_CHANGED','AUTH_VERIFICATION_REQUESTED',
        'AUTHZ_TIER_DENIED','AUTHZ_SCOPE_DENIED','AUTHZ_SELF_ACTION_BLOCKED','IDENTITY_ERASED')),
    CONSTRAINT ck_audit_event_outcome CHECK (outcome IN ('SUCCESS','FAILURE','DENIED'))
);

-- Entity @Index set: actor/subject lookups, (event_type, occurred_at) time-range, correlation join.
CREATE INDEX ix_audit_event_actor       ON audit_event (actor_public_id);
CREATE INDEX ix_audit_event_subject     ON audit_event (subject_public_id);
CREATE INDEX ix_audit_event_type_time   ON audit_event (event_type, occurred_at);
CREATE INDEX ix_audit_event_correlation ON audit_event (correlation_id);

COMMENT ON TABLE  audit_event                   IS 'Immutable, APPEND-ONLY security/authz/identity-lifecycle log. INSERT+SELECT only (UPDATE/DELETE revoked below). References/hashes only — never raw PII (L-1, PRD §18, §25.1).';
COMMENT ON COLUMN audit_event.event_type        IS 'AuditEventType from the §11.2 catalogue; stable machine token SOC tooling branches on.';
COMMENT ON COLUMN audit_event.actor_public_id   IS 'Acting principal publicId; SYSTEM_ACTOR sentinel for system events; NULL for anonymous — never a spoofable id (S-5).';
COMMENT ON COLUMN audit_event.client_ip_hash    IS 'HASHED client IP only — the raw IP is never persisted (PDPA, S-5).';
COMMENT ON COLUMN audit_event.detail_ref        IS 'Object-store key for non-PII detail; inline PII is NEVER written here (PRD §18).';
COMMENT ON COLUMN audit_event.entry_hash        IS 'Tamper-evidence chain hash = H(prev_hash || canonical(row)); a removed/edited row breaks the chain (best-effort, writer-computed).';


-- -----------------------------------------------------------------------------
-- APPEND-ONLY ENFORCEMENT (L-1) — revoke UPDATE/DELETE from the runtime DB role.
--
-- The application is granted INSERT + SELECT only; UPDATE/DELETE/TRUNCATE are
-- revoked so the immutability invariant is enforced by the database, not merely by
-- application convention. The migration runs as the schema owner (which retains
-- full rights to apply later forward migrations); only the LEAST-PRIVILEGED runtime
-- role loses mutation rights here.
--
-- WHY guarded by a DO block: the runtime role name is deployment-specific
-- (`taarifu_app` by convention). If the role is absent (e.g. local dev where the
-- app connects as the owner), the migration logs a NOTICE and continues rather than
-- failing — the invariant is then carried by the application's INSERT-only writer
-- (AuditEventWriter) until the dedicated role exists. Adjust the role name per env.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'taarifu_app') THEN
        EXECUTE 'GRANT INSERT, SELECT ON audit_event TO taarifu_app';
        EXECUTE 'REVOKE UPDATE, DELETE, TRUNCATE ON audit_event FROM taarifu_app';
        RAISE NOTICE 'audit_event: granted INSERT+SELECT, revoked UPDATE/DELETE/TRUNCATE from role taarifu_app (append-only, L-1).';
    ELSE
        RAISE NOTICE 'audit_event: runtime role "taarifu_app" not found; append-only is carried by the application writer only. Create the least-privileged role and re-apply grants in your environment.';
    END IF;
END
$$;
