-- =============================================================================
-- V90__admin_system_config.sql  —  Admin Console system-config surface
--                                  (admin module, M14, US-14.1, UC-H07, PRD EI-16).
--
-- Responsibility: create the two tables the admin console owns directly —
--   * app_config   — per-platform server-driven app config (min version /
--                    force-update / splash); the mobile/web client reads it at
--                    boot and enforces min-version LOCALLY (EI-16).
--   * feature_flag — server-controlled capability toggles (UC-H07).
-- Both are BaseEntity subclasses (audit + soft-delete + version) and MUST match
-- the JPA entities for ddl-auto=validate (ARCHITECTURE.md §4.1).
--
-- ISOLATION: the admin module aggregates OTHER modules' counts via published api
-- ports (ModuleStatsProvider SPI) and mutates identity via IdentityAdminPort — so
-- it owns NO user/role/reporting tables here; only its own config tables. Version
-- block V90 is the admin module's assigned range (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * app_config has at most ONE live row per platform (partial unique where not
--     deleted). Play/App Store version lines advance independently, so a force-
--     update may apply to one platform and not the other (PRD EI-16).
--   * Version gates are stored as BOTH a human string (display) and a comparable
--     *_version_code BIGINT (the build number). The client compares its own build
--     CODE against the code — store version strings are not lexically comparable
--     ("1.10.0" < "1.9.0" as text). EI-16.
--   * feature_flag.rollout_percentage is CHECK-bounded 0..100 so a malformed
--     staged-rollout can never be persisted.
--   * Neither table holds PII; both are read by the (unauthenticated) public app-
--     config endpoint so a client can boot/gate without a token (EI-16).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- app_config — per-platform min-version / force-update / splash (EI-16).
-- -----------------------------------------------------------------------------
CREATE TABLE app_config (
    id                          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                   UUID        NOT NULL,
    version                     BIGINT      NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE,
    created_by                  UUID,
    updated_at                  TIMESTAMP WITH TIME ZONE,
    updated_by                  UUID,
    deleted                     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMP WITH TIME ZONE,
    deleted_by                  UUID,

    platform                    VARCHAR(16) NOT NULL,                 -- ClientPlatform: ANDROID/IOS/WEB
    min_supported_version       VARCHAR(32) NOT NULL,                 -- human display string (e.g. "2.3.0")
    min_supported_version_code  BIGINT      NOT NULL,                 -- comparable build code; client gates on THIS
    latest_version              VARCHAR(32),                          -- human latest (soft "update available")
    latest_version_code         BIGINT,                               -- comparable latest code; NULL = no nudge
    force_update                BOOLEAN     NOT NULL DEFAULT FALSE,   -- below-min clients hard-block when TRUE
    splash_message              VARCHAR(512),                         -- optional maintenance/announcement banner
    splash_url                  VARCHAR(512),                         -- optional deep link for the banner

    CONSTRAINT uq_app_config_public_id UNIQUE (public_id),
    CONSTRAINT ck_app_config_platform  CHECK (platform IN ('ANDROID','IOS','WEB')),
    CONSTRAINT ck_app_config_min_code_nonneg CHECK (min_supported_version_code >= 0)
);

-- INVARIANT (DB-owned): at most ONE live (non-deleted) config row per platform.
CREATE UNIQUE INDEX ux_app_config_platform_live
    ON app_config (platform)
    WHERE deleted = FALSE;

COMMENT ON TABLE  app_config                             IS 'Per-platform server-driven app config: min version / force-update / splash (PRD EI-16). Read by the client at boot; min-version enforced LOCALLY so a server outage never bricks a running client.';
COMMENT ON COLUMN app_config.min_supported_version_code  IS 'Comparable minimum build code. The client compares its OWN build code against this, never the display string (store versions are not lexically comparable). EI-16.';
COMMENT ON COLUMN app_config.force_update                IS 'When TRUE, a client below min_supported_version_code must hard-block (force update) rather than receive only a soft nudge. EI-16.';


-- -----------------------------------------------------------------------------
-- feature_flag — server-controlled capability toggles (UC-H07).
-- -----------------------------------------------------------------------------
CREATE TABLE feature_flag (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID        NOT NULL,
    version             BIGINT      NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    created_by          UUID,
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          UUID,
    deleted             BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          UUID,

    flag_key            VARCHAR(96) NOT NULL,                         -- stable machine key (module-namespaced)
    description         VARCHAR(255),                                 -- human purpose
    enabled             BOOLEAN     NOT NULL DEFAULT FALSE,           -- master switch (new flag is off)
    rollout_percentage  INTEGER     NOT NULL DEFAULT 100,             -- staged rollout 0..100

    CONSTRAINT uq_feature_flag_public_id UNIQUE (public_id),
    CONSTRAINT ck_feature_flag_rollout   CHECK (rollout_percentage BETWEEN 0 AND 100)
);

-- INVARIANT (DB-owned): a flag key is unique among live (non-deleted) flags.
CREATE UNIQUE INDEX ux_feature_flag_key_live
    ON feature_flag (flag_key)
    WHERE deleted = FALSE;

COMMENT ON TABLE  feature_flag                    IS 'Server-controlled capability toggles flipped from the admin console (UC-H07). Read by clients/modules to gate a feature without a redeploy. No PII.';
COMMENT ON COLUMN feature_flag.flag_key           IS 'Stable, module-namespaced machine key (e.g. reporting.voice_note_capture). Append-only by convention; clients/modules branch on it.';
COMMENT ON COLUMN feature_flag.rollout_percentage IS 'Staged rollout 0..100 (CHECK-bounded). 100 = fully on when enabled; used to arm a flag before rolling it out by stable user hash.';
