-- =============================================================================
-- V91__analytics_event.sql  —  Append-only product-analytics fact table
--                              (analytics module, M15, PRD §3.3 / Appendix C / E).
--
-- Responsibility: create the single analytics_event table that the recording API
-- (com.taarifu.analytics.api.AnalyticsApi) appends to and the dashboard
-- aggregations (reports volume + TTFR/TTR, SLA-breach counts, the T0->T3
-- verification funnel, channel mix, engagement counts, moderation actions) group
-- over. It MUST match the JPA entity AnalyticsEvent exactly so Hibernate
-- ddl-auto=validate passes (ARCHITECTURE.md §4.1).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * APPEND-ONLY (mirrors token_transaction / audit_event): an analytics fact is
--     never updated or soft-deleted — NO version, NO updated_*, NO deleted columns.
--     A correction is a new fact, never an edit. The application is granted only
--     INSERT+SELECT (the REVOKE at the foot documents the intent). This is the
--     read model that powers dashboards; it is NOT the audit log (§18) and the two
--     never share storage or access controls (Appendix E.4 separation of duties).
--   * IDEMPOTENT: event_id is GLOBALLY UNIQUE, so a replayed/duplicated outbox
--     emission is recorded exactly once — no double-count (Appendix E.0/E.3). The
--     same outbox that drives feed/notification fan-out feeds this sink, so the
--     numbers never diverge from operational state (§16).
--   * 🔒 NO PII, EVER (Appendix E.4, binding — §18/PDPA): there is no column for a
--     name, phone/MSISDN, email, national/voter ID, free-text report/comment body,
--     photo, or precise GPS. Identity is a single pseudonymous actor_ref (a salted
--     HASH supplied by the caller — never the account UUID). Geography is truncated
--     to a ward-or-coarser public area id (geo_area_id); village/hamlet/Mtaa and raw
--     GPS are never recorded. PDPA erasure deletes the actor_ref salt mapping (held
--     in identity), orphaning these rows — it never mutates them.
--   * Dimensions are opaque PUBLIC UUIDs referenced by id only (geography/reporting)
--     — NO cross-module FK (ADR-0013 §3.2). Aggregations run over THIS table, never
--     as live cross-module reads.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id              -> bigint identity PK
--   UUID event_id        -> uuid not null unique
--   @Enumerated(STRING)  -> varchar(<declared length>)
--   Instant occurred_at  -> timestamp with time zone
--   Long latency_seconds -> bigint (nullable)
--   String actor_ref/... -> varchar(<declared length>)
--   UUID *_id dims       -> uuid (nullable)
--
-- Forward-only; never edit once applied — add a new migration.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- analytics_event — one immutable, PII-free fact per measurable occurrence.
-- Deliberately NOT a BaseEntity: no version/updated_*/deleted — never mutated.
-- -----------------------------------------------------------------------------
CREATE TABLE analytics_event (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         UUID         NOT NULL,                 -- GLOBALLY UNIQUE idempotency key (Appendix E.0)

    event_type       VARCHAR(48)  NOT NULL,                 -- AnalyticsEventType (drawn from the catalogue)
    occurred_at      TIMESTAMP WITH TIME ZONE NOT NULL,     -- when it HAPPENED (UTC); pipeline keys on this, not ingest

    actor_ref        VARCHAR(128),                          -- pseudonymous SALTED HASH; never the UUID/name/phone/ID
    geo_area_id      UUID,                                  -- ward-or-coarser area public id (cross-module; no FK)
    category_id      UUID,                                  -- issue-category public id (cross-module; no FK)
    tier             VARCHAR(8),                            -- AnalyticsTier T0..T3 (verification-funnel dimension)
    channel          VARCHAR(16),                           -- AnalyticsChannel (channel-mix dimension)
    active_role      VARCHAR(16),                           -- AnalyticsRole (role-segmentation dimension)

    latency_seconds  BIGINT,                                -- TTFR/TTR/answer-latency measure, in seconds
    breach_type      VARCHAR(8),                            -- BreachType TTFR|TTR on REPORT_ESCALATED (SLA heatmap)
    outcome          VARCHAR(32),                           -- controlled-vocabulary qualifier (CONFIRMED/HIDE/...); never PII

    CONSTRAINT uq_analytics_event_event_id UNIQUE (event_id),
    -- amount-of-time measures are non-negative when present (defence in depth; the producers also guard this).
    CONSTRAINT ck_analytics_event_latency_nonneg CHECK (latency_seconds IS NULL OR latency_seconds >= 0),
    CONSTRAINT ck_analytics_event_tier   CHECK (tier        IS NULL OR tier        IN ('T0','T1','T2','T3')),
    CONSTRAINT ck_analytics_event_breach CHECK (breach_type IS NULL OR breach_type IN ('TTFR','TTR'))
);

-- Time-bucketed counts per event type — the backbone of every dashboard query.
CREATE INDEX ix_analytics_event_type_time ON analytics_event (event_type, occurred_at);
-- Geo + category + time — reports volume / SLA heatmap by area x category x time.
CREATE INDEX ix_analytics_event_geo_cat   ON analytics_event (geo_area_id, category_id, occurred_at);
-- Funnel and channel-mix segmentation.
CREATE INDEX ix_analytics_event_tier      ON analytics_event (tier, occurred_at);
CREATE INDEX ix_analytics_event_channel   ON analytics_event (channel, occurred_at);

COMMENT ON TABLE  analytics_event                 IS 'Append-only, PII-free product-analytics facts powering the §3.3 KPIs and Appendix C dashboards. Never updated/deleted; idempotent on event_id; app is granted only INSERT+SELECT. This is NOT the audit log (Appendix E.4 separation of duties).';
COMMENT ON COLUMN analytics_event.event_id        IS 'Globally-unique idempotency key (the outbox event id); a replayed/duplicated emission is a no-op — no double-count (Appendix E.0/E.3).';
COMMENT ON COLUMN analytics_event.occurred_at     IS 'When the occurrence actually happened (UTC). The pipeline keys on this, not ingest time, so late/offline-synced events do not skew funnels (Appendix E.3).';
COMMENT ON COLUMN analytics_event.actor_ref       IS 'Pseudonymous SALTED HASH of the account — NEVER the UUID/name/phone/national-or-voter ID. Null for guest/pre-auth. PDPA erasure drops the salt mapping, orphaning rows (Appendix E.4).';
COMMENT ON COLUMN analytics_event.geo_area_id     IS 'Geographic-area public id truncated to WARD-OR-COARSER (region/council/ward). Village/hamlet/Mtaa and raw GPS are never recorded (Appendix E.4). Cross-module id only; no FK (ADR-0013).';
COMMENT ON COLUMN analytics_event.latency_seconds IS 'Headline latency in seconds: TTFR (REPORT_FIRST_RESPONDED), TTR (REPORT_RESOLVED), answer latency (QUESTION_ANSWERED), verify latency (IDENTITY_VERIFIED). Aggregated via percentile_cont for p50/p90 (§3.3).';
COMMENT ON COLUMN analytics_event.outcome         IS 'Controlled-vocabulary qualifier (e.g. CONFIRMED/DISPUTED, DUPLICATE_ID/NO_MATCH, HIDE/REMOVE/WARN) for outcome-split dashboards; never free-text/PII.';


-- -----------------------------------------------------------------------------
-- Append-only intent: the application role must not UPDATE/DELETE analytics_event.
-- The concrete REVOKE is environment-specific (the role name differs per deployment),
-- documented here so the DBA enforces it, mirroring token_transaction / audit_event
-- (AUTH-DESIGN §11). Left as a comment to keep the migration portable.
--   REVOKE UPDATE, DELETE ON analytics_event FROM <app_role>;
-- -----------------------------------------------------------------------------
