-- =============================================================================
-- V94__ussd_session.sql  —  Ephemeral USSD dialogue state (ussd module, M13).
--
-- Responsibility: create the `ussd_session` table behind the JPA entity
-- com.taarifu.ussd.domain.model.UssdSession — the DB-backed state of one in-flight
-- USSD dialogue keyed by (msisdn, session_id). MUST match the entity so
-- ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §14, EI-4, UC-D02).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * DB-BACKED, NOT REDIS: the architecture permits "Redis-or-DB-backed" ephemeral
--     USSD state (PRD §16, EI-4) and the build has no Redis dependency; an expires_at
--     TTL gives the same self-cleaning, last-write-wins semantics. The store sits behind
--     UssdSessionStore so a later Redis swap is a local change.
--   * CROSS-MODULE REFERENCE BY ID, not FK: user_public_id (identity), category_id
--     (reporting), ward_id (geography) are bare UUID publicIds of OTHER modules'
--     entities — intentionally NOT FKs, to keep the module boundary clean (ARCHITECTURE
--     §3.2, the parallel-build isolation rule).
--   * MSISDN IS PII (S-4, PDPA): stored only to key the session and link the account;
--     never logged raw; the expires_at sweep keeps it no longer than needed.
--   * ONE LIVE SESSION per (msisdn, session_id): the aggregator guarantees one live
--     session id per dialogue; a duplicate would fork the conversation. The entity's
--     @UniqueConstraint is mirrored here as a full UNIQUE (sessions are hard-deleted on
--     sweep, not soft-deleted, so live-scoping is unnecessary for the key).
--
-- Type mapping contract (entity -> column): as the established modules
--   (String -> varchar(n); enum @Enumerated(STRING) -> varchar(n); UUID -> uuid;
--    Instant -> timestamptz; bigint PK + version; boolean not null default false).
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================

CREATE TABLE ussd_session (
    -- BaseEntity (ARCHITECTURE §4.2): internal PK + public UUID + audit + soft-delete + version.
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    -- Domain columns (UssdSession.java).
    msisdn          VARCHAR(20)  NOT NULL,                 -- caller E.164; session key + account link; PII (S-4)
    session_id      VARCHAR(128) NOT NULL,                 -- aggregator session id (unique per live dialogue)
    step            VARCHAR(24)  NOT NULL,                 -- UssdStep state-machine position
    language        VARCHAR(4),                            -- UssdLanguage SW/EN; null until language chosen
    user_public_id  UUID,                                  -- identity account publicId (T1, MSISDN-linked); bare ref
    category_id     UUID,                                  -- reporting category publicId (file draft); bare ref
    ward_id         UUID,                                  -- geography ward publicId (file draft); bare ref
    description     VARCHAR(1000),                         -- citizen free-text description (file draft)
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,     -- TTL; abandoned dialogue self-cleans (PDPA)

    CONSTRAINT uq_ussd_session_public_id UNIQUE (public_id),
    -- One live session per dialogue key (mirrors the entity @UniqueConstraint).
    CONSTRAINT ux_ussd_session_key UNIQUE (msisdn, session_id),
    -- Enum domain guards mirror Hibernate's generated CHECKs for @Enumerated(STRING) columns.
    CONSTRAINT ck_ussd_session_step CHECK (step IN
        ('LANGUAGE','MAIN_MENU','FILE_CATEGORY','FILE_AREA_CHOICE','FILE_AREA_PICK',
         'FILE_DESCRIPTION','FILE_CONFIRM','TRACK_CODE','ALERTS_CONFIRM','DONE')),
    CONSTRAINT ck_ussd_session_language CHECK (language IN ('SW','EN'))
);

-- Entity-declared index: TTL sweep scans by expires_at.
CREATE INDEX ix_ussd_session_expires ON ussd_session (expires_at);

COMMENT ON TABLE  ussd_session                IS 'Ephemeral USSD dialogue state keyed by (msisdn, session_id); DB-backed (PRD §14, EI-4, UC-D02).';
COMMENT ON COLUMN ussd_session.msisdn         IS 'Caller E.164 phone; session key + account-link key; PII — never logged raw (S-4, PDPA).';
COMMENT ON COLUMN ussd_session.session_id     IS 'Aggregator session id, unique per live dialogue for this MSISDN.';
COMMENT ON COLUMN ussd_session.step           IS 'UssdStep — position in the menu state machine; advanced server-side each keypress.';
COMMENT ON COLUMN ussd_session.language       IS 'UssdLanguage SW/EN (Swahili-first); null until the first screen is answered.';
COMMENT ON COLUMN ussd_session.user_public_id IS 'identity account publicId (T1, MSISDN-linked, EI-4); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN ussd_session.category_id    IS 'reporting issue-category publicId (file-report draft); bare UUID ref, never a FK.';
COMMENT ON COLUMN ussd_session.ward_id        IS 'geography ward publicId (file-report draft; min pin granularity); bare UUID ref, never a FK.';
COMMENT ON COLUMN ussd_session.expires_at     IS 'Session TTL; expired rows are swept so an abandoned dialogue self-cleans and no MSISDN lingers (PDPA).';
