-- =============================================================================
-- V95__ussd_alert_subscription.sql  —  USSD my-area alert intents (ussd module, M13).
--
-- Responsibility: create the `ussd_alert_subscription` table behind the JPA entity
-- com.taarifu.ussd.domain.model.UssdAlertSubscription — a feature-phone citizen's
-- intent (captured over USSD) to receive SMS alerts for their registered area. MUST
-- match the entity so ddl-auto=validate passes (ARCHITECTURE §4.1, PRD §14 menu item 3,
-- EI-3/EI-4).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * WHY LOCAL (not a communications Subscription): the isolation rule forbids this
--     module from writing communications' tables, and that module's Subscription is keyed
--     by a profile id on an authenticated path — unavailable on the USSD webhook. So the
--     intent is captured here and forwarded to communications once a published command
--     port exists (// TODO(wiring); see CENTRAL INTEGRATION NEEDS). `forwarded` tracks that.
--   * CROSS-MODULE REFERENCE BY ID, not FK: user_public_id (identity) and ward_id
--     (geography) are bare UUID publicIds — never FKs (ARCHITECTURE §3.2).
--   * ONE LIVE SUBSCRIPTION per (user, ward): a citizen subscribes an area at most once;
--     unsubscribe is a SOFT-DELETE so history stays auditable (PRD §9) and a re-subscribe
--     inserts a fresh row. JPA cannot express partial uniqueness, so the live-scoped
--     PARTIAL UNIQUE INDEX below is the authoritative guarantee; the entity's
--     @UniqueConstraint documents intent. (validate does not check table-level
--     constraints, so the partial index keeps validate green while being correct.)
--
-- Forward-only; never edit once applied — add a new migration (CLAUDE.md §12).
-- =============================================================================

CREATE TABLE ussd_alert_subscription (
    -- BaseEntity (ARCHITECTURE §4.2).
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID    NOT NULL,
    version         BIGINT  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    -- Domain columns (UssdAlertSubscription.java).
    user_public_id  UUID    NOT NULL,                      -- identity account publicId (MSISDN-linked); bare ref
    ward_id         UUID    NOT NULL,                      -- geography ward publicId; bare ref
    forwarded       BOOLEAN NOT NULL DEFAULT FALSE,        -- forwarded to communications yet? (// TODO(wiring))

    CONSTRAINT uq_ussd_alert_sub_public_id UNIQUE (public_id)
);

-- Entity-declared lookup indexes.
CREATE INDEX ix_ussd_alert_user ON ussd_alert_subscription (user_public_id);
CREATE INDEX ix_ussd_alert_ward ON ussd_alert_subscription (ward_id);

-- INVARIANT (DB-owned): at most ONE LIVE subscription per (user, ward).
-- Scoped to live rows so a soft-deleted (unsubscribed) row never blocks a fresh re-subscribe.
CREATE UNIQUE INDEX ux_ussd_alert_sub_live
    ON ussd_alert_subscription (user_public_id, ward_id)
    WHERE deleted = FALSE;

COMMENT ON TABLE  ussd_alert_subscription                IS 'USSD my-area SMS-alert intent: account wants alerts for a ward (PRD §14 menu 3, EI-3/EI-4).';
COMMENT ON COLUMN ussd_alert_subscription.user_public_id IS 'identity account publicId (MSISDN-linked); bare UUID ref, never a FK (ARCHITECTURE §3.2).';
COMMENT ON COLUMN ussd_alert_subscription.ward_id        IS 'geography ward publicId (subscribed area); bare UUID ref, never a FK.';
COMMENT ON COLUMN ussd_alert_subscription.forwarded      IS 'Whether the intent has been forwarded to communications to register the real preference (// TODO(wiring)).';
