-- =============================================================================
-- V97__common_outbox_event.sql  —  Transactional outbox (shared kernel, common.outbox).
--
-- Responsibility: create the `outbox_event` table behind the JPA entity
-- com.taarifu.common.outbox.domain.model.OutboxEvent — the durable record of
-- "something happened", written in the PRODUCER'S transaction so the domain row and
-- the event commit atomically (ADR-0008; ADR-0014; PRD §15 DI3, §16). MUST match the
-- entity exactly so Hibernate ddl-auto=validate passes (ARCHITECTURE §4.1).
--
-- WHY V97 (the cross-cutting tail, not a feature range): the outbox is shared-kernel
-- infrastructure (common), not a feature module, so it sits with the other late
-- cross-cutting migrations (…V94 ussd, V95 ussd, V96 audit) rather than in a per-module
-- range (ARCHITECTURE §4.1, ADR-0014 §1). Forward-only; never edit once applied — add
-- a new migration (CLAUDE.md §12).
--
-- DESIGN NOTES (the "why", per CLAUDE.md §8):
--   * IS a BaseEntity (ARCHITECTURE §4.2): full id + public_id + audit + soft-delete +
--     version. WHY soft-delete columns though the relay never sets them: the entity
--     extends BaseEntity (DRY); a separate retention job HARD-purges PROCESSED rows older
--     than N days (ADR-0014 "operability") — the poller itself never soft-deletes.
--   * 🔒 PAYLOAD IS jsonb OF ids/codes/enums ONLY — NEVER PII (PRD §18, §12; ADR-0014 §1).
--     No name, phone/MSISDN, email, national/voter ID, OTP, free-text body, or raw GPS
--     ever enters this table: it is queryable, replayable, and dumped in support. Consumers
--     re-read the aggregate by id through the owner's *QueryApi (ADR-0013).
--   * STATUS lifecycle PENDING -> PROCESSED | FAILED (at-least-once delivery, ADR-0014 §3):
--     the relay claims PENDING rows due now, dispatches in-process, marks PROCESSED on
--     success; on handler failure attempts++ with exponential backoff (next_attempt_at) and
--     terminal FAILED after maxAttempts. FAILED rows ARE the DLQ (queryable + alertable).
--   * last_error IS REDACTED — truncated reason only, NO PII, NO stack trace (ADR-0008 §5.2).
--   * aggregate_id IS A BARE PUBLIC UUID of another module's aggregate — intentionally NOT
--     a FK (cross-module references are opaque UUIDs — ADR-0013 §3.2). The outbox is a leaf:
--     nothing FK-references it.
--
-- Type mapping contract (entity -> column), so validate is exact:
--   Long id              -> bigint identity PK
--   UUID public_id       -> uuid not null unique
--   String aggregate_type-> varchar(64)  not null
--   UUID aggregate_id    -> uuid         not null
--   String event_type    -> varchar(96)  not null
--   String payload (JSON)-> jsonb        not null  (@JdbcTypeCode(SqlTypes.JSON) on a String)
--   Instant occurred_at  -> timestamptz  not null
--   String status (enum) -> varchar(16)  not null  (@Enumerated(STRING))
--   int attempts         -> int          not null
--   Instant next_attempt -> timestamptz  not null
--   String last_error    -> varchar(1024) (nullable)
--   Instant processed_at -> timestamptz  (nullable)
-- =============================================================================

CREATE TABLE outbox_event (
    -- BaseEntity (ARCHITECTURE §4.2): internal PK + public UUID + audit + soft-delete + version.
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL,                 -- also the delivery IDEMPOTENCY anchor (== eventId)
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE,
    created_by      UUID,
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      UUID,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      UUID,

    -- Domain columns (OutboxEvent.java).
    aggregate_type  VARCHAR(64)  NOT NULL,                 -- producing aggregate type, e.g. ANNOUNCEMENT / REPORT
    aggregate_id    UUID         NOT NULL,                 -- producing aggregate PUBLIC id; bare UUID, never a FK
    event_type      VARCHAR(96)  NOT NULL,                 -- taxonomy key handlers register on, e.g. ANNOUNCEMENT_PUBLISHED
    payload         JSONB        NOT NULL,                 -- 🔒 ids/codes/enums ONLY — NEVER PII (PRD §18)
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL,     -- domain-time the thing happened (ordering key)
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INT          NOT NULL DEFAULT 0,       -- dispatch attempts so far; drives backoff + FAILED cutoff
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),  -- earliest the relay may (re-)pick this row
    last_error      VARCHAR(1024),                         -- REDACTED last failure reason; no PII, no stack trace
    processed_at    TIMESTAMP WITH TIME ZONE,              -- when it reached PROCESSED or terminal FAILED

    CONSTRAINT uq_outbox_event_public_id UNIQUE (public_id),
    -- Enum domain guard mirrors Hibernate's generated CHECK for the @Enumerated(STRING) column.
    CONSTRAINT ck_outbox_event_status CHECK (status IN ('PENDING','PROCESSED','FAILED')),
    -- Defence in depth: attempt count is never negative (the relay only increments).
    CONSTRAINT ck_outbox_event_attempts_nonneg CHECK (attempts >= 0)
);

-- The relay's ONLY query path: due PENDING rows in occurred order. PARTIAL index on
-- status='PENDING' keeps it tiny as PROCESSED/FAILED rows accumulate before retention purge
-- (ADR-0014 §1 "this table is hot — poll every second").
CREATE INDEX ix_outbox_event_due ON outbox_event (next_attempt_at)
    WHERE status = 'PENDING';

-- Replay / diagnostics by aggregate (e.g. "all events for this report, in order").
CREATE INDEX ix_outbox_event_aggregate ON outbox_event (aggregate_type, aggregate_id, occurred_at);

COMMENT ON TABLE  outbox_event                 IS 'Transactional outbox: durable "something happened" rows written in the producer''s tx; an @Scheduled relay dispatches them in-process to idempotent handlers (ADR-0014, ADR-0008). At-least-once delivery; PENDING -> PROCESSED|FAILED; FAILED rows are the DLQ.';
COMMENT ON COLUMN outbox_event.public_id       IS 'Public event id; ALSO the delivery idempotency key (== EventEnvelope.eventId) handlers dedup on (ADR-0014 §4).';
COMMENT ON COLUMN outbox_event.aggregate_type  IS 'Producing aggregate type (ANNOUNCEMENT / REPORT / …); for routing, diagnostics and replay-by-type.';
COMMENT ON COLUMN outbox_event.aggregate_id    IS 'Producing aggregate PUBLIC id (UUID). Bare cross-module reference — never an internal id, never a FK (ADR-0013 §3.2).';
COMMENT ON COLUMN outbox_event.event_type      IS 'Taxonomy key the DomainEventHandler SPI registers on (e.g. ANNOUNCEMENT_PUBLISHED, REPORT_ROUTED); the dispatcher routes by exact match.';
COMMENT ON COLUMN outbox_event.payload         IS '🔒 Serialised EventEnvelope body — ids/codes/enums ONLY, NEVER PII (PRD §18, §12). The outbox is queryable/replayable/dumped; PII must never leak through it. Consumers re-read the aggregate by id via the owner''s *QueryApi.';
COMMENT ON COLUMN outbox_event.occurred_at     IS 'Domain-time the event happened (UTC), set by the producer. Best-effort batch ordering key — delivery order is NOT guaranteed (ADR-0014 ordering caveats).';
COMMENT ON COLUMN outbox_event.status          IS 'PENDING (awaiting dispatch) | PROCESSED (all handlers succeeded) | FAILED (terminal after maxAttempts — the DLQ).';
COMMENT ON COLUMN outbox_event.next_attempt_at IS 'Earliest instant the relay may (re-)pick this row. Set to now() on insert; on handler failure pushed out by exponential backoff-with-jitter (ADR-0014 §3).';
COMMENT ON COLUMN outbox_event.last_error      IS 'REDACTED last-failure reason (truncated) for diagnostics — NO PII, NO stack trace (ADR-0008 §5.2).';
